# Generated by Django 1.10.8 on 2018-02-03 22:26
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matsucon2018", "0003_signupextra_shirt_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="signupextra",
            name="shift_type",
            field=models.CharField(
                choices=[
                    ("lb", "Pitkät vuorot molempina päivinä (4h/vuoro/päivä)"),
                    ("sb", "Lyhyitä vuoroja molempina päivinä (2h/vuoro, 4h/päivä)"),
                    ("as", "Kaikki vuorot lauantaina"),
                    ("au", "Kaikki vuorot sunnuntaina"),
                ],
                default="au",
                help_text="Jokaisen työvoimaan kuuluvan on tehtävä vähintään 8 tuntia töitä. Työvuorotoiveet yritetään huomioida vuoroja jaettaessa. Jos haluat kaikki vuorot samalle päivälle, vuorot jaetaan niin että pääset pitämään taukoa välissä.",
                max_length=2,
                verbose_name="Valitse toivomasi työvuoro",
            ),
            preserve_default=False,
        ),
    ]
