# Generated by Django 5.1.5 on 2025-04-23 15:10

import django.core.validators
from django.db import migrations, models

import kompassi.dimensions.models.dimension


class Migration(migrations.Migration):
    dependencies = [
        ("dimensions", "0007_dimension_is_technical_dimensionvalue_is_technical"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dimension",
            name="slug",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Tekninen nimi saa sisältää vain pieniä kirjaimia, numeroita sekä väliviivoja.",
                        regex="^[a-z0-9-]+$",
                    ),
                    kompassi.dimensions.models.dimension.invalid_slugs_validator,
                ],
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="dimensionvalue",
            name="slug",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Tekninen nimi saa sisältää vain pieniä kirjaimia, numeroita sekä väliviivoja.",
                        regex="^[a-z0-9-]+$",
                    )
                ],
                verbose_name="Slug",
            ),
        ),
    ]
