# Generated by Django 5.1.5 on 2025-04-27 22:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("dimensions", "0008_alter_dimension_slug_alter_dimensionvalue_slug"),
        ("forms", "0039_survey_cached_default_dimensions_and_more"),
    ]

    operations = [  # noqa: RUF012
        migrations.RemoveField(
            model_name="dimensionvalue",
            name="is_initial",
        ),
    ]
