# Generated by Django 5.1.5 on 2025-05-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dimensions", "0009_remove_dimensionvalue_is_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="universe",
            name="app",
            field=models.CharField(
                choices=[("forms", "Surveys V2"), ("program_v2", "Program V2"), ("involvement", "Involvement")],
                max_length=11,
            ),
        ),
    ]
