# Generated by Django 5.2.1 on 2025-05-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dimensions", "0010_alter_universe_app"),
    ]

    operations = [
        migrations.AddField(
            model_name="dimensionvalue",
            name="is_subject_locked",
            field=models.BooleanField(
                default=False,
                help_text="If set, subjects this value is assigned to can no longer be edited by whomever submitted them.",
            ),
        ),
    ]
