# Generated by Django 5.2.4 on 2025-07-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dimensions", "0013_dimension_can_values_be_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dimension",
            name="can_values_be_added",
            field=models.BooleanField(
                default=True,
                help_text="If set, users can add values to this dimension in the UI and values added by the user can be edited. Some technical dimensions may allow adding values and some may not.",
            ),
        ),
    ]
