# Generated by Django 5.2.4 on 2025-08-27 18:17

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dimensions", "0016_alter_universeannotation_form_fields"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="annotation",
            name="dimensions_Annotation_type_AnnotationDataType",
        ),
        migrations.AlterField(
            model_name="annotation",
            name="type",
            field=django_enum.fields.EnumCharField(
                choices=[("string", "STRING"), ("number", "NUMBER"), ("boolean", "BOOLEAN"), ("datetime", "DATETIME")],
                max_length=8,
            ),
        ),
        migrations.AddConstraint(
            model_name="annotation",
            constraint=models.CheckConstraint(
                condition=models.Q(("type__in", ["string", "number", "boolean", "datetime"])),
                name="dimensions_Annotation_type_AnnotationDataType",
            ),
        ),
    ]
