# Generated by Django 6.0.1 on 2026-01-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("desucon2026", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signupextra",
            name="total_work",
            field=models.CharField(
                choices=[("12h", "12h"), ("15h", "15h"), ("18h", "18h tai enemmän")],
                help_text="Kuinka paljon haluat tehdä töitä yhteensä tapahtuman aikana? Minimi on pääsääntöisesti 12 tuntia. 15 tuntia töitä tekevät saavat palkkioksi ylimääräisen ruokalipun street food -pisteelle sekä uniikin Desucon Seal of Approval -tarran. 18 tuntia tai enemmän tekevät saavat palkkioksi edellä mainittujen lisäksi vaihtuvan oheistuotteen.",
                max_length=3,
                verbose_name="Toivottu kokonaistyömäärä",
            ),
        ),
    ]
