title: Hae artesaanipöytää
description: |
  Tällä lomakkeella haetaan artesaanipöytää Tracon-tapahtumasta 6.-8.9.2024. Artesaanialue sijaitsee sisätiloissa ja on auki perjantaista sunnuntaihin. Edellytämme artesaanipyödän pitämistä auki ennalta ilmoitettuina myyntiaikoina.

  Artesaanipöydän hinta perjantaista sunnuntaihin on 350 €, sisältäen 2 kpl viikonloppurannekkeita.

  <strong>Lisätietoja suomeksi:</strong> <a href="https://2024.tracon.fi/artesaanihaku/">Artesaanihaku</a>.
fields:
  - type: StaticText
    title: Perustiedot
    slug: basic_info_title

  - slug: name
    title: Vastuuhenkilön etu- ja sukunimi
    type: SingleLineText
    required: true

  - slug: email
    title: Vastuuhenkilön sähköposti
    type: SingleLineText
    required: true

  - slug: helper_name
    title: Apumyyjän nimi
    type: SingleLineText

  - slug: portfolio_title
    type: StaticText
    title: Portfolio
    helpText: >
      Ethän käytä portfoliopohjana sosiaalista mediaa (Facebook, Instagram, Twitter tms) tai taidesivustoa josta löytää kaiken tuotantosi. Portfolion tulee olla varta vasten portfolioksi rakennettu sivu / tiedosto tai muu asiansa ajava pohja. Varmistathan ettei jaetun linkin sisältö ole suojattu salasanalla.

  - slug: portfolio_link
    title: Portfolion linkki
    type: MultiLineText
    required: true
    helpText: >
      Portfolion linkki. Enintään yksi (1) linkki per henkilö.

  - slug: artist_info_title
    type: StaticText
    title: Tiedot verkkosivujen esittelyihin
    helpText: >
      Taiteilijatiedot julkaistaan Traconin verkkosivuilla lähempänä tapahtumaa.

  - slug: artist_name
    title: Taiteilijanimi
    required: true
    type: SingleLineText

  - slug: artist_website
    title: Linkki taiteilijan kotisivuille
    type: SingleLineText
    required: true

  - slug: artist_intro
    title: Lyhyt esittelyteksti
    type: MultiLineText
    required: true

  - slug: artist_avatar
    title: Avatar-kuva
    helpText: "Koko 200 px x 200 px. Suosimme .jpg ja .png -tiedostoja."
    type: FileUpload
    required: true

  - slug: additional_details_title
    type: StaticText
    title: Lisätiedot

  - slug: additional_details
    helpText: >
      Vapaa kenttä kommenteille, toiveille, maininta esteettömyyden tarpeesta ja esimerkiksi perusteluille pöytätoiveiden suhteen.
    type: MultiLineText

  - slug: data_protection_text
    type: StaticText
    title: Tietosuoja
    helpText: >
      Rekisterinpitäjä on Tracon ry edustajanaan Niina "Nino" Kytöharju.
      Tietoja käytetään tamperelaisen Tracon -tapahtuman artesaanialueen järjestämiseen.
      Tietoja säilytetään tapahtumavuoden ajan ja sen jälkeen ne poistetaan.
      Tietoja ei luovuteta ulkopuolisille.
      Tietoja ei käytetä suoramarkkinointiin.
      Tietoja ei siirretä EU:n tai Euroopan talousalueen ulkopuolelle.
      Luovutetut taiteilijatiedot (taiteilijanimi, web-osoite, kuvaus ja avatar) lisätään tapahtuman kotisivuille.
