title: Apply for Artisan Spot
description: |
  This form is used to apply for Artisan spots at the Tracon event on the 6th to 8th of September 2024. The Artisan area is located indoors and the area is open from Friday to Sunday during convention weekend. We require the Artisan tables to be open during the pre-announced sales hours.

  The price of the Artisan spot from Friday to Sunday is 350 €. The price includes 2 tickets.

  <strong>Information in English:</strong> <a href="https://2024.tracon.fi/apply-as-artisan/">Apply as Artisan</a>.
fields:
  - type: StaticText
    title: Basic info
    slug: basic_info_title

  - slug: name
    title: Contact person's first name and surname
    type: SingleLineText
    required: true

  - slug: email
    title: Contact person's email
    type: SingleLineText
    required: true

  - slug: helper_name
    title: Helper's name
    type: SingleLineText

  - slug: portfolio_title
    type: StaticText
    title: Portfolio
    helpText: >
      Please do not use social media platforms as the base of your portfolio (Facebook, Instagram, Twitter etc.) or an art site that consists all of your production.

  - slug: portfolio_link
    title: Portfolio link
    type: MultiLineText
    required: true
    helpText: >
      Portfolio, one (1) link per person.

  - slug: artist_info_title
    type: StaticText
    title: Information for artist profile on event website
    helpText: >
      Artist info will be published on the event website later.

  - slug: artist_name
    title: Artist name
    required: true
    type: SingleLineText

  - slug: artist_website
    title: Artist website link
    required: true
    type: SingleLineText

  - slug: artist_intro
    title: Short introduction
    required: true
    type: MultiLineText

  - slug: artist_avatar
    title: Avatar picture
    helpText: "Size 200 px x 200 px. Files .jpg or .png preferred."
    required: true
    type: FileUpload

  - slug: additional_details_title
    type: StaticText
    title: Additional details

  - slug: additional_details
    helpText: >
      Section for comments, wishes, accessibility need requests etc.
    type: MultiLineText

  - slug: data_protection_text
    type: StaticText
    title: Data protection
    helpText: >
      The controller of personal data is Tracon ry represented by Niina "Nino" Kytöharju.
      The information is used to organize the Artisan area of the Tracon event in Tampere.
      The information is stored for the duration of the event year and then deleted.
      The information is not disclosed to third parties. The information is not used for direct marketing.
      The information is not transferred outside the EU or the European Economic Area.
      The submitted artist information (artist name, website, description and avatar) will be added to the event's homepage.
