# Generated by Django 1.10.6 on 2017-04-16 17:48
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_auto_20160704_2155"),
        ("surveys", "0002_auto_20170321_2103"),
        ("event_log", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="event",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.Event"
            ),
        ),
        migrations.AddField(
            model_name="entry",
            name="event_survey_result",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="surveys.EventSurveyResult"
            ),
        ),
        migrations.AddField(
            model_name="entry",
            name="global_survey_result",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="surveys.GlobalSurveyResult"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="callback_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Code path to a callback function. Only used when channel=callback. Eg. event_log.tests:test_callback.",
                max_length=255,
                verbose_name="Callback function",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="event_filter",
            field=models.ForeignKey(
                blank=True,
                help_text="When specified, only entries related to this event will match the subscription.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.Event",
                verbose_name="Event filter",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="channel",
            field=models.CharField(
                choices=[("email", "E-mail"), ("callback", "Callback")], default="email", max_length=8
            ),
        ),
    ]
