# Generated by Django 5.0.9 on 2024-09-27 14:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event_log", "0014_remove_entry_feedback_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entry",
            name="accommodation_information",
        ),
    ]
