# Generated by Django 5.0.10 on 2024-12-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_v2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_per_order',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
