# Generated by Django 5.0.10 on 2025-01-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets_v2", "0002_product_ordering_alter_paymentstamp_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketsv2eventmeta",
            name="terms_and_conditions_url_en",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="ticketsv2eventmeta",
            name="terms_and_conditions_url_fi",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="ticketsv2eventmeta",
            name="terms_and_conditions_url_sv",
            field=models.TextField(default=""),
        ),
    ]
