# Generated by Django 4.2.8 on 2023-12-28 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hitpoint2024", "0002_alter_signupextra_shirt_size"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SignupExtra",
        ),
    ]
