# Generated by Django 5.1.5 on 2025-03-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ropecon2025", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="signupextra",
            name="certificate_delivery_address",
        ),
        migrations.AlterField(
            model_name="signupextra",
            name="free_text",
            field=models.TextField(
                blank=True,
                help_text="If you want to share something to the application reviewers that doesn't have a dedicated field above, please use this field.",
                verbose_name="Vapaa alue",
            ),
        ),
        migrations.AlterField(
            model_name="signupextra",
            name="prior_experience",
            field=models.TextField(
                blank=True,
                help_text="If you have work, volunteer work or other experience you think might be useful in the work station you are applying for, you can provide the information here.",
                verbose_name="Työkokemus",
            ),
        ),
        migrations.AlterField(
            model_name="signupextra",
            name="shift_type",
            field=models.CharField(
                choices=[
                    ("yksipitka", "Yksi pitkä vuoro"),
                    ("montalyhytta", "Monta lyhyempää vuoroa"),
                    ("kaikkikay", "Kumpi tahansa käy"),
                ],
                help_text="Would you like to work one long shift or multiple shorter shifts?",
                max_length=15,
                verbose_name="Toivottu työvuoron pituus",
            ),
        ),
        migrations.AlterField(
            model_name="signupextra",
            name="shift_wishes",
            field=models.TextField(
                blank=True,
                help_text="If you already know that you will not be able to attend a certain time or want to participate in a programme, you can provide the information here. Note that depending on the workstation, shifts may also take place before and after the event opening hours (on Thursday, Friday morning and Sunday evening) as well as during the nighttime (between 10:00 PM and 6:00 AM). Final shift preference surveys will be sent out in the summer after the programme for Ropecon 2025 is published.",
                verbose_name="Alustavat työvuorotoiveet",
            ),
        ),
        migrations.AlterField(
            model_name="signupextra",
            name="special_diet_other",
            field=models.TextField(
                blank=True,
                help_text="If you are on a special diet that is not listed above, you can add it here. The event organizers will take special dietary needs into consideration, but it may not be possible to cater to all of them.",
                verbose_name="Muu erikoisruokavalio",
            ),
        ),
        migrations.AlterField(
            model_name="signupextra",
            name="want_certificate",
            field=models.BooleanField(
                default=False,
                help_text="Work certificates will be sent to the email address provided after the event.",
                verbose_name="Haluan todistuksen työskentelystäni Ropeconissa",
            ),
        ),
    ]
