# Generated by Django 1.9.1 on 2016-01-29 13:53


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0005_badge_layout"),
    ]

    operations = [
        migrations.AddField(
            model_name="badgeseventmeta",
            name="real_name_must_be_visible",
            field=models.BooleanField(
                default=False,
                help_text='In most events, it is up to the person carrying the badge to decide whether or not their real name is displayed in their badge. Some choose to go by their first name or nick name only. Some events have, however, decided to restrict this and require the first name and surname to be visible in all badges. If this option is selected, only the name display styles <em>Firstname Surname</em> and <em>Firstname "Nick" Surname</em> are effectively allowed.',
                verbose_name="Require real name to be visible",
            ),
        ),
    ]
