# Generated by Django 1.9.2 on 2016-02-02 00:22


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0016_auto_20160129_2339"),
    ]

    operations = [
        migrations.CreateModel(
            name="BadgeManagementProxy",
            fields=[],
            options={
                "proxy": True,
            },
            bases=("badges.badge",),
        ),
    ]
