# Generated by Django 4.2.5 on 2023-10-11 09:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0025_badgeseventmeta_onboarding_instructions_markdown"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="badgeseventmeta",
            name="badge_layout",
        ),
    ]
