# Generated by Django 5.1.5 on 2025-05-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0030_alter_surveytobadgemapping_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badgeseventmeta",
            name="emperkelator_name",
            field=models.CharField(
                choices=[
                    ("noop", "Noop (no perks)"),
                    ("simple", "Simple (perks from personnel class)"),
                    ("tracon2024", "Tracon (2024)"),
                    ("desucon2025", "Desucon (2025)"),
                ],
                default="noop",
                help_text="The emperkelator defines the perks of a volunteer in the event based on their involvement with the event.",
                max_length=63,
                verbose_name="Emperkelator",
            ),
        ),
    ]
