# Generated by Django 5.2.4 on 2025-08-08 21:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0031_alter_badgeseventmeta_emperkelator_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="badgeseventmeta",
            name="emperkelator_name",
        ),
    ]
