# Generated by Django 5.2.8 on 2025-12-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0032_remove_badgeseventmeta_emperkelator_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="job_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Please stay civil with the job title field.",
                max_length=255,
                verbose_name="Job title",
            ),
        ),
    ]
