# Generated by Django 6.1 on 2026-09-02 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("badges", "0033_alter_badge_job_title"),
        ("involvement", "0013_registry_default_retention_period"),
    ]

    operations = [  # noqa: RUF012
        migrations.AddField(
            model_name="badgeseventmeta",
            name="registry",
            field=models.ForeignKey(
                blank=True,
                help_text="The personal data registry the badges of this event belong to. Badges are deleted after the default retention period of the registry has passed since the end time of the event.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="badges_event_metas",
                to="involvement.registry",
                verbose_name="Registry",
            ),
        ),
    ]
