# Generated by Django 4.2.6 on 2023-11-09 18:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0010_eventform_thank_you_message_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventformresponse",
            old_name="values",
            new_name="form_data",
        ),
        migrations.RenameField(
            model_name="globalformresponse",
            old_name="values",
            new_name="form_data",
        ),
    ]
