# Generated by Django 5.0.4 on 2024-06-09 12:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracon2023", "0003_signupextraafterpartyproxy_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SignupExtraAfterpartyProxy",
        ),
    ]
