minimum_pre_commit_version: 2.15.0

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.4.9"
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
        args:
          - --quiet
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
        exclude: .*__generated__.*
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        exclude: |
          (?x)(
            .*__generated__.*|
            ^backend|
            ^.github
          )
  # XXX somehow the typechecking still leaks to parts of the code that is not yet ready for pyrekt
  # - repo: https://github.com/RobertCraigie/pyright-python
  #   rev: v1.1.367
  #   hooks:
  #     - id: pyright
  #       language: system
  #       # add apps as they become fully typechecked
  #       files: |
  #         (?x)(
  #           ^backend/directory/|
  #           ^backend/program_v2/|
  #         )
