minimum_pre_commit_version: 2.15.0

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.4
    hooks:
      - id: ruff-check
        args:
          - --fix
      - id: ruff-format
        args:
          - --quiet
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
        exclude: .*__generated__.*
      - id: trailing-whitespace
  # - repo: local
  #   hooks:
  #     - id: prettier
  #       name: prettier
  #       entry: prettier
  #       args: [--check, --ignore-unknown]
  #       language: node
  #       types_or: [javascript, jsx, ts, tsx]
  #       files: ^kompassi-v2-frontend/
  #       additional_dependencies:
  #         - prettier@3.9.6
  # XXX somehow the typechecking still leaks to parts of the code that is not yet ready for pyrekt
  # - repo: https://github.com/RobertCraigie/pyright-python
  #   rev: v1.1.367
  #   hooks:
  #     - id: pyright
  #       language: system
  #       # add apps as they become fully typechecked
  #       files: |
  #         (?x)(
  #           ^backend/directory/|
  #           ^backend/program_v2/|
  #         )
