#!/bin/bash

set -ue

# Allow setting either DATABASE_URL (takes precedence) or KOMPASSI_POSTGRESQL_*
KOMPASSI_POSTGRESQL_USERNAME="${KOMPASSI_POSTGRESQL_USERNAME:-kompassi}"
KOMPASSI_POSTGRESQL_PASSWORD="${KOMPASSI_POSTGRESQL_PASSWORD:-secret}"
KOMPASSI_POSTGRESQL_HOSTNAME="${KOMPASSI_POSTGRESQL_HOSTNAME:-postgres}"
KOMPASSI_POSTGRESQL_DATABASE="${KOMPASSI_POSTGRESQL_DATABASE:-kompassi}"
export DATABASE_URL="${DATABASE_URL:-psql://$KOMPASSI_POSTGRESQL_USERNAME:$KOMPASSI_POSTGRESQL_PASSWORD@$KOMPASSI_POSTGRESQL_HOSTNAME/$KOMPASSI_POSTGRESQL_DATABASE}"

# Allow setting either BROKER_URL (takes precedence) or KOMPASSI_RABBITMQ_*
KOMPASSI_RABBITMQ_USERNAME="${KOMPASSI_RABBITMQ_USERNAME:-kompassi}"
KOMPASSI_RABBITMQ_PASSWORD="${KOMPASSI_RABBITMQ_PASSWORD:-secret}"
KOMPASSI_RABBITMQ_HOSTNAME="${KOMPASSI_RABBITMQ_HOSTNAME:-rabbitmq}"
KOMPASSI_RABBITMQ_VHOST="${KOMPASSI_RABBITMQ_VHOST:-}"
export BROKER_URL="${BROKER_URL:-rabbitmq://$KOMPASSI_RABBITMQ_USERNAME:$KOMPASSI_RABBITMQ_PASSWORD@$KOMPASSI_RABBITMQ_HOSTNAME/$KOMPASSI_RABBITMQ_VHOST}"
export KOMPAQ_URL="${KOMPAQ_URL:-$BROKER_URL}"

exec "$@"
