ARG FRONTEND_IMAGE
FROM $FRONTEND_IMAGE

ARG PUBLIC_URL
ARG REACT_APP_KOMPASSI_BASE_URL
ARG REACT_APP_CLIENT_ID

USER root

ENV NODE_ENV=production
RUN env
RUN npm run build

FROM nginx:1-alpine
COPY --from=0 /usr/src/app/build/ /usr/share/nginx/html/
COPY nginx_default.conf /etc/nginx/conf.d/default.conf
