apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: edegal

build:
  local:
    useBuildkit: true
  artifacts:
    - image: kompassi
      context: .

deploy:
  statusCheckDeadlineSeconds: 600
  kubectl:
    manifests:
      - kubernetes/*.json
