# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_event_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='state',
            field=models.CharField(choices=[(b'valid', 'Valid'), (b'used', 'Used'), (b'revoked', 'Revoked')], default=b'valid', max_length=8),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='state',
            field=models.CharField(choices=[(b'valid', 'Valid'), (b'used', 'Used'), (b'revoked', 'Revoked')], default=b'valid', max_length=8),
        ),
    ]
