# Generated by Django 1.9.5 on 2016-07-04 18:55


import core.models.person
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_auto_20160202_2235"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Puhelinnumeroasi k\xe4ytet\xe4\xe4n tarvittaessa kiireellisiin yhteydenottoihin koskien osallistumistasi tapahtumaan.",
                max_length=255,
                validators=[core.models.person.phone_number_validator],
                verbose_name="Puhelinnumero",
            ),
        ),
    ]
