# Generated by Django 1.10.7 on 2017-07-22 16:13
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_auto_20160704_2155"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarouselSlide",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("active_from", models.DateTimeField(blank=True, null=True)),
                ("active_until", models.DateTimeField(blank=True, null=True)),
                ("href", models.CharField(blank=True, default="", max_length=512)),
                ("title", models.CharField(blank=True, default="", max_length=512)),
                ("image_file", models.FileField(blank=True, upload_to="carousel_slides")),
                ("image_credit", models.CharField(blank=True, default="", max_length=512)),
                (
                    "target",
                    models.CharField(choices=[("", "Same window"), ("_blank", "New window")], default="", max_length=6),
                ),
            ],
        ),
    ]
