# Generated by Django 4.0.6 on 2022-07-30 07:09

from django.db import migrations, models


def populate_panel_classes(apps, schema_editor):
    Organization = apps.get_model("core", "Organization")
    Organization.objects.filter(slug="tracon-ry").update(panel_css_class="panel-danger")
    Organization.objects.filter(slug="kehittyvien-conien-suomi-ry").update(panel_css_class="panel-success")
    Organization.objects.filter(slug="finnish-fandom-conventions-ry").update(panel_css_class="panel-warning")
    Organization.objects.filter(slug="ropecon-ry").update(panel_css_class="panel-ropecon panel-default")
    Organization.objects.filter(slug="yukitea-ry").update(panel_css_class="panel-info")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_person_discord_handle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="panel_css_class",
        ),
        migrations.AddField(
            model_name="organization",
            name="panel_css_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("panel-default", "Harmaa"),
                    ("panel-primary", "Kompassi (turkoosi)"),
                    ("panel-success", "Desucon (vihreä)"),
                    ("panel-info", "Yukicon (vaaleansininen)"),
                    ("panel-warning", "Popcult (oranssi)"),
                    ("panel-danger", "Tracon (punainen)"),
                ],
                default="panel-default",
                max_length=255,
                verbose_name="Etusivun paneelin väri",
            ),
        ),
        migrations.RunPython(populate_panel_classes),
    ]
