# Generated by Django 1.10.8 on 2018-04-29 17:12
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finncon2018", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="signupextra",
            name="language_skills",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Kerro kielitaidostasi erityisesti suomen, ruotsin ja englannin kielissä.",
                verbose_name="Kielitaito",
            ),
        ),
        migrations.AlterField(
            model_name="signupextra",
            name="dead_dog",
            field=models.BooleanField(
                default=False,
                help_text="Dead dogit ovat heti tapahtuman jälkeen järjestettävät kestit kaikille täysikäisille työvoimaan kuuluville. Ilmoittautuminen ei ole sitova.",
                verbose_name="Osallistun dead dogeihin",
            ),
        ),
    ]
