# Generated by Django 4.2.1 on 2023-10-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kotaeexpo2024", "0003_accommodation_knownlanguage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signupextra",
            name="total_work",
            field=models.CharField(
                choices=[
                    ("4h", "4 tuntia - Minivuoro"),
                    ("8h", "8 tuntia - Täysvuoro"),
                    ("yli10h", "Yli 10 tuntia - Supervuoro!"),
                ],
                help_text="Kuinka paljon haluat tehdä töitä yhteensä tapahtuman aikana? Huomaathan, ettei 4 tunnin työpanos oikeuta täysiin työvoimaetuihin. Tarkasta työvoimaedut Kotaen verkkosivuilta.",
                max_length=15,
                verbose_name="Toivottu kokonaistyömäärä",
            ),
        ),
    ]
