# Generated by Django 2.1.12 on 2019-11-26 15:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0003_form_login_required"),
    ]

    operations = [
        migrations.RenameField(
            model_name="form",
            old_name="is_active",
            new_name="active",
        ),
        migrations.RenameField(
            model_name="form",
            old_name="is_standalone",
            new_name="standalone",
        ),
    ]
