# Generated by Django 4.2.6 on 2023-11-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("forms", "0007_eventform_eventformresponse_globalform_and_more"),
    ]

    operations = [  # noqa: RUF012
        migrations.AddField(
            model_name="eventform",
            name="language",
            field=models.CharField(choices=[("fi", "Finnish"), ("en", "English")], default="fi", max_length=2),
        ),
        migrations.AddField(
            model_name="globalform",
            name="language",
            field=models.CharField(choices=[("fi", "Finnish"), ("en", "English")], default="fi", max_length=2),
        ),
    ]
