# Generated by Django 4.2.8 on 2023-12-23 10:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0012_alter_eventform_language_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventsurvey",
            name="active",
        ),
        migrations.RemoveField(
            model_name="eventsurvey",
            name="standalone",
        ),
        migrations.RemoveField(
            model_name="globalsurvey",
            name="active",
        ),
        migrations.RemoveField(
            model_name="globalsurvey",
            name="standalone",
        ),
    ]
