# Generated by Django 4.2.9 on 2024-01-07 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forms", "0014_rename_eventsurvey_survey_delete_globalsurvey"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GlobalFormResponse",
            new_name="Response",
        ),
        migrations.AlterField(
            model_name="response",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="responses", to="forms.eventform"
            ),
        ),
        migrations.DeleteModel(
            name="EventFormResponse",
        ),
    ]
