# Generated by Django 4.2.9 on 2024-01-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0017_survey_key_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="anonymity",
            field=models.CharField(
                choices=[
                    ("hard", "Hard anonymous"),
                    ("soft", "Soft anonymous (linked to user account but not shown to survey owner)"),
                    ("name_and_email", "Name and email shown to survey owner if responded logged-in"),
                ],
                default="soft",
                help_text="Hard anonymous: responses are not linked to user accounts and IP addresses are not recorded. Soft anonymous: responses are linked to user accounts but not shown to survey owners. Name and email: responses are linked to user accounts and shown to survey owners.",
                max_length=14,
                verbose_name="anonymity",
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="max_responses_per_user",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Maximum number of responses per user. 0 = unlimited. Note that if login_required is not set, this only takes effect for logged in users.Has no effect if the survey is hard anonymous.",
                verbose_name="max responses per user",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="login_required",
            field=models.BooleanField(default=False, verbose_name="Login required"),
        ),
    ]
