# Generated by Django 5.0.1 on 2024-01-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0021_dimension_is_multi_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="dimension",
            name="is_shown_to_respondent",
            field=models.BooleanField(
                default=False,
                help_text="If set, the respondent will see the value of the dimension in the profile survey responses list.",
            ),
        ),
    ]
