# Generated by Django 5.0.2 on 2024-02-12 18:25

from django.db import migrations, models


def number_existing_responses(apps, schema_editor):
    Response = apps.get_model("forms", "Response")
    Survey = apps.get_model("forms", "Survey")

    for survey in Survey.objects.all():
        responses = Response.objects.filter(
            form__in=survey.languages.all(),
            sequence_number=0,
        ).order_by("created_at")
        for i, response in enumerate(responses):
            response.sequence_number = i + 1
            response.save(update_fields=["sequence_number"])


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0022_dimension_is_shown_to_respondent"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="sequence_number",
            field=models.PositiveIntegerField(
                default=0, help_text="Sequence number of this response within the use case (eg. survey)."
            ),
        ),
        migrations.RunPython(number_existing_responses, reverse_code=migrations.RunPython.noop),
    ]
