# Generated by Django 5.0.9 on 2024-11-30 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dimensions", "0002_populate"),
        ("forms", "0030_responsedimensionvalue_new_value_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dimensionvalue",
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name="responsedimensionvalue",
            unique_together={("response", "new_value")},
        ),
        migrations.AlterField(
            model_name="responsedimensionvalue",
            name="new_value",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, related_name="+", to="dimensions.dimensionvalue"
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="dimensionvalue",
            name="dimension",
        ),
        migrations.RemoveField(
            model_name="responsedimensionvalue",
            name="dimension",
        ),
        migrations.RemoveField(
            model_name="responsedimensionvalue",
            name="value",
        ),
        migrations.DeleteModel(
            name="Dimension",
        ),
        migrations.DeleteModel(
            name="DimensionValue",
        ),
    ]
