# Generated by Django 5.0.9 on 2024-11-30 15:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("dimensions", "0002_populate"),
        ("forms", "0031_remove_dimensionvalue_dimension_and_more"),
    ]

    operations = [  # noqa: RUF012
        migrations.RenameField(
            model_name="responsedimensionvalue",
            old_name="new_value",
            new_name="value",
        ),
        migrations.AlterUniqueTogether(
            name="responsedimensionvalue",
            unique_together={("response", "value")},
        ),
    ]
