# Generated by Django 5.1.5 on 2025-05-11 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0039_survey_cached_default_dimensions_and_more"),
        ("involvement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="registry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="surveys",
                to="involvement.registry",
            ),
        ),
    ]
