# Generated by Django 5.2.1 on 2025-06-14 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dimensions", "0011_dimensionvalue_is_subject_locked"),
        ("forms", "0047_survey_universe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="universe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="surveys", to="dimensions.universe"
            ),
        ),
    ]
