# Generated by Django 5.2.3 on 2025-07-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0048_alter_survey_universe"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="cached_default_involvement_dimensions",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
