# Generated by Django 5.2.3 on 2025-07-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0049_survey_cached_default_involvement_dimensions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="app_name",
            field=models.CharField(
                choices=[("forms", "forms"), ("program_v2", "program_v2"), ("involvement", "involvement")],
                default="forms",
                help_text="Which app manages this survey?",
                max_length=11,
            ),
        ),
    ]
