# Generated by Django 5.2.4 on 2025-09-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0053_surveydefaultinvolvementdimensionvalue"),
    ]

    operations = [
        migrations.AddField(
            model_name="projection",
            name="special_fields",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Which special fields to include. Supported: responseId, createdAt, updatedAt.",
            ),
        ),
    ]
