# Generated by Django 6.1 on 2026-09-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("forms", "0057_rename_survey_app_name_purpose_slug"),
    ]

    operations = [  # noqa: RUF012
        migrations.AddField(
            model_name="survey",
            name="retention_period",
            field=models.DurationField(
                blank=True,
                help_text="Overrides the default retention period of the registry for the responses of this survey. Counted from the end of the year in which the event ends or, lacking that, in which the response was created.",
                null=True,
                verbose_name="retention period",
            ),
        ),
    ]
