# Generated by Django 6.1.1 on 2026-10-02 13:45

import django.db.models.deletion
import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("core", "0045_person_program_role_retention_policy"),
        ("dimensions", "0020_propagate_annotation_form_fields_to_forms"),
        ("forms", "0058_survey_retention_period"),
        ("involvement", "0014_alter_involvementeventmeta_default_registry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [  # noqa: RUF012
        migrations.RemoveConstraint(
            model_name="survey",
            name="forms_Survey_purpose_SurveyPurpose",
        ),
        migrations.AddField(
            model_name="response",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Reserved: the response a follow-up response follows up on. Must always point to the newest version of the parent response.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="followups",
                to="forms.response",
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Reserved for follow-up surveys that follow up on the responses of a parent survey.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="followups",
                to="forms.survey",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="purpose",
            field=django_enum.fields.EnumCharField(
                choices=[("DEFAULT", "DEFAULT"), ("INVITE", "INVITE"), ("FOLLOWUP", "FOLLOWUP")],
                default="DEFAULT",
                help_text="Generic surveys and program offers are DEFAULT, program host invitations are INVITE, follow-up questions to existing program hosts are FOLLOWUP.",
                max_length=8,
            ),
        ),
        migrations.AddConstraint(
            model_name="survey",
            constraint=models.CheckConstraint(
                condition=models.Q(("purpose__in", ["DEFAULT", "INVITE", "FOLLOWUP"])),
                name="forms_Survey_purpose_SurveyPurpose",
            ),
        ),
    ]
