{{- if not .Values.backend.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: kompassi
  labels:
    {{- include "kompassi.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.backend.secret }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
{{- if not .Values.backend.existingPostgresSecretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres
  labels:
    {{- include "kompassi.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.backend.postgresSecret }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
{{- if not .Values.frontend.existingSecretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: kompassi2
  labels:
    {{- include "kompassi.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.frontend.secret }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
