# Generated by Django 2.2.10 on 2020-07-23 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_event_cancelled"),
        ("membership", "0015_auto_20190921_1449"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="membership",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="membershipfeepayment",
            name="reference_number",
            field=models.CharField(blank=True, db_index=True, max_length=31, verbose_name="Viitenumero"),
        ),
        migrations.AddField(
            model_name="term",
            name="reference_number_template",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="membershipfeepayment",
            name="amount_cents",
            field=models.PositiveIntegerField(
                help_text="TODO vaihda kälissä euroiks", verbose_name="Maksettu summa (snt)"
            ),
        ),
        migrations.AlterField(
            model_name="membershipfeepayment",
            name="payment_date",
            field=models.DateField(
                blank=True,
                help_text="Jos maksupäivä on asetettu, jäsenmaksu näkyy maksettuna. Jätä jäsenmaksu tyhjäksi jos haluat nollata maksetun jäsenmaksun.",
                null=True,
                verbose_name="Maksupäivä",
            ),
        ),
        migrations.AlterField(
            model_name="membershipfeepayment",
            name="payment_method",
            field=models.CharField(
                choices=[("bank_transfer", "Tilisiirto"), ("checkout", "Checkout Finland")],
                default="bank_transfer",
                max_length=13,
                verbose_name="Maksutapa",
            ),
        ),
        migrations.AlterField(
            model_name="membershipfeepayment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("membership_fee_with_entrance_fee", "Liittymismaksu ja jäsenmaksu"),
                    ("membership_fee", "Jäsenmaksu"),
                ],
                default="membership_fee",
                max_length=32,
                verbose_name="Maksun tyyppi",
            ),
        ),
        migrations.AlterField(
            model_name="membershipfeepayment",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="membership_fee_payments",
                to="membership.Term",
                verbose_name="Toimikausi",
            ),
        ),
        migrations.AlterField(
            model_name="term",
            name="entrance_fee_cents",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Arvo 0 (nolla senttiä) tarkoittaa, että yhdistyksellä ei ole tällä kaudella liittymismaksua. Arvon puuttuminen tarkoittaa, että liittymismaksu ei ole tiedossa. (TODO: Se, että jäsenmaksut esitetään tässä sentteinä eikä euroina, on tiedostettu puute joka korjataan… joskus. Siihen asti kerro euromääräinen jäsenmaksu 100:lla.)",
                null=True,
                verbose_name="Liittymismaksu (snt)",
            ),
        ),
        migrations.AlterField(
            model_name="term",
            name="payment_method",
            field=models.CharField(
                choices=[("bank_transfer", "Tilisiirto"), ("checkout", "Checkout Finland")],
                default="bank_transfer",
                max_length=13,
                verbose_name="Maksutapa",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="membership",
            unique_together={("organization", "person")},
        ),
        migrations.AlterUniqueTogether(
            name="membershipfeepayment",
            unique_together={("term", "member")},
        ),
    ]
