ingress_public_hostnames:
  - dev.kompassi.eu

postgres_managed: false
postgres_hostname: siilo.tracon.fi
postgres_database: kompassidev
postgres_username: kompassidev
postgres_ssl: true

redis_managed: false
redis_hostname: redis-ha-haproxy.redis-ha.svc.cluster.local
redis_broker_database: 7
redis_cache_database: 7

kompassi_secret_managed: false
kompassi_storage_pvc: false
kompassi_storage_pvc_storageclass: longhorn-nfs
kompassi_installation_name: Kompassi (DEV)
kompassi_installation_slug: turskadev
kompassi_v2_base_url: https://v2.dev.kompassi.eu
kompassi_admins:
  - Santtu Pajukanta <santtu@pajukanta.fi>

kompassi_csp_allowed_login_redirects:
  - https://dev.kompassi.eu
  - dev.ropekonsti.fi
  - localhost:3000
  - localhost:5000
  - localhost:8000
  - ropekonsti.fi
  - wp.ropecon.fi

# kompassi_readiness_probe: !Void
# kompassi_liveness_probe: !Void
kompassi_workers: 8

smtp_server: sr1.pahaip.fi
smtp_default_from_email: suunnistajat@kompassi.eu

setup_should_run: true

ingress_letsencrypt_enabled: true
ingress_letsencrypt_cluster_issuer: letsencrypt-prod

minio_bucket_name: kompassidev
minio_endpoint_url: https://minio.con2.fi
