# Generated by Django 1.9.1 on 2016-01-23 11:36


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0008_category_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.CharField(max_length=1023)),
            ],
            options={
                "verbose_name": "invitation",
                "verbose_name_plural": "invitations",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["title"], "verbose_name": "category", "verbose_name_plural": "categories"},
        ),
        migrations.AlterModelOptions(
            name="role",
            options={"ordering": ["title"], "verbose_name": "role", "verbose_name_plural": "roles"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["order"], "verbose_name": "tag", "verbose_name_plural": "tags"},
        ),
        migrations.AlterModelOptions(
            name="view",
            options={
                "ordering": ["event", "order"],
                "verbose_name": "schedule view",
                "verbose_name_plural": "schedule views",
            },
        ),
        migrations.AlterField(
            model_name="programme",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="programme.Category", verbose_name="category"
            ),
        ),
        migrations.AlterField(
            model_name="programme",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="This description is published in the web schedule and the programme booklet. The purpose of this description is to give the participant sufficient information to decide whether to take part or not and to market your programme to the participants. We reserve the right to edit the description.",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="programme",
            name="title",
            field=models.CharField(
                help_text="Make up a concise title for your programme. We reserve the right to edit the title.",
                max_length=1023,
                verbose_name="Title",
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="programme",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="programme.Programme"),
        ),
        migrations.AddField(
            model_name="invitation",
            name="role",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="programme.Role"),
        ),
    ]
