# Generated by Django 1.9.1 on 2016-01-24 21:28


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0013_auto_20160124_2151"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvitationAdminProxy",
            fields=[],
            options={
                "verbose_name": "invitation",
                "proxy": True,
                "verbose_name_plural": "invitations",
            },
            bases=("programme.invitation",),
        ),
        migrations.CreateModel(
            name="ProgrammeManagementProxy",
            fields=[],
            options={
                "proxy": True,
            },
            bases=("programme.programme",),
        ),
    ]
