# Generated by Django 1.9.1 on 2016-02-22 19:51


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0028_auto_20160207_2330"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
