# Generated by Django 1.9.5 on 2016-08-11 20:19


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0045_auto_20160715_0127"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="override_public_title",
            field=models.CharField(
                blank=True,
                help_text="This gets displayed publicly instead of title, if set. Affects eg. badges.",
                max_length=63,
                verbose_name="Override public job title",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="title",
            field=models.CharField(max_length=1023, verbose_name="Job title"),
        ),
    ]
