# Generated by Django 1.10.8 on 2017-11-25 10:36
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0062_populate_viewroom"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="view",
            name="rooms",
        ),
    ]
