# Generated by Django 1.10.8 on 2018-04-29 16:43
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0071_auto_20180417_2245"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="language_skills",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Please describe your language skills relevant to the language of this programme.",
                verbose_name="Language skills",
            ),
        ),
    ]
