# Generated by Django 2.1.5 on 2019-02-17 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0078_auto_20190217_1344"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alternativeprogrammeform",
            name="active_from",
        ),
        migrations.RemoveField(
            model_name="alternativeprogrammeform",
            name="active_until",
        ),
    ]
