# Generated by Django 4.1.7 on 2023-03-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0114_programme_ropecon2023_furniture_needs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="ropecon2023_workshop_fee",
            field=models.CharField(
                blank=True,
                default="0€",
                help_text="If participation in the workshop requires a material fee, write the amount here as accurately as possible (if already known at the time of application).<br/>If not known (or there is no fee of any type), write 0€. Remember to update the exact amount to Kompassi before the release of the programme guide!",
                max_length=1023,
                verbose_name="Workshop fee",
            ),
        ),
    ]
