# Generated by Django 4.1.7 on 2023-03-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracon2023", "0002_accessibilitywarning_timeslot"),
        ("programme", "0116_merge_20230314_2218"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="tracon2023_accessibility_warnings",
            field=models.ManyToManyField(
                blank=True, to="tracon2023.accessibilitywarning", verbose_name="accessibility warnings"
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="tracon2023_content_warnings",
            field=models.TextField(
                blank=True,
                default="",
                help_text="We will print content warnings in the programme schedule in order to give our visitors the requisite information to make educated choices about programme. If your programme contains bright lights, loud noises, smoke or similar effects, please choose them above. Please include any other content warnings in the text field.",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="tracon2023_preferred_time_slots",
            field=models.ManyToManyField(
                help_text="When would you like to hold your programme? The time slots are intentionally vague. If you have more specific needs regarding the time, please explain them in the last open field.",
                to="tracon2023.timeslot",
                verbose_name="preferred time slots",
            ),
        ),
        migrations.AlterField(
            model_name="programme",
            name="ropecon2023_workshop_fee",
            field=models.CharField(
                blank=True,
                default="0€",
                help_text="If participation in the workshop requires a material fee, write the amount here as accurately as possible (if already known at the time of application). If not known (or there is no fee of any type), write 0€. Remember to update the exact amount to Kompassi before the release of the programme guide!",
                max_length=1023,
                verbose_name="Workshop fee",
            ),
        ),
    ]
