# Generated by Django 4.1.7 on 2023-04-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracon2023", "0002_accessibilitywarning_timeslot"),
        ("programme", "0117_programme_tracon2023_accessibility_warnings_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programme",
            name="photography",
            field=models.CharField(
                blank=True,
                choices=[
                    ("please", "Please photograph my programme"),
                    ("okay", "It's OK to photograph my programme"),
                    ("nope", "Please do not photograph my programme"),
                ],
                help_text="Our official photographers will try to cover all programmes whose hosts request their programmes to be photographed.",
                max_length=6,
                verbose_name="Photography of your programme",
            ),
        ),
        migrations.AlterField(
            model_name="programme",
            name="tracon2023_accessibility_warnings",
            field=models.ManyToManyField(
                blank=True, to="tracon2023.accessibilitywarning", verbose_name="Accessibility warnings"
            ),
        ),
        migrations.AlterField(
            model_name="programme",
            name="tracon2023_content_warnings",
            field=models.TextField(
                blank=True,
                default="",
                help_text="We will print content warnings in the programme schedule in order to give our visitors the requisite information to make educated choices about programme. If your programme contains bright lights, loud noises, smoke or similar effects, please choose them above. Please include any other content warnings in the text field.",
                verbose_name="Content warnings",
            ),
        ),
    ]
