# Generated by Django 4.2.7 on 2023-11-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0120_remove_programme_solmukohta2024_computer_usage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="solmukohta2024_other_emails",
            field=models.CharField(
                blank=True,
                default="",
                help_text="We will make a mailing list to reach all our programme hosts for the purpose of keeping you informed. You need not add your own email address here – it will be shared with us when you submit this form.",
                max_length=1023,
                verbose_name="Email addresses of other programme hosts",
            ),
        ),
        migrations.AlterField(
            model_name="programme",
            name="length_from_host",
            field=models.CharField(
                blank=True,
                help_text="Huomaathan, että emme voi taata juuri toivomasi pituista ohjelmapaikkaa. Ohjelmavastaava vahvistaa ohjelmasi pituuden.",
                max_length=127,
                null=True,
                verbose_name="Length of the programme",
            ),
        ),
    ]
