# Generated by Django 4.2.7 on 2023-11-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0121_programme_solmukohta2024_other_emails_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programme",
            name="hosts_from_host",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Please provide the names as they should be presented in the programme guide. Please indicate their role in the programme, if there are multiple roles (moderator, panelist, etc.). Please also include yourself in the list.",
                max_length=1023,
                verbose_name="Programme host names",
            ),
        ),
    ]
