# Generated by Django 5.0.2 on 2024-02-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0123_rename_programme_category_state_programme_p_categor_69bbc0_idx"),
        ("ropecon2024", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="ropecon2024_blocked_time_slots",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select the times when you are <b>NOT able</b> to run your larp. In other words, leave the times that you would be able to run your larp unselected!<br/>If you have a more specific request in mind regarding your schedule (for example, you would like to run your larp late at night), please let us know in the Comments section below.<br/>In this section, we would like to know more about how work or volunteer shifts, public transport schedules and other factors might be impacting your schedule. For example, if you need to leave the venue by 11pm to be able to catch the last bus to your accommodation.",
                related_name="+",
                to="ropecon2024.timeslot",
                verbose_name="When are you NOT able to host your programme?",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="ropecon2024_language",
            field=models.CharField(
                choices=[
                    ("finnish", "Finnish"),
                    ("english", "English"),
                    ("language_free", "Language-free"),
                    ("fin_and_eng", "Finnish and English"),
                    ("other", "Other"),
                ],
                default="finnish",
                help_text="Finnish - choose this, if only Finnish is spoken in your programme.<br><br>English - choose this, if only English is spoken in your programme.<br><br>Language-free - choose this, if no Finnish or English is necessary to participate in the programme (e.g. a workshop with picture instructions or a dance where one can follow what others are doing).<br><br>Finnish and English - choose this, if your programme item will use both Finnish and English (e.g. if you will switch languages based on participants). If chosen, please provide the title and description of your programme in both languages.<br><br>Other - choose this, if your programme is in a language other than Finnish or English. If chosen, please provide the title and description of your programme in the chosen language.",
                max_length=13,
                null=True,
                verbose_name="Choose the language used in your programme",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="ropecon2024_language_other",
            field=models.CharField(
                blank=True,
                default="",
                help_text='If you chose "other", enter the language or languages you will be using in your programme here',
                max_length=1023,
                verbose_name="Other",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="ropecon2024_language_prog",
            field=models.CharField(
                choices=[
                    ("finnish", "Finnish"),
                    ("english", "English"),
                    ("language_free", "Language-free"),
                    ("fin_or_eng", "Finnish or English"),
                    ("fin_and_eng", "Finnish and English"),
                    ("other", "Other"),
                ],
                default="finnish",
                help_text="Finnish - choose this, if only Finnish is spoken in your programme.<br><br>English - choose this, if only English is spoken in your programme.<br><br>Language-free - choose this, if no Finnish or English is necessary to participate in the programme (e.g. a workshop with picture instructions or a dance where one can follow what others are doing).<br><br>Finnish or English - choose this, if you are okay with either of the two languages. The programme team will contact you regarding the final choice of language.<br><br>Finnish and English - choose this, if your programme item will use both Finnish and English (e.g. if you will switch languages based on participants).<br><br>Other - choose this, if your programme is in a language other than Finnish or English. If chosen, please provide the title and description of your programme in the chosen language.",
                max_length=13,
                null=True,
                verbose_name="Choose the language used in your programme",
            ),
        ),
    ]
