# Generated by Django 5.0.4 on 2024-04-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0125_remove_programme_ropecon2024_language_prog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="programmeeventmeta",
            name="override_schedule_link",
            field=models.URLField(
                blank=True,
                help_text="If you have a separate programme system, you can link to it here. This link will replace the link to the internal programme schedule.",
                verbose_name="Override schedule link",
            ),
        ),
        migrations.AlterField(
            model_name="view",
            name="public",
            field=models.BooleanField(
                default=True,
                help_text="Even if the schedule is already published, you can hide this view by unchecking this box.",
                verbose_name="Visible",
            ),
        ),
    ]
