# Generated by Django 5.0.6 on 2024-06-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0127_programme_programme_p_categor_5b8eeb_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="v2_dimensions",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="dimension slug -> list of dimension value slugs. When program is imported to v2, dimension values indicated here are added to programs of this category.",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="v2_dimensions",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="dimension slug -> list of dimension value slugs. When program is imported to v2, dimension values indicated here are added to programs of this category.",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="v2_dimensions",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="dimension slug -> list of dimension value slugs. When program is imported to v2, dimension values indicated here are added to programs of this category.",
            ),
        ),
    ]
