# Generated by Django 5.0.6 on 2024-07-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0129_alternativeprogrammeform_v2_dimensions"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="max_runs",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=1,
                help_text="How many times are you prepared to run this game?",
                null=True,
                verbose_name="Maximum number of runs",
            ),
        ),
        migrations.AlterField(
            model_name="programme",
            name="approximate_length",
            field=models.IntegerField(
                blank=True,
                default=240,
                help_text="Please give your best guess on how long you expect one run of your game to take.",
                null=True,
                verbose_name="approximate length (minutes)",
            ),
        ),
    ]
