# Generated by Django 5.0.7 on 2024-07-29 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0130_programme_max_runs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="programmerole",
            name="override_perks",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="If set, overrides the perks set in the role.",
                verbose_name="Override perks",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="perks",
            field=models.JSONField(blank=True, default=dict, help_text="Perks for this role", verbose_name="Perks"),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="sire",
            field=models.ForeignKey(
                blank=True,
                help_text="The host that spawned this invitation. Sired invitations consume the extra invite quota of the sire.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sired_invitations",
                to="programme.programmerole",
                verbose_name="Sire",
            ),
        ),
    ]
