# Generated by Django 1.10.8 on 2018-02-12 21:01
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0022_orderproduct_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="electronic_tickets_per_product",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="product",
            name="override_electronic_ticket_title",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
