# Generated by Django 2.2.28 on 2022-04-18 12:53

from django.contrib.postgres.fields import HStoreField
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0029_auto_20220418_1531"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketseventmeta",
            name="terms_and_conditions_url",
            field=HStoreField(blank=True),
        ),
    ]
