# Generated by Django 4.2.5 on 2023-10-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0036_alter_ticketseventmeta_max_count_per_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ("ordering", "id"), "verbose_name": "product", "verbose_name_plural": "products"},
        ),
        migrations.AddField(
            model_name="product",
            name="code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="If set, the product will only be available with this code supplied as a query string parameter.",
                max_length=63,
            ),
        ),
        migrations.AddField(
            model_name="ticketseventmeta",
            name="tickets_view_version",
            field=models.CharField(
                choices=[
                    ("v1", "Version 1 (Django frontend, multiple phases)"),
                    ("v1.5", "Version 1.5 (Django frontend, single phase)"),
                    ("v2", "Version 2 (Next.js frontend)"),
                ],
                default="v1",
                max_length=4,
                verbose_name="Tickets view version",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                help_text="Check the e-mail address carefully. The order confirmation and any electronic tickets will be sent to this e-mail address.",
                max_length=254,
                verbose_name="E-mail address",
            ),
        ),
    ]
