# Generated by Django 5.0.9 on 2024-09-27 14:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event_log", "0015_remove_entry_accommodation_information"),
        ("tickets", "0042_remove_ticketseventmeta_receipt_footer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="requires_accommodation_information",
        ),
        migrations.RemoveField(
            model_name="ticketseventmeta",
            name="accommodation_access_group",
        ),
        migrations.RemoveField(
            model_name="ticketseventmeta",
            name="ticket_spam_email",
        ),
        migrations.RemoveField(
            model_name="ticketseventmeta",
            name="tickets_view_version",
        ),
        migrations.DeleteModel(
            name="AccommodationInformation",
        ),
    ]
