# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-26 13:58
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import labour.models.signup_extras


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labour', '0033_auto_20170802_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupExtra',
            fields=[
                ('signup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='aicon2018_signup_extra', serialize=False, to='labour.Signup')),
                ('is_active', models.BooleanField(default=True)),
                ('shift_type', models.CharField(choices=[('yksipitka', 'Yksi pitkä vuoro'), ('montalyhytta', 'Monta lyhyempää vuoroa'), ('kaikkikay', 'Kumpi tahansa käy')], help_text='Haluatko tehdä yhden pitkän työvuoron vaiko monta lyhyempää vuoroa?', max_length=15, verbose_name='Toivottu työvuoron pituus')),
                ('total_work', models.CharField(choices=[('8h', 'Minimi - 8 tuntia'), ('12h', '10–12 tuntia'), ('yli12h', 'Työn Sankari! Yli 12 tuntia!')], help_text='Kuinka paljon haluat tehdä töitä yhteensä tapahtuman aikana? Useimmissa tehtävistä minimi on kahdeksan tuntia, mutta joissain tehtävissä se voi olla myös vähemmän (esim. majoitusvalvonta 6 h).', max_length=15, verbose_name='Toivottu kokonaistyömäärä')),
                ('want_certificate', models.BooleanField(default=False, verbose_name='Haluan todistuksen työskentelystäni Aiconissa')),
                ('certificate_delivery_address', models.TextField(blank=True, help_text='Jos haluat työtodistuksen, täytä tähän kenttään postiosoite (katuosoite, postinumero ja postitoimipaikka) johon haluat todistuksen toimitettavan.', verbose_name='Työtodistuksen toimitusosoite')),
                ('special_diet_other', models.TextField(blank=True, help_text='Jos noudatat erikoisruokavaliota, jota ei ole yllä olevassa listassa, ilmoita se tässä. Tapahtuman järjestäjä pyrkii ottamaan erikoisruokavaliot huomioon, mutta kaikkia erikoisruokavalioita ei välttämättä pystytä järjestämään.', verbose_name='Muu erikoisruokavalio')),
                ('need_lodging', models.BooleanField(default=False, verbose_name='Tarvitsen lattiamajoitusta lauantain ja sunnuntain väliseksi yöksi')),
                ('prior_experience', models.TextField(blank=True, help_text='Kerro tässä kentässä, jos sinulla on aiempaa kokemusta vastaavista tehtävistä tai muuta sellaista työkokemusta, josta arvioit olevan hyötyä hakemassasi tehtävässä.', verbose_name='Työkokemus')),
                ('free_text', models.TextField(blank=True, help_text='Jos haluat sanoa hakemuksesi käsittelijöille jotain sellaista, jolle ei ole omaa kenttää yllä, käytä tätä kenttää.', verbose_name='Vapaa alue')),
                ('email_alias', models.CharField(blank=True, default='', help_text='Vastaavat saavat käyttöönsä sähköpostialiakset, jotka ovat muotoa tehtävä@aicon.fi. Mikäli tiedät jo Aiconin vastaavatehtäväsi, syötä se tähän mahdollisimman yksinkertaisessa muodossa (esim. pj, työvoima, ohjelma ym). Osoitteessa isot kirjaimet muutetaan automaattisesti pieniksi, ä a:ksi ja niin edelleen. Näet lopullisen osoitteesi <a href="/profile/aliases" target="_blank">profiilin sähköpostialiassivulta</a> sitten, kun vastaavailmoittautumisesi on hyväksytty. Mikäli osoitteisiin tarvitaan tämän jälkeen muutoksia, Japsu auttaa.', max_length=32, validators=[django.core.validators.RegexValidator(message='Tekninen nimi saa sisältää vain pieniä kirjaimia, numeroita sekä väliviivoja.', regex='[a-z0-9-]+')], verbose_name='Sähköpostialias')),
            ],
            options={
                'abstract': False,
            },
            bases=(labour.models.signup_extras.SignupExtraMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SpecialDiet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='signupextra',
            name='special_diet',
            field=models.ManyToManyField(blank=True, to='aicon2018.SpecialDiet', verbose_name='Erikoisruokavalio'),
        ),
    ]
