# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-19 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aicon2018', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupextra',
            name='total_work',
            field=models.CharField(choices=[('5h', 'Minimi - 5 tuntia'), ('yli5h', 'Enemmän kuin 5 tuntia')], help_text='Kuinka paljon haluat tehdä töitä yhteensä tapahtuman aikana? Useimmissa tehtävistä minimi on kahdeksan tuntia, mutta joissain tehtävissä se voi olla myös vähemmän (esim. majoitusvalvonta 6 h).', max_length=15, verbose_name='Toivottu kokonaistyömäärä'),
        ),
    ]
