# Generated by Django 1.10.8 on 2018-07-16 13:13
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0002_listing_external_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalevent",
            name="public",
            field=models.BooleanField(default=True),
        ),
    ]
