# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-17 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import labour.models.signup_extras


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0023_auto_20160704_2155'),
        ('enrollment', '0003_auto_20170417_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('special_diet_other', models.TextField(blank=True, help_text='Jos noudatat erikoisruokavaliota, jota ei ole yllä olevassa listassa, ilmoita se tässä. Tapahtuman järjestäjä pyrkii ottamaan erikoisruokavaliot huomioon, mutta kaikkia erikoisruokavalioita ei välttämättä pystytä järjestämään.', verbose_name='Muu erikoisruokavalio')),
                ('shift_wishes', models.TextField(blank=True, help_text='Miten olet käytettävissä työvuoroihin tapahtuman aikana? Jos tiedät, ettet pääse paikalle johonkin tiettyyn aikaan tai haluat esimerkiksi osallistua johonkin tiettyyn ohjelmanumeroon, mainitse siitä tässä.', verbose_name='Työvuorotoiveet')),
                ('prior_experience', models.TextField(blank=True, help_text='Kerro aikaisemmasta työkokemuksestasi tapahtuman työvoimana tai muusta kokemuksesta, josta koet olevan hyötyä haetussa/haetuissa työtehtävissä.', verbose_name='Työkokemus')),
                ('free_text', models.TextField(blank=True, help_text='Tässä kentässä voit kertoa jotain minkä koet tarpeelliseksi, jota ei ole vielä mainittu.', verbose_name='Lisätietoja')),
                ('is_attending_member', models.BooleanField(verbose_name='Olen Worldcon 75:n <em>attending member</em>')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worldcon75_signup_extras', to='core.Event')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worldcon75_signup_extra', to='core.Person')),
                ('special_diet', models.ManyToManyField(blank=True, related_name='worldcon75_signupextra', to='enrollment.SpecialDiet', verbose_name='Erikoisruokavalio')),
            ],
            options={
                'abstract': False,
            },
            bases=(labour.models.signup_extras.SignupExtraMixin, models.Model),
        ),
    ]
