# Generated by Django 1.9.9 on 2016-11-02 14:58


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intra", "0002_auto_20161020_2143"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="The primary contact e-mail of the team.",
                max_length=255,
                verbose_name="E-mail address",
            ),
        ),
    ]
