# Generated by Django 5.0.4 on 2024-06-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intra", "0008_alter_intraeventmeta_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="intraeventmeta",
            name="is_organizer_list_public",
            field=models.BooleanField(
                default=False,
                help_text="If set, the organizer list (name and job title) can be accessed via the GraphQL API.",
            ),
        ),
    ]
