# Generated by Django 4.2.7 on 2023-11-26 09:18

import localized_fields.fields.char_field
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("program_v2", "0007_programv2eventmeta_skip_offer_form_selection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dimension",
            name="title",
            field=localized_fields.fields.char_field.LocalizedCharField(max_length=1023, required=["en"]),
        ),
        migrations.AlterField(
            model_name="dimensionvalue",
            name="title",
            field=localized_fields.fields.char_field.LocalizedCharField(max_length=1023, required=["en"]),
        ),
    ]
