# Generated by Django 5.0.2 on 2024-04-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_v2", "0009_alter_dimension_title_alter_dimensionvalue_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="programv2eventmeta",
            name="importer_name",
            field=models.CharField(
                blank=True,
                choices=[("default", "Default"), ("solmukohta2024", "Solmukohta 2024")],
                default="",
                help_text="Select the importer to use when importing program data from v1. WARNING: If set, destructive changes will be made to the v2 program data. Do not set for events that are using Program v2 natively.",
                max_length=14,
                verbose_name="V1 program importer",
            ),
        ),
    ]
