# Generated by Django 5.0.4 on 2024-04-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_v2", "0011_program_favorited_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleitem",
            name="cached_end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
