# Generated by Django 5.0.4 on 2024-04-12 17:04

from django.db import migrations, models


def populate_cached_end_time(apps, schema_editor):
    ScheduleItem = apps.get_model("program_v2", "ScheduleItem")
    for schedule_item in ScheduleItem.objects.all():
        schedule_item.cached_end_time = schedule_item.start_time + schedule_item.length
        schedule_item.save(update_fields=["cached_end_time"])


class Migration(migrations.Migration):
    dependencies = [
        ("program_v2", "0012_scheduleitem_cached_end_time"),
    ]

    operations = [
        migrations.RunPython(
            populate_cached_end_time,
        ),
        migrations.AlterField(
            model_name="scheduleitem",
            name="cached_end_time",
            field=models.DateTimeField(),
        ),
    ]
