# Generated by Django 5.0.4 on 2024-04-18 06:25

from django.db import migrations, models, transaction


def populate_cached_times(apps, schema_editor):
    Program = apps.get_model("program_v2", "Program")

    with transaction.atomic():
        bulk_update = []
        for program in (
            Program.objects.all()
            .select_for_update(of=("self",))
            .only(
                "id",
                "cached_earliest_start_time",
                "cached_latest_end_time",
            )
        ):
            earliest_start_time = program.schedule_items.order_by("start_time").first()
            latest_end_time = program.schedule_items.order_by("cached_end_time").last()

            program.cached_earliest_start_time = earliest_start_time.start_time if earliest_start_time else None
            program.cached_latest_end_time = latest_end_time.cached_end_time if latest_end_time else None

            bulk_update.append(program)

        Program.objects.bulk_update(bulk_update, ["cached_earliest_start_time", "cached_latest_end_time"])


class Migration(migrations.Migration):
    dependencies = [
        ("program_v2", "0013_alter_scheduleitem_cached_end_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="cached_earliest_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="cached_latest_end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            populate_cached_times,
        ),
    ]
