# Generated by Django 5.0.6 on 2024-06-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_v2", "0016_alter_dimension_event"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dimension",
            options={"ordering": ("event", "order")},
        ),
        migrations.AlterModelOptions(
            name="dimensionvalue",
            options={"ordering": ("dimension__order", "order")},
        ),
        migrations.AlterModelOptions(
            name="programdimensionvalue",
            options={"ordering": ("dimension__order", "value__order")},
        ),
        migrations.AddField(
            model_name="dimension",
            name="order",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dimension",
            name="value_ordering",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("slug", "Alphabetical (slug)"),
                    ("title", "Alphabetical (localized title)"),
                ],
                default="title",
                help_text="In which order are the values of this dimension returned in the GraphQL API. NOTE: When using Alphabetical (localized title), the language needs to be provided to `values` and `values.title` fields separately.",
            ),
        ),
        migrations.AddField(
            model_name="dimensionvalue",
            name="order",
            field=models.SmallIntegerField(
                default=0, help_text="Only applies if `dimension.value_ordering` is `manual`."
            ),
        ),
    ]
