# Generated by Django 5.0.6 on 2024-06-16 09:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("program_v2", "0017_alter_dimension_options_alter_dimensionvalue_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="program",
            old_name="other_fields",
            new_name="annotations",
        ),
    ]
