# Generated by Django 5.0.8 on 2024-09-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_v2", "0020_alter_scheduleitem_options_scheduleitem_cached_event_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="programv2eventmeta",
            name="is_accepting_feedback",
            field=models.BooleanField(
                default=True,
                help_text="If checked, feedback can be left for programs.",
                verbose_name="Is accepting feedback",
            ),
        ),
    ]
