# Generated by Django 5.0.9 on 2024-10-26 14:39

from django.conf import settings
from django.db import migrations, models


def populate_favorited_by(apps, schema_editor):
    Program = apps.get_model("program_v2", "Program")

    for program in Program.objects.filter(favorited_by__isnull=False):
        for user in program.favorited_by.all():
            for schedule_item in program.schedule_items.all():
                if not schedule_item.favorited_by.filter(pk=user.pk).exists():
                    schedule_item.favorited_by.add(user)


class Migration(migrations.Migration):
    dependencies = [
        ("program_v2", "0022_remove_programv2eventmeta_primary_dimension"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleitem",
            name="favorited_by",
            field=models.ManyToManyField(
                blank=True, related_name="favorite_schedule_items", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RunPython(populate_favorited_by, elidable=True),
    ]
