# Generated by Django 5.0.9 on 2024-11-30 16:10

import django.db.models.deletion
from django.db import migrations, models


def old_value_ordering_to_new(old_value_ordering: str) -> int:
    """
    See dimensions/models/value_ordering.py:ValueOrdering
    """
    match old_value_ordering:
        case "manual":
            return 1
        case "slug":
            return 2
        case "title":
            return 3
        case _:
            raise ValueError(f"Invalid ValueOrdering slug: {old_value_ordering}")


def populate_new_location_dimension(apps, schema_editor):
    Dimension = apps.get_model("dimensions", "Dimension")
    ProgramV2EventMeta = apps.get_model("program_v2", "ProgramV2EventMeta")

    for meta in ProgramV2EventMeta.objects.filter(location_dimension__isnull=False):
        location_dimension = meta.location_dimension
        meta.new_location_dimension = Dimension.objects.get(
            universe__scope__slug=location_dimension.event.slug,
            universe__app="program_v2",
            universe__slug="default",
            slug=location_dimension.slug,
        )
        meta.save(update_fields=["new_location_dimension"])


class Migration(migrations.Migration):
    dependencies = [
        ("dimensions", "0002_populate"),
        ("program_v2", "0027_alter_programdimensionvalue_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dimensionvalue",
            unique_together=None,
        ),
        migrations.AlterModelOptions(
            name="programdimensionvalue",
            options={"ordering": ("new_value__dimension__order", "new_value__order")},
        ),
        migrations.AddField(
            model_name="programv2eventmeta",
            name="new_location_dimension",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, this dimension will be used as the location dimension for the event. This is used at least by the calendar export for the iCalendar location field.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="location_dimension_for_event_meta",
                to="dimensions.dimension",
            ),
        ),
        migrations.RunPython(
            populate_new_location_dimension,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
        migrations.RemoveField(
            model_name="dimensionvalue",
            name="dimension",
        ),
        migrations.RemoveField(
            model_name="programdimensionvalue",
            name="dimension",
        ),
        migrations.RemoveField(
            model_name="programv2eventmeta",
            name="location_dimension",
        ),
        migrations.RemoveField(
            model_name="programdimensionvalue",
            name="value",
        ),
        migrations.DeleteModel(
            name="DimensionValue",
        ),
        migrations.DeleteModel(
            name="Dimension",
        ),
    ]
