# Generated by Django 5.0.9 on 2024-11-30 16:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dimensions", "0002_populate"),
        ("program_v2", "0028_remove_dimensionvalue_dimension_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="programdimensionvalue",
            options={"ordering": ("value__dimension__order", "value__order")},
        ),
        migrations.RenameField(
            model_name="programdimensionvalue",
            old_name="new_value",
            new_name="value",
        ),
        migrations.RenameField(
            model_name="programv2eventmeta",
            old_name="new_location_dimension",
            new_name="location_dimension",
        ),
        migrations.AlterUniqueTogether(
            name="programdimensionvalue",
            unique_together={("program", "value")},
        ),
    ]
