# Generated by Django 5.0.10 on 2024-12-15 14:53

import django.db.models.deletion
import program_v2.models.dimension_values
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimensions', '0002_populate'),
        ('program_v2', '0030_delete_offerform'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleItemDimensionValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='program_v2.scheduleitem')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dimensions.dimensionvalue')),
            ],
            options={
                'ordering': ('value__dimension__order', 'value__order'),
                'unique_together': {('schedule_item', 'value')},
            },
            bases=(program_v2.models.dimension_values.DimensionValueMixin, models.Model),
        ),
    ]
