# Generated by Django 5.1.5 on 2025-02-23 12:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("program_v2", "0031_programform_attributes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="programv2eventmeta",
            name="skip_offer_form_selection",
        ),
    ]
