# Generated by Django 5.1.5 on 2025-04-21 11:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("program_v2", "0034_programv2eventmeta_contact_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="programv2eventmeta",
            name="importer_name",
        ),
    ]
