# Generated by Django 5.1.5 on 2025-05-11 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("involvement", "0001_initial"),
        ("program_v2", "0038_alter_programv2eventmeta_contact_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="programv2eventmeta",
            name="default_registry",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="involvement.registry"
            ),
        ),
    ]
