# Generated by Django 1.9.9 on 2016-10-01 11:00


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("yukicon2017", "0002_auto_20160921_2248"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="signupextra",
            name="shirt_size",
        ),
    ]
