apiVersion: v1
kind: Secret
metadata:
  name: kompassi
  labels:
    stack: kompassi
type: Opaque
data:
  desuprofileOauth2ClientId: ''
  desuprofileOauth2ClientSecret: ''
  sshPrivateKey: 'Ym9ndXM='
  sshKnownHosts: 'Ym9ndXM='
  secretKey: !Base64,Var kompassi_secret_key
  minioAccessKeyId: !Base64,Var minio_access_key_id
  minioSecretAccessKey: !Base64,Var minio_secret_access_key
  oidcRsaPrivateKey: ''
  ticketsApikey: !Base64 secret
