# Generated by Django 5.0.8 on 2024-09-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracon2024", "0004_signupextraafterpartyproxy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signupextra",
            name="afterparty_help",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Kaatajaiset järjestyvät oman työryhmän voimin, mutta joskus lisäkädet ovat tarpeen. Oletko valmis auttamaan kaadon järjestelyissä, esim. logistiikassa tai juomien kaatamisessa? Jos kyllä, kirjoita tähän. Erityisesti pulaa on usein paluukuskeista, niin omalla autolla kuin ilman omaa autoa raittiina liikkeellä olevista. Vastanneisiin otetaan yhteyttä Slackitse jos apuanne tarvitaan.",
                verbose_name="Työskentely kaatajaisissa",
            ),
        ),
        migrations.AlterField(
            model_name="signupextra",
            name="afterparty_policy",
            field=models.BooleanField(
                default=False,
                verbose_name="Olen tutustunut Traconin häirinnän vastaiseen linjaukseen, ymmärrän sen olevan voimassa myös kaadossa ja sitoudun noudattamaan sitä.",
            ),
        ),
    ]
