# Generated by Django 5.1.5 on 2025-02-28 18:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracon2024", "0006_alter_signupextra_email_alias"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SignupExtraAfterpartyProxy",
        ),
    ]
