# Generated by Django 1.9 on 2015-12-20 13:52


import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labour_common_qualifications", "0002_auto_20150521_1557"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jvkortti",
            name="card_number",
            field=models.CharField(
                help_text="Muoto: 0000/J0000/00 tai XX/0000/00",
                max_length=13,
                validators=[
                    django.core.validators.RegexValidator(message="Tarkista JV-kortin numero", regex=".+/.+/.+")
                ],
                verbose_name="JV-kortin numero",
            ),
        ),
    ]
