# Generated by Django 4.1.7 on 2023-04-15 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("programme", "0118_alter_programme_photography_and_more"),
        ("mailings", "0009_recipientgroup_programme_category_and_more"),
    ]

    operations = [  # noqa: RUF012
        migrations.AddField(
            model_name="recipientgroup",
            name="programme_form",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="programme.alternativeprogrammeform",
            ),
        ),
    ]
