# Generated by Django 4.2 on 2023-05-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailings", "0011_alter_recipientgroup_verbose_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipientgroup",
            name="override_reply_to",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Due to spam protection, the sender field will always display a technical address in the kompassi.eu domain. That address will redirect incoming mail to the default contact address. You can direct replies to another address by setting a reply-to address here. Format: foo@example.com or Foo Bar &lt;foo@example.com&gt;.",
                max_length=255,
                verbose_name="Reply-to address",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="channel",
            field=models.CharField(
                choices=[("email", "Sähköposti")], default="email", max_length=5, verbose_name="Kanava"
            ),
        ),
    ]
