# Generated by Django 1.9.4 on 2016-04-06 18:44


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labour", "0024_emptysignupextra"),
    ]

    operations = [
        migrations.AddField(
            model_name="emptysignupextra",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="obsoleteemptysignupextrav1",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
