# Generated by Django 1.9.9 on 2016-09-01 22:19


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_auto_20160704_2155"),
        ("labour", "0030_auto_20160716_1419"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyRecord",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="survey_records", to="core.Person"
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="survey_records", to="labour.Survey"
                    ),
                ),
            ],
        ),
    ]
