# Generated by Django 5.0.7 on 2024-07-29 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_rename_emailverificationtoken_person_state_core_emailv_person__722147_idx_and_more"),
        ("labour", "0038_laboureventmeta_work_certificate_pdf_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personnelclass",
            name="perks_markdown",
        ),
        migrations.AddField(
            model_name="personnelclass",
            name="override_formatted_perks",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="personnelclass",
            name="perks",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="signup",
            name="override_working_hours",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Huomioidaan työvoimaetujen laskennassa, jos tapahtuma antaa työvoimaedut työntuntien perusteella. Jos henkilö tekee tapahtuman eteen töitä, joita ei ole huomioitu Kompassiin kirjatuissa työvuoroissa, voit asettaa tähän hänen kokonaistuntimääränsä, ja työvoimaedut lasketaan tämän mukaan.",
                null=True,
                verbose_name="Aseta työtunnit käsin",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="labour.jobcategory",
                verbose_name="job category",
            ),
        ),
        migrations.AlterField(
            model_name="personqualification",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qualifications",
                to="core.person",
                verbose_name="henkilö",
            ),
        ),
        migrations.AlterField(
            model_name="personqualification",
            name="qualification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="person_qualifications",
                to="labour.qualification",
                verbose_name="pätevyys",
            ),
        ),
        migrations.AlterField(
            model_name="signup",
            name="job_categories_accepted",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tehtäväalueet, joilla hyväksytty vapaaehtoistyöntekijä tulee työskentelemään. Tämän perusteella henkilölle mm. lähetetään oman tehtäväalueensa työvoimaohjeet. Harmaalla merkityt tehtäväalueet ovat niitä, joihin hakija ei ole itse hakenut.",
                related_name="accepted_signups",
                to="labour.jobcategory",
                verbose_name="Hyväksytyt tehtäväalueet",
            ),
        ),
    ]
