# Generated by Django 5.2.4 on 2025-07-31 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_emailverificationtoken_language_and_more"),
        ("labour", "0042_signup_override_formatted_perks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personnelclass",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="personnel_classes", to="core.event"
            ),
        ),
    ]
