# Generated by Django 6.0.7 on 2026-07-07 22:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("labour", "0043_alter_personnelclass_event"),
    ]

    operations = [
        migrations.DeleteModel(
            name="JobCategoryManagementProxy",
        ),
    ]
