# Generated by Django 6.1 on 2026-09-02 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("core", "0044_organization_business_id"),
        ("labour", "0044_delete_jobcategorymanagementproxy"),
    ]

    operations = [  # noqa: RUF012
        migrations.AlterField(
            model_name="signup",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="signups", to="core.event"
            ),
        ),
        migrations.AlterField(
            model_name="signup",
            name="job_categories",
            field=models.ManyToManyField(
                help_text="Valitse kaikki ne tehtävät, joissa olisit valmis työskentelemään tapahtumassa. Huomaathan, että sinulle tarjottavia tehtäviä voi rajoittaa se, mitä pätevyyksiä olet ilmoittanut sinulla olevan. Esimerkiksi järjestyksenvalvojaksi voivat ilmoittautua ainoastaan JV-kortilliset.",
                related_name="signups",
                to="labour.jobcategory",
                verbose_name="Haettavat tehtävät",
            ),
        ),
        migrations.AlterField(
            model_name="signup",
            name="personnel_classes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Mihin henkilöstöryhmiin tämä henkilö kuuluu? Henkilö saa valituista ryhmistä ylimmän mukaisen badgen.",
                related_name="signups",
                to="labour.personnelclass",
                verbose_name="Henkilöstöluokat",
            ),
        ),
    ]
