# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-01 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracon11', '0007_migrate_to_signupextrav2'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupextrav2',
            name='afterparty_participation',
            field=models.BooleanField(default=False, help_text='Ruksaa t\xe4m\xe4 ruutu, mik\xe4li haluat osallistua kaatajaisiin. Mik\xe4li mielesi muuttuu tai sinulle tulee este, peru ilmoittautumisesi poistamalla rasti t\xe4st\xe4 ruudusta.', verbose_name='Osallistun kaatajaisiin'),
        ),
        migrations.AddField(
            model_name='signupextrav2',
            name='outward_coach_departure_time',
            field=models.CharField(blank=True, choices=[('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('nobus', 'En tarvitse menokyyti\xe4 (tulen omalla kyydill\xe4)')], max_length=5, verbose_name='Menobussin l\xe4ht\xf6aika'),
        ),
        migrations.AddField(
            model_name='signupextrav2',
            name='return_coach_departure_time',
            field=models.CharField(blank=True, choices=[('23:00', '23:00'), ('00:00', '00:00'), ('01:00', '01:00'), ('nobus', 'En tarvitse paluukyyti\xe4 (poistun omalla kyydill\xe4)')], help_text='Tracon tarjoaa maksuttoman bussikyydin kaatajaisiin ja takaisin Tampereen keskustorilta. Saavuthan hyviss\xe4 ajoin ennen valitsemaasi l\xe4ht\xf6aikaa l\xe4ht\xf6pys\xe4kille (Vanha kirkko), ja huolehdithan itse siit\xe4, ett\xe4 nouset oikeaan aikaan paluubussiin kaatajaispaikalla. Mik\xe4li my\xf6h\xe4styt valitsemastasi bussista, Tracon ei v\xe4ltt\xe4m\xe4tt\xe4 pysty tarjoamaan sinulle kyyti\xe4 kaatajaisiin tai sielt\xe4 pois. Bussit t\xe4ytet\xe4\xe4n ilmoittautumisj\xe4rjestyksess\xe4, ja mik\xe4li jokin busseista osoittautuu erityisen suosituksi, saatamme joutua siirt\xe4m\xe4\xe4n osallistujia bussista toiseen, mist\xe4 ilmoitamme s\xe4hk\xf6postitse. Meno- tai paluubussin vaihto kaatajaisilmoittautumisen sulkeuduttua ainoastaan kaatajaisvastaavan my\xf6t\xe4vaikutuksella os. kaatajaiset@tracon.fi, ei omin p\xe4in.', max_length=5, verbose_name='Paluubussin l\xe4ht\xf6aika'),
        ),
    ]
