# Generated by Django 1.9.9 on 2016-09-12 18:25


import core.csv_export
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracon11", "0008_auto_20160901_2351"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignupExtraV2AfterpartyProxy",
            fields=[],
            options={
                "proxy": True,
            },
            bases=("tracon11.signupextrav2", core.csv_export.CsvExportMixin),
        ),
        migrations.AddField(
            model_name="signupextrav2",
            name="afterparty_coaches_changed",
            field=models.BooleanField(default=False),
        ),
    ]
