# Generated by Django 1.10.8 on 2017-11-13 19:58
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracon11", "0009_auto_20160912_2125"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SignupExtraV2AfterpartyProxy",
        ),
    ]
