# Generated by Django 1.9.1 on 2016-01-28 16:05


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labour", "0015_auto_20160124_2328"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignupCertificateProxy",
            fields=[],
            options={
                "proxy": True,
            },
            bases=("labour.signup",),
        ),
        migrations.AddField(
            model_name="laboureventmeta",
            name="work_certificate_signer",
            field=models.TextField(
                blank=True,
                default="",
                help_text="T\xe4m\xe4n kent\xe4n sis\xe4lt\xf6 n\xe4kyy ty\xf6todistuksen allekirjoittajan nimenselvennyksen\xe4. On suositeltavaa sis\xe4llytt\xe4\xe4 t\xe4h\xe4n omalle rivilleen allekirjoittajan teht\xe4v\xe4nimike.",
                null=True,
                verbose_name="Ty\xf6todistuksen allekirjoittaja",
            ),
        ),
    ]
