# Generated by Django 1.9.1 on 2016-02-10 17:02


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labour", "0019_auto_20160207_2330"),
    ]

    operations = [
        migrations.AddField(
            model_name="signup",
            name="job_categories_rejected",
            field=models.ManyToManyField(
                blank=True,
                help_text="The workforce manager may use this field to inform other workforce managers that this applicant will not be accepted to a certain job category. This field is not visible to the applicant, but should they request a record of their own information, this field will be included.",
                related_name="_signup_job_categories_rejected_+",
                to="labour.JobCategory",
                verbose_name="Rejected job categories",
            ),
        ),
    ]
