# Generated by Django 1.9.5 on 2016-04-25 17:24


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("labour", "0016_auto_20151205_1321"),
        ("labour", "0025_auto_20160406_2144"),
    ]

    operations = []
