# Generated by Django 5.0.1 on 2024-01-17 13:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("labour", "0036_alter_survey_event"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="personnelclass",
            new_name="labour_pers_event_i_49de47_idx",
            old_fields=("event", "app_label"),
        ),
    ]
