# Generated by Django 5.0.1 on 2024-02-18 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emprinten", "0001_initial"),
        ("labour", "0037_rename_personnelclass_event_app_label_labour_pers_event_i_49de47_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="laboureventmeta",
            name="work_certificate_pdf_project",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="emprinten.project"
            ),
        ),
    ]
