# Generated by Django 5.0.8 on 2024-09-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labour", "0039_remove_personnelclass_perks_markdown_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alternativesignupform",
            name="signup_extra_form_class_path",
            field=models.CharField(
                default="labour.forms:SignupExtraForm",
                help_text="Viittaus lisätietolomakkeen toteuttavaan luokkaan. Esimerkki: tracon9.forms:ConcomSignupExtraForm",
                max_length=63,
            ),
        ),
    ]
