# Generated by Django 1.9.1 on 2016-02-16 16:08


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("tickets", "0009_accom_limit_group_refactor"),
    ]

    operations = [  # noqa: RUF012
        migrations.AddField(
            model_name="product",
            name="requires_shirt_size",
            field=models.BooleanField(default=False),
        ),
    ]
