# Generated by Django 1.9.5 on 2016-06-08 20:09


import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0016_remove_ticketseventmeta_plain_contact_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketseventmeta",
            name="contact_email",
            field=models.CharField(
                blank=True,
                help_text="Ongelmatilanteissa k\xe4ytt\xe4j\xe4\xe4 kehotetaan ottamaan yhteytt\xe4 t\xe4h\xe4n osoitteeseen. Muoto: Tracon 9 -lipunmyynti &lt;liput@tracon.fi&gt;",
                max_length=255,
                validators=[django.core.validators.RegexValidator(re.compile("(?P<name>.+) <(?P<email>.+@.+\\..+)>"))],
                verbose_name="Asiakaspalvelun s\xe4hk\xf6postiosoite selitteineen",
            ),
        ),
    ]
