# Generated by Django 1.9.5 on 2016-06-09 21:05


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0017_auto_20160608_2309"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shirtorder",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="shirt_orders", to="tickets.Order"
            ),
        ),
        migrations.AlterField(
            model_name="shirtorder",
            name="size",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="shirt_orders", to="tickets.ShirtSize"
            ),
        ),
        migrations.AlterField(
            model_name="shirtsize",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="shirt_sizes", to="tickets.ShirtType"
            ),
        ),
    ]
