# Generated by Django 1.9.5 on 2016-07-04 19:22


from django.db import migrations, models

import kompassi.core.utils.model_utils


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0018_auto_20160610_0005"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                validators=[kompassi.core.utils.model_utils.phone_number_validator],
                verbose_name="phone number",
            ),
        ),
    ]
