# Generated by Django 2.1.3 on 2018-11-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0024_ticketseventmeta_pos_access_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="allow_marketing_email",
            field=models.BooleanField(
                blank=True,
                default=True,
                verbose_name="Allow sending news and other information related to this event via e-mail",
            ),
        ),
    ]
