# Generated by Django 2.2.27 on 2022-03-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("tickets", "0026_auto_20200723_1925"),
    ]

    operations = [  # noqa: RUF012
        migrations.AlterField(
            model_name="product",
            name="internal_description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=150),
        ),
    ]
