# Generated by Django 4.2 on 2023-04-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("tickets", "0034_ticketseventmeta_accommodation_access_group"),
    ]

    operations = [  # noqa: RUF012
        migrations.AddField(
            model_name="ticketseventmeta",
            name="max_count_per_product",
            field=models.SmallIntegerField(default=99),
        ),
    ]
