# Generated by Django 4.2.6 on 2023-10-27 06:05

from django.db import migrations, models

import kompassi.core.utils.model_utils


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0037_alter_product_options_product_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shirtorder",
            name="order",
        ),
        migrations.RemoveField(
            model_name="shirtorder",
            name="size",
        ),
        migrations.AlterUniqueTogether(
            name="shirtsize",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="shirtsize",
            name="type",
        ),
        migrations.AlterUniqueTogether(
            name="shirttype",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="shirttype",
            name="event",
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "order", "verbose_name_plural": "orders"},
        ),
        migrations.RemoveField(
            model_name="customer",
            name="address",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="allow_marketing_email",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="city",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="zip_code",
        ),
        migrations.RemoveField(
            model_name="order",
            name="batch",
        ),
        migrations.RemoveField(
            model_name="product",
            name="requires_shipping",
        ),
        migrations.RemoveField(
            model_name="product",
            name="requires_shirt_size",
        ),
        migrations.RemoveField(
            model_name="ticketseventmeta",
            name="shipping_and_handling_cents",
        ),
        migrations.AddField(
            model_name="order",
            name="language",
            field=models.CharField(blank=True, default="fi", max_length=2, verbose_name="Kieli"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(
                blank=True,
                default="",
                max_length=30,
                validators=[kompassi.core.utils.model_utils.phone_number_validator],
                verbose_name="phone number",
            ),
        ),
        migrations.DeleteModel(
            name="Batch",
        ),
        migrations.DeleteModel(
            name="ShirtOrder",
        ),
        migrations.DeleteModel(
            name="ShirtSize",
        ),
        migrations.DeleteModel(
            name="ShirtType",
        ),
    ]
