# Generated by Django 5.0.8 on 2024-08-18 17:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0040_remove_ticketseventmeta_reservation_seconds"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticketseventmeta",
            name="due_days",
        ),
    ]
