# Generated by Django 5.0.8 on 2024-08-18 17:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("tickets", "0041_remove_ticketseventmeta_due_days"),
    ]

    operations = [  # noqa: RUF012
        migrations.RemoveField(
            model_name="ticketseventmeta",
            name="receipt_footer",
        ),
    ]
