# Generated by Django 1.10.8 on 2018-12-07 14:25
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("popcult2019", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signupextra",
            name="want_certificate",
            field=models.BooleanField(
                default=False, verbose_name="Haluan todistuksen työskentelystäni Popcult Helsingissä"
            ),
        ),
    ]
