# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-11 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracon2017', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupextra',
            name='afterparty_coaches_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signupextra',
            name='afterparty_participation',
            field=models.BooleanField(default=False, help_text='Ruksaa tämä ruutu, mikäli haluat osallistua kaatajaisiin. Mikäli mielesi muuttuu tai sinulle tulee este, peru ilmoittautumisesi poistamalla rasti tästä ruudusta.', verbose_name='Osallistun kaatajaisiin'),
        ),
        migrations.AddField(
            model_name='signupextra',
            name='outward_coach_departure_time',
            field=models.CharField(blank=True, choices=[('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('nobus', 'En tarvitse menokyytiä (tulen omalla kyydillä)')], default='', max_length=5, verbose_name='Menobussin lähtöaika'),
        ),
        migrations.AddField(
            model_name='signupextra',
            name='return_coach_departure_time',
            field=models.CharField(blank=True, choices=[('23:00', '23:00'), ('00:00', '00:00'), ('01:00', '01:00'), ('nobus', 'En tarvitse paluukyytiä (poistun omalla kyydillä)')], default='', help_text='Tracon tarjoaa maksuttoman bussikyydin kaatajaisiin ja takaisin Tampereen keskustorilta. Saavuthan hyvissä ajoin ennen valitsemaasi lähtöaikaa lähtöpysäkille (Vanha kirkko), ja huolehdithan itse siitä, että nouset oikeaan aikaan paluubussiin kaatajaispaikalla. Mikäli myöhästyt valitsemastasi bussista, Tracon ei välttämättä pysty tarjoamaan sinulle kyytiä kaatajaisiin tai sieltä pois. Bussit täytetään ilmoittautumisjärjestyksessä, ja mikäli jokin busseista osoittautuu erityisen suosituksi, saatamme joutua siirtämään osallistujia bussista toiseen, mistä ilmoitamme sähköpostitse. Meno- tai paluubussin vaihto kaatajaisilmoittautumisen sulkeuduttua ainoastaan kaatajaisvastaavan myötävaikutuksella os. kaatajaiset@tracon.fi, ei omin päin.', max_length=5, verbose_name='Paluubussin lähtöaika'),
        ),
    ]
