# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-12 19:59
from __future__ import unicode_literals

import core.csv_export
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracon2017', '0002_auto_20170911_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SignupExtraAfterpartyProxy',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('tracon2017.signupextra', core.csv_export.CsvExportMixin),
        ),
        migrations.AddField(
            model_name='signupextra',
            name='pick_your_poison',
            field=models.ManyToManyField(blank=True, help_text='Pyrimme siihen, että kaikki löytäisivät kaadon tarjoiluista jotain itselleen sopivaa. Ruksaa kaikki ne juomat, mitä saattaisit kuvitella nauttivasi kaadon aikana, niin yritämme arvioida määriä jotenkin sinne päin.', to='tracon2017.Poison', verbose_name='Mitä tykkäät juoda?'),
        ),
    ]
