# Generated by Django 2.1.12 on 2019-09-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracon2017', '0004_auto_20171113_2158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignupExtraAfterpartyProxy',
        ),
    ]
