# Generated by Django 4.2 on 2023-07-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shumicon2023", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="signupextra",
            name="shift_leader",
            field=models.BooleanField(
                default=False,
                verbose_name="Oletko kiinnostunut vuorovastaavan tehtävistä? Vuorovastaava koordinoi vuoron aikana tehtäviä ja tauotuksia.",
            ),
        ),
        migrations.AlterField(
            model_name="signupextra",
            name="build_participation",
            field=models.CharField(
                choices=[
                    ("ei", "En pysty osallistumaan kumpaankaan"),
                    ("kasaus", "Pystyn osallistumaan vain kasaukseen"),
                    ("purku", "Pystyn osallistumaan vain purkuun"),
                    ("molemmat", "Pystyn osallistumaan molempiin"),
                ],
                help_text="Valitse pystytkö osallistumaan kasaukseen ja/tai purkuun",
                max_length=15,
                verbose_name="Kasaus ja purku",
            ),
        ),
    ]
