# Generated by Django 1.9.5 on 2016-06-07 21:18


import django.db.models.deletion
from django.db import migrations, models

import kompassi.access.models.email_alias_mixin


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_auto_20160202_2235"),
        ("access", "0012_auto_20160607_2224"),
    ]

    operations = [
        migrations.CreateModel(
            name="InternalEmailAlias",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "account_name",
                    models.CharField(
                        blank=True,
                        help_text="Ennen @-merkki\xe4 tuleva osa s\xe4hk\xf6postiosoitetta. Muodostetaan automaattisesti jos tyhj\xe4.",
                        max_length=255,
                        verbose_name="account name",
                    ),
                ),
                (
                    "target_emails",
                    models.CharField(
                        help_text="E-mail to this alias will be directed to these e-mail addresses (separated by whitespace)",
                        max_length=1023,
                        verbose_name="target e-mail address",
                    ),
                ),
                (
                    "email_address",
                    models.CharField(
                        help_text="Muodostetaan automaattisesti", max_length=511, verbose_name="e-mail address"
                    ),
                ),
                ("app_label", models.CharField(blank=True, max_length=63)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("modified_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
            ],
            options={
                "verbose_name": "internal e-mail alias",
                "verbose_name_plural": "internal e-mail aliases",
            },
            bases=(kompassi.access.models.email_alias_mixin.EmailAliasMixin, models.Model),
        ),
        migrations.AddField(
            model_name="emailaliasdomain",
            name="has_internal_aliases",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="internalemailalias",
            name="domain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="access.EmailAliasDomain", verbose_name="domain"
            ),
        ),
        migrations.AddField(
            model_name="internalemailalias",
            name="event",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.Event"
            ),
        ),
    ]
