# Generated by Django 2.1.14 on 2019-12-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0016_auto_20190119_2213"),
    ]

    operations = [
        migrations.AddField(
            model_name="privilege",
            name="url",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
