# Generated by Django 5.2.4 on 2025-07-23 10:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0024_alter_emailaliasdomain_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailaliastype",
            name="account_name_code",
        ),
        migrations.RemoveField(
            model_name="emailaliastype",
            name="metavar",
        ),
    ]
