# Generated by Django 5.2.4 on 2025-07-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0025_remove_emailaliastype_account_name_code_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="privilege",
            options={},
        ),
        migrations.RemoveField(
            model_name="privilege",
            name="grant_code",
        ),
        migrations.AddField(
            model_name="privilege",
            name="type_slug",
            field=models.CharField(choices=[("SLACK", "SLACK")], default="SLACK", max_length=5, verbose_name="type"),
        ),
    ]
