# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-24 20:10
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yukicon2018', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupextra',
            name='shirt_size',
            field=models.CharField(choices=[('NO_SHIRT', 'Ei paitaa'), ('XS', 'XS Unisex'), ('S', 'S Unisex'), ('M', 'M Unisex'), ('L', 'L Unisex'), ('XL', 'XL Unisex'), ('XXL', 'XXL Unisex'), ('3XL', '3XL Unisex'), ('4XL', '4XL Unisex'), ('5XL', '5XL Unisex')], default='NO_SHIRT', help_text='Ajoissa ilmoittautuneet vänkärit saavat maksuttoman työvoimapaidan.', max_length=8, verbose_name='Paidan koko'),
        ),
        migrations.AlterField(
            model_name='signupextra',
            name='total_work',
            field=models.CharField(choices=[('10h', 'Minimi - 10 tuntia'), ('12h', '10-12 tuntia'), ('yli12h', 'Työn Sankari! Yli 12 tuntia!')], help_text='Kuinka paljon haluat tehdä töitä yhteensä tapahtuman aikana? Useimmissa tehtävistä minimi on kahdeksan tuntia, mutta joissain tehtävissä se voi olla myös vähemmän (esim. majoitusvalvonta 6 h).', max_length=15, verbose_name='Toivottu kokonaistyömäärä'),
        ),
    ]
