# Generated by Django 1.9.4 on 2016-04-06 18:51


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hitpoint2017", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="signupextra",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
