# Generated by Django 4.2.7 on 2023-11-26 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_alter_person_birth_date_alter_person_email_and_more"),
        ("intra", "0007_team_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intraeventmeta",
            name="event",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="%(class)s",
                serialize=False,
                to="core.event",
            ),
        ),
    ]
