# Generated by Django 6.0.2 on 2026-03-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finncon2026', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupextra',
            name='color_wish',
            field=models.TextField(blank=True, default='', help_text='Keräämme toivomuksia paidan pohjavärille!(graaffikkomme valitsee suosituimpien värien kesken työvoimapaidan ja conipaidan pohjavärit.)', verbose_name='Ehdota pohjaväriä työvoimapaille:'),
        ),
        migrations.AddField(
            model_name='signupextra',
            name='ika',
            field=models.BooleanField(default=False, help_text='Vapaaehtoistyöhön vaadimme Blaa blaa blaa', verbose_name='Oletko yli 15 vuotias?'),
        ),
    ]
