# Generated by Django 5.0.6 on 2024-06-15 05:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("directory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="directoryorganizationmeta",
            name="organization",
        ),
        migrations.DeleteModel(
            name="DirectoryAccessGroup",
        ),
        migrations.DeleteModel(
            name="DirectoryOrganizationMeta",
        ),
    ]
