# Generated by Django 2.1.4 on 2019-01-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hypecon2019", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="signupextra",
            name="want_certificate",
            field=models.BooleanField(default=False, verbose_name="Haluan todistuksen työskentelystäni Hypeconissa"),
        ),
    ]
