# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-15 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20170827_1818'),
        ('event_log', '0004_entry_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Person'),
        ),
    ]
