# Generated by Django 1.10.7 on 2017-09-15 16:21
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_log", "0006_auto_20170915_1845"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="ip_address",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The IP address this action was performed from.",
                max_length=48,
                verbose_name="IP address",
            ),
        ),
    ]
