# Generated by Django 4.2.8 on 2023-12-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hitpoint2024", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signupextra",
            name="shirt_size",
            field=models.CharField(
                choices=[
                    ("NO_SHIRT", "Ei paitaa"),
                    ("BEANIE", "Pipo"),
                    ("XS", "Paita – XS Unisex"),
                    ("S", "Paita – S Unisex"),
                    ("M", "Paita – M Unisex"),
                    ("L", "Paita – L Unisex"),
                    ("XL", "Paita – XL Unisex"),
                    ("XXL", "Paita – XXL Unisex"),
                    ("3XL", "Paita – 3XL Unisex"),
                    ("4XL", "Paita – 4XL Unisex"),
                    ("5XL", "Paita – 5XL Unisex"),
                    ("LF_S", "Paita – S Ladyfit"),
                    ("LF_M", "Paita – M Ladyfit"),
                    ("LF_L", "Paita – L Ladyfit"),
                    ("LF_XL", "Paita – XL Ladyfit"),
                ],
                default="NO_SHIRT",
                help_text='Ajoissa ilmoittautuneet vänkärit saavat maksuttoman työvoimapaidan tai pipon. Valitse tässä, haluatko pipon vai paidan, ja paidan tapauksessa myös paidan koko. Kokotaulukot: <a href="https://dc-collection.fi/product/TU03T" target="_blank" rel="noopener noreferrer">unisex-paita</a>, <a href="https://dc-collection.fi/product/TW04T" target="_blank" rel="noopener noreferrer">ladyfit-paita</a>',
                max_length=8,
                verbose_name="Swägivalinta",
            ),
        ),
    ]
