# Generated by Django 2.1.8 on 2019-06-14 11:20

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0025_auto_20181130_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomShirtProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('tickets.shirtorder',),
        ),
    ]
