# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-30 05:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ropecon2018', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupextra',
            name='extra_work',
        ),
    ]
