# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kawacon2016', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Night',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='signupextra',
            name='shirt_size',
            field=models.CharField(choices=[('NO_SHIRT', 'Ei paitaa'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], help_text='Ajoissa ilmoittautuneet v\xe4nk\xe4rit saavat maksuttoman ty\xf6voimapaidan. Kokotaulukot: <a href="http://www.bc-collection.eu/uploads/sizes/TU004.jpg" target="_blank">unisex-paita</a>, <a href="http://www.bc-collection.eu/uploads/sizes/TW040.jpg" target="_blank">ladyfit-paita</a>', max_length=8, verbose_name='Paidan koko'),
        ),
        migrations.AddField(
            model_name='signupextra',
            name='needs_lodging',
            field=models.ManyToManyField(blank=True, to='kawacon2016.Night', verbose_name='Majoitustarve lattiamajoituksessa'),
        ),
    ]
