# Generated by Django 2.2.16 on 2020-12-27 11:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event_log", "0008_subscription_job_category_filter"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="other_fields",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
