# Generated by Django 5.2.1 on 2025-06-13 13:33

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_emailverificationtoken_language_and_more"),
        ("dimensions", "0011_dimensionvalue_is_subject_locked"),
        ("forms", "0046_rename_response_responsedimensionvalue_subject_and_more"),
        ("involvement", "0002_invitation_and_more"),
        ("program_v2", "0039_programv2eventmeta_default_registry"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="involvement",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["cached_dimensions"],
                name="involvement_gin",
                opclasses=["jsonb_path_ops"],
            ),
        ),
    ]
