# Generated by Django 5.2.3 on 2025-07-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("involvement", "0003_involvement_involvement_gin"),
    ]

    operations = [  # noqa: RUF012
        migrations.AddField(
            model_name="invitation",
            name="cached_dimensions",
            field=models.JSONField(
                blank=True, default=dict, help_text="Dimensions to set on the Involvement created from this Invitation."
            ),
        ),
    ]
