# Generated by Django 5.2.3 on 2025-07-07 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("dimensions", "0012_universe_app_name"),
        ("involvement", "0004_invitation_cached_dimensions"),
        ("labour", "0042_signup_override_formatted_perks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="involvement",
            name="universe",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="all_involvements",
                to="dimensions.universe",
            ),
        ),
        migrations.CreateModel(
            name="InvolvementToBadgeMapping",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("required_dimensions", models.JSONField(default=dict)),
                ("job_title", models.CharField(blank=True, default="", max_length=255)),
                ("priority", models.IntegerField(default=0, help_text="smallest number is the highest priority")),
                ("annotations", models.JSONField(blank=True, default=dict)),
                (
                    "personnel_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="involvement_to_badge_mappings",
                        to="labour.personnelclass",
                    ),
                ),
                (
                    "universe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="involvement_to_badge_mappings",
                        to="dimensions.universe",
                    ),
                ),
            ],
            options={
                "ordering": ("universe", "priority"),
            },
        ),
        migrations.CreateModel(
            name="InvolvementToGroupMapping",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("required_dimensions", models.JSONField(default=dict)),
                (
                    "group",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="auth.group"),
                ),
                (
                    "universe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="involvement_to_group_mappings",
                        to="dimensions.universe",
                    ),
                ),
            ],
            options={
                "ordering": ("universe",),
            },
        ),
    ]
