# Generated by Django 5.2.4 on 2025-07-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("involvement", "0006_involvementeventmeta_involvement_annotations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="involvement",
            name="title",
            field=models.TextField(default=""),
        ),
    ]
