# Generated by Django 5.2.8 on 2025-12-13 13:15

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dimensions", "0017_remove_annotation_dimensions_annotation_type_annotationdatatype_and_more"),
        ("involvement", "0007_involvement_title"),
        ("labour", "0043_alter_personnelclass_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="involvementtobadgemapping",
            name="job_title_mode",
            field=django_enum.fields.EnumCharField(
                choices=[("fallback", "FALLBACK"), ("override", "OVERRIDE")], default="fallback", max_length=8
            ),
        ),
        migrations.AddConstraint(
            model_name="involvementtobadgemapping",
            constraint=models.CheckConstraint(
                condition=models.Q(("job_title_mode__in", ["fallback", "override"])),
                name="nvolvement_InvolvementToBadgeMapping_job_title_mode_JobTitleMode",
            ),
        ),
    ]
