# Generated by Django 6.0.5 on 2026-05-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("involvement", "0008_involvementtobadgemapping_job_title_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="involvementeventmeta",
            name="shirts_frozen_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When shirts were ordered, the shirt sizes in COMBINED_PERKS involvements are frozen. After this timestamp, only changing to ShirtSize.NONE is allowed.",
                null=True,
            ),
        ),
    ]
