# Generated by Django 6.1 on 2026-08-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("core", "0044_organization_business_id"),
        ("dimensions", "0019_rename_universe_app_name_to_app"),
        ("forms", "0057_rename_survey_app_name_purpose_slug"),
        ("involvement", "0010_involvementeventmeta_admin_group"),
        ("program_v2", "0053_alter_programv2eventmeta_public_from"),
    ]

    operations = [  # noqa: RUF012
        migrations.RemoveConstraint(
            model_name="involvement",
            name="involvement_Involvement_app_InvolvementApp",
        ),
        migrations.AddConstraint(
            model_name="involvement",
            constraint=models.CheckConstraint(
                condition=models.Q(("app__in", ["forms", "program", "involvement", "volunteers"])),
                name="involvement_Involvement_app_DimensionApp",
            ),
        ),
    ]
