# Generated by Django 6.1 on 2026-09-01 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("forms", "0057_rename_survey_app_name_purpose_slug"),
        ("involvement", "0011_remove_involvement_involvement_involvement_app_involvementapp_and_more"),
    ]

    operations = [  # noqa: RUF012
        migrations.AlterField(
            model_name="involvement",
            name="response",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="involvements",
                to="forms.response",
            ),
        ),
    ]
