# Generated by Django 6.1 on 2026-09-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("involvement", "0012_alter_involvement_response"),
    ]

    operations = [  # noqa: RUF012
        migrations.AddField(
            model_name="registry",
            name="default_retention_period",
            field=models.DurationField(
                blank=True,
                help_text="The default retention period for personal data in this registry, counted from the end of the year in which the event ends (or, lacking that, in which the record was created). If unset, personal data in this registry is retained indefinitely. Can be overridden per survey.",
                null=True,
            ),
        ),
    ]
