# Generated by Django 6.1 on 2026-09-03 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("involvement", "0013_registry_default_retention_period"),
    ]

    operations = [  # noqa: RUF012
        migrations.AlterField(
            model_name="involvementeventmeta",
            name="default_registry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="involvement_event_metas",
                to="involvement.registry",
            ),
        ),
    ]
