# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labour', '0021_auto_20160306_1125'),
    ]

    operations = [
        migrations.RenameModel('EmptySignupExtra', 'ObsoleteEmptySignupExtraV1'),
    ]
