# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import labour.models.signup_extras


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20160202_2235'),
        ('labour', '0023_auto_20160406_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmptySignupExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_signup_extras', to='core.Event')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='labour_signup_extra', to='core.Person')),
            ],
            options={
                'abstract': False,
            },
            bases=(labour.models.signup_extras.SignupExtraMixin, models.Model),
        ),
    ]
