# Generated by Django 1.10.7 on 2017-08-02 12:00
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("labour", "0032_survey_override_does_not_apply_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="personnelclass",
            name="icon_css_class",
            field=models.CharField(blank=True, default="fa-user", max_length=63),
        ),
        migrations.AlterField(
            model_name="signup",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="signups", to="core.Person"
            ),
        ),
    ]
