# Generated by Django 4.2.7 on 2023-11-26 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_alter_person_birth_date_alter_person_email_and_more"),
        ("labour", "0035_remove_personnelclass_perks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="labour_surveys", to="core.event"
            ),
        ),
    ]
