# Generated by Django 4.2.8 on 2023-12-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frostbite2024", "0002_alter_signupextra_shirt_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="signupextra",
            name="accommodation",
            field=models.CharField(
                choices=[
                    ("no_need", "En majoitu Kuusessa"),
                    ("pe_la", "Majoitun pe-la"),
                    ("la_su", "Majoitun la-su"),
                    ("whole_weekend", "Majoitun koko viikonlopun"),
                ],
                default="no_need",
                max_length=13,
                verbose_name="Työvoimamajoitus",
            ),
        ),
    ]
