# Generated by Django 2.2.16 on 2020-12-02 14:46

import django.contrib.postgres.fields.hstore
import django.db.models.deletion
from django.conf import settings
from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0011_update_proxy_permissions"),
        ("access", "0017_privilege_url"),
    ]

    operations = [
        HStoreExtension(),
        migrations.CreateModel(
            name="CBACEntry",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                (
                    "mode",
                    models.CharField(
                        choices=[("+", "Allow"), ("-", "Deny"), ("0", "Inactive")], default="+", max_length=1
                    ),
                ),
                ("claims", django.contrib.postgres.fields.hstore.HStoreField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "granted_by_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="auth.Group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cbac_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "index_together": {("user", "mode", "valid_until")},
            },
        ),
    ]
