# Generated by Django 5.2.1 on 2025-05-27 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0022_alter_privilege_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privilege",
            name="slug",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Tekninen nimi saa sisältää vain pieniä kirjaimia, numeroita sekä väliviivoja.",
                        regex="^[a-z0-9-]+$",
                    )
                ],
                verbose_name="Slug",
            ),
        ),
    ]
