# Generated by Django 4.2.6 on 2023-10-27 17:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hitpoint2017", "0004_auto_20170122_1920"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SignupExtra",
        ),
    ]
