# Generated by Django 1.10.7 on 2017-09-28 10:34
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrollment", "0004_auto_20170926_1851"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConconPart",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=63)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="concon_event_affiliation",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Mikäli edustat jotain tapahtumaorganisaatiota, voit kertoa siitä tässä. Conconiin ovat tervetulleita osallistumaan kaikki kiinnostuneet, eli minkään tapahtumaorganisaation edustaminen ei ole edellytys osallistumiselle. Jos annat julkaista nimesi osallistujalistassa, myös tämä kenttä näytetään siinä.",
                max_length=512,
                verbose_name="Mitä tapahtumia edustat?",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="is_public",
            field=models.NullBooleanField(
                choices=[
                    (True, "Sallin nimeni julkaisemisen osallistujalistassa"),
                    (False, "Kiellän nimeni julkaisemisen osallistujalistassa"),
                ],
                help_text='Tästä tapahtumasta julkistetaan osallistujalista, jossa näkyvät niiden osallistujien nimet, jotka ovat antaneet siihen luvan. Nimesi näytetään valitsemassasi muodossa, jonka voit tarkistaa ja muuttaa <a href="/profile" target="_blank">profiilissasi</a>.',
                verbose_name="Näkyminen osallistujalistassa",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="concon_parts",
            field=models.ManyToManyField(
                blank=True,
                help_text="Concon koostuu päivän luento- ja keskusteluohjelmasta sekä jatkosaunasta illalla.",
                to="enrollment.ConconPart",
                verbose_name="Mihin osiin tilaisuudesta osallistut?",
            ),
        ),
    ]
