# Generated by Django 2.1.5 on 2019-01-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrollment", "0005_auto_20170928_1334"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="address",
            field=models.CharField(blank=True, max_length=1023, verbose_name="Katuosoite"),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="city",
            field=models.CharField(blank=True, max_length=127, verbose_name="Postitoimipaikka"),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="personal_identification_number",
            field=models.CharField(
                blank=True,
                help_text="Henkilötunnus luovutetaan kurssin järjestäjälle todistuksen kirjoittamista varten. Henkilötunnukset poistetaan tämän jälkeen järjestelmästä.",
                max_length=12,
                verbose_name="Henkilötunnus",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="traconjv_expiring",
            field=models.DateField(blank=True, null=True, verbose_name="Milloin nykyinen JV-korttisi on umpeutumassa?"),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="traconjv_solemnly_swear",
            field=models.BooleanField(
                default=False,
                verbose_name="Vakuutan antamani tiedot oikeiksi. Sitoudun maksamaan kurssin hinnan täysimääräisenä, mikäli en pysty osallistumaan kurssille ja/tai järjestyksenvalvojana Tracon 2019 -tapahtumaan.",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="traconjv_when",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Milloin olet käynyt järjestyksenvalvojan peruskoulutuksen?"
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="zip_code",
            field=models.CharField(blank=True, max_length=5, verbose_name="Postinumero"),
        ),
        migrations.AddField(
            model_name="enrollmenteventmeta",
            name="is_official_name_required",
            field=models.BooleanField(
                default=False,
                help_text="If this option is selected, participants will be required to fill in their official names in their profile.",
                verbose_name="Official name required",
            ),
        ),
    ]
