# Generated by Django 6.1 on 2026-09-03 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0009_alter_enrollment_is_public_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='concon_parts',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='event',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='person',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='special_diet',
        ),
        migrations.RemoveField(
            model_name='enrollmenteventmeta',
            name='admin_group',
        ),
        migrations.RemoveField(
            model_name='enrollmenteventmeta',
            name='event',
        ),
        migrations.DeleteModel(
            name='ConconPart',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='EnrollmentEventMeta',
        ),
    ]
