# Generated by Django 5.1.5 on 2025-05-15 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import event_log_v2.utils.monthly_partitions
import tickets_v2.optimized_server.utils.uuid7


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0042_survey_purpose_slug"),
        ("involvement", "0001_initial"),
        ("program_v2", "0039_programv2eventmeta_default_registry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=tickets_v2.optimized_server.utils.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("fi", "Finnish"), ("sv", "Swedish")],
                        default="en",
                        help_text="The language of the invitation. This is used to send the invitation in the correct language.",
                        max_length=2,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="The email address of the person to invite. This is used to send the invitation.",
                        max_length=255,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "involvement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitation",
                        to="involvement.involvement",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="program_v2.program",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        help_text="When a user accepts this invitation, they will fill in this survey.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="forms.survey",
                    ),
                ),
            ],
            bases=(event_log_v2.utils.monthly_partitions.UUID7Mixin, models.Model),
        ),
    ]
