apiVersion: v1
kind: Service
metadata:
  name: uvicorn
  labels:
    stack: kompassi
    component: uvicorn
spec:
  ports:
    - port: 7998
      targetPort: 7998
  selector:
    stack: kompassi
    component: uvicorn
