apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: kompassi2
build:
  local:
    useBuildkit: true
  artifacts:
    - image: kompassi2
      context: .
deploy:
  statusCheckDeadlineSeconds: 300
  kubectl:
    manifests:
      - kubernetes/*.json
