# Generated by Django 4.2.1 on 2023-10-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kotaeexpo2024", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="signupextra",
            name="night_shift",
            field=models.BooleanField(default=False, verbose_name="Olen valmis tekemään yötöitä klo 23-07"),
        ),
        migrations.AlterField(
            model_name="signupextra",
            name="total_work",
            field=models.CharField(
                choices=[("4h", "Minivuoro"), ("8h", "Täysvuoro"), ("yli10h", "Supervuoro!")],
                help_text="Kuinka paljon haluat tehdä töitä yhteensä tapahtuman aikana? Huomaathan, ettei 4 tunnin työpanos oikeuta täysiin työvoimaetuihin. Tarkasta työvoimaedut Kotaen verkkosivuilta.",
                max_length=15,
                verbose_name="Toivottu kokonaistyömäärä",
            ),
        ),
    ]
