# Generated by Django 4.2.1 on 2023-10-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kotaeexpo2024", "0002_signupextra_night_shift_alter_signupextra_total_work"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accommodation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=63)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KnownLanguage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=63)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="signupextra",
            name="known_language_other",
            field=models.TextField(blank=True, verbose_name="Muu kieli"),
        ),
        migrations.AddField(
            model_name="signupextra",
            name="accommodation",
            field=models.ManyToManyField(
                blank=True,
                related_name="kotaeexpo2024_signup_extras",
                to="kotaeexpo2024.accommodation",
                verbose_name="Tarvitsen lattiamajoitusta",
            ),
        ),
        migrations.AddField(
            model_name="signupextra",
            name="known_language",
            field=models.ManyToManyField(
                blank=True,
                related_name="kotaeexpo2024_signup_extras",
                to="kotaeexpo2024.knownlanguage",
                verbose_name="Osaamasi kielet",
            ),
        ),
    ]
