# Generated by Django 5.0.4 on 2024-05-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kotaeexpo2024", "0004_alter_signupextra_total_work"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessibilityWarning",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=63)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=63)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
