# Generated by Django 1.9.1 on 2016-02-02 17:50


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0021_auto_20160201_0050"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={
                "ordering": ("personnel_class__event", "priority", "title"),
                "verbose_name": "role",
                "verbose_name_plural": "roles",
            },
        ),
        migrations.AddField(
            model_name="role",
            name="priority",
            field=models.IntegerField(
                default=0,
                help_text="Some events have speaker roles that convey different privileges. This priority field will put the speakers in their place.",
                verbose_name="Priority",
            ),
        ),
    ]
