# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 20:31
from __future__ import unicode_literals

import re

from django.db import migrations


SLUGIFY_CHAR_MAP = {
  u'ä': u'a',
  u'å': u'a',
  u'ö': u'o',
  u'ü': u'u',
  u' ': u'-',
  u'_': u'-',
  u'.': u'-',
}
SLUGIFY_FORBANNAD_RE = re.compile(ur'[^a-z0-9-]', re.UNICODE)
SLUGIFY_MULTIDASH_RE = re.compile(ur'-+', re.UNICODE)


def slugify(ustr):
    ustr = ustr.lower()
    ustr = u''.join(SLUGIFY_CHAR_MAP.get(c, c) for c in ustr)
    ustr = SLUGIFY_FORBANNAD_RE.sub(u'', ustr)
    ustr = SLUGIFY_MULTIDASH_RE.sub(u'-', ustr)
    return ustr


def populate_slug(apps, schema_editor):
    Programme = apps.get_model('programme', 'programme')

    for programme in Programme.objects.all():
        if not programme.slug:
            programme.slug = slugify(programme.title)
            programme.save()


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0024_auto_20160202_2236'),
    ]

    operations = [
        migrations.RunPython(populate_slug)
    ]
