# Generated by Django 1.9.5 on 2016-06-22 21:37


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0034_auto_20160608_2309"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="specialstarttime",
            options={
                "ordering": ["event", "start_time"],
                "verbose_name": "special start time",
                "verbose_name_plural": "special start times",
            },
        ),
        migrations.AlterField(
            model_name="specialstarttime",
            name="event",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.Event", verbose_name="event"),
        ),
        migrations.AlterField(
            model_name="specialstarttime",
            name="start_time",
            field=models.DateTimeField(verbose_name="starting time"),
        ),
    ]
