# Generated by Django 1.9.5 on 2016-06-27 17:57


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0037_populate_programme_frozen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programme",
            name="state",
            field=models.CharField(
                choices=[
                    ("idea", "Internal programme idea"),
                    ("asked", "Asked from the host"),
                    ("offered", "Offer received"),
                    ("accepted", "Accepted"),
                    ("published", "Published"),
                    ("cancelled", "Cancelled"),
                    ("rejected", "Rejected"),
                ],
                default="accepted",
                help_text='The programmes in the state "Published" will be visible to the general public, if the schedule has already been published.',
                max_length=15,
                verbose_name="State",
            ),
        ),
    ]
