# Generated by Django 1.10.8 on 2017-11-09 17:40
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_auto_20170827_1818"),
        ("programme", "0056_auto_20171104_1806"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="event",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.Event"
            ),
        ),
        migrations.AlterField(
            model_name="programme",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="programme.Room",
                verbose_name="Room",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="room",
            unique_together={("event", "slug")},
        ),
    ]
