# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-23 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0066_programme_ropecon2018_preferred_time_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='ropecon2018_audience_size',
            field=models.CharField(choices=[('unknown', 'No estimate'), ('lt50', 'Less than 50'), ('50-100', '50 - 100'), ('100-150', '100 - 150'), ('150-200', '150 - 200'), ('200-250', '200 - 250'), ('gt250', 'Over 250')], default='unknown', help_text='Estimate of audience size for talk/presentation, if you have previous experience.', max_length=7, null=True, verbose_name='Audience estimate'),
        ),
        migrations.AddField(
            model_name='programme',
            name='ropecon2018_is_no_language',
            field=models.BooleanField(default=False, help_text='No Finnish language needed to participate.', verbose_name='No language'),
        ),
        migrations.AddField(
            model_name='programme',
            name='ropecon2018_is_panel_attendance_ok',
            field=models.BooleanField(default=False, help_text='I can participate in a panel discussion related to my field of expertise.', verbose_name='Panel talk'),
        ),
        migrations.AddField(
            model_name='programme',
            name='ropecon2018_speciality',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='My field(s) of expertise'),
        ),
    ]
