# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-25 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0067_auto_20180223_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='ropecon2018_genre_drama',
            field=models.BooleanField(default=False, verbose_name='Drama'),
        ),
        migrations.AddField(
            model_name='programme',
            name='ropecon2018_genre_exploration',
            field=models.BooleanField(default=False, verbose_name='Exploration'),
        ),
        migrations.AddField(
            model_name='programme',
            name='ropecon2018_genre_fantasy',
            field=models.BooleanField(default=False, verbose_name='Fantasy'),
        ),
        migrations.AddField(
            model_name='programme',
            name='ropecon2018_genre_historical',
            field=models.BooleanField(default=False, verbose_name='Historical'),
        ),
        migrations.AddField(
            model_name='programme',
            name='ropecon2018_genre_horror',
            field=models.BooleanField(default=False, verbose_name='Horror'),
        ),
        migrations.AddField(
            model_name='programme',
            name='ropecon2018_genre_humor',
            field=models.BooleanField(default=False, verbose_name='Humor'),
        ),
        migrations.AddField(
            model_name='programme',
            name='ropecon2018_genre_modern',
            field=models.BooleanField(default=False, verbose_name='Modern'),
        ),
        migrations.AddField(
            model_name='programme',
            name='ropecon2018_genre_mystery',
            field=models.BooleanField(default=False, verbose_name='Mystery'),
        ),
        migrations.AddField(
            model_name='programme',
            name='ropecon2018_genre_scifi',
            field=models.BooleanField(default=False, verbose_name='Sci-fi'),
        ),
        migrations.AddField(
            model_name='programme',
            name='ropecon2018_genre_war',
            field=models.BooleanField(default=False, verbose_name='War'),
        ),
        migrations.AddField(
            model_name='programme',
            name='ropecon2018_style_character_driven',
            field=models.BooleanField(default=False, verbose_name='Character driven'),
        ),
        migrations.AddField(
            model_name='programme',
            name='ropecon2018_style_combat_driven',
            field=models.BooleanField(default=False, verbose_name='Combat driven'),
        ),
        migrations.AddField(
            model_name='programme',
            name='ropecon2018_style_light',
            field=models.BooleanField(default=False, verbose_name='Light'),
        ),
        migrations.AddField(
            model_name='programme',
            name='ropecon2018_style_rules_heavy',
            field=models.BooleanField(default=False, verbose_name='Rules heavy'),
        ),
        migrations.AddField(
            model_name='programme',
            name='ropecon2018_style_rules_light',
            field=models.BooleanField(default=False, verbose_name='Rules light'),
        ),
        migrations.AddField(
            model_name='programme',
            name='ropecon2018_style_serious',
            field=models.BooleanField(default=False, verbose_name='Serious'),
        ),
        migrations.AddField(
            model_name='programme',
            name='ropecon2018_style_story_driven',
            field=models.BooleanField(default=False, verbose_name='Story driven'),
        ),
    ]
