# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-05 17:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0068_auto_20180225_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='ropecon2018_characters',
            field=models.PositiveIntegerField(default=10, help_text='If the game design requires characters with a specific gender let us know in the notes.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='number of characters'),
        ),
        migrations.AddField(
            model_name='programme',
            name='ropecon2018_prop_requirements',
            field=models.CharField(blank=True, default='', help_text='Let us know what props and other equipment you need. Not all requests can be accommodated. Water and glasses are always provided.', max_length=200, null=True, verbose_name='Prop requirements'),
        ),
        migrations.AddField(
            model_name='programme',
            name='ropecon2018_sessions',
            field=models.PositiveIntegerField(default=2, help_text='This is your preference only. Due to the limited space we are not able to accommodate all requests. One four hour session gives you one weekend ticket. A second session gives you an additional day ticket.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='number of sessions'),
        ),
        migrations.AddField(
            model_name='programme',
            name='ropecon2018_signuplist',
            field=models.CharField(choices=[('itse', 'I will make my own signup sheet'), ('tiski', 'Desk will make the signup sheet')], default='itse', help_text='A self-made signup sheet allows you to ask more detailed player preferences. Larp-desk-made signup sheet is a list of participant names.', max_length=15, null=True, verbose_name='Do you make your own signup sheet'),
        ),
        migrations.AddField(
            model_name='programme',
            name='ropecon2018_space_requirements',
            field=models.CharField(blank=True, default='', help_text='Let us know of your requirements. Fully dark, separate rooms, water outlet, etc.', max_length=200, null=True, verbose_name='Space requirements'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='ropecon2018_style_light',
            field=models.BooleanField(default=False, verbose_name='Light game style'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='ropecon2018_style_serious',
            field=models.BooleanField(default=False, verbose_name='Serious game style'),
        ),
    ]
