# Generated by Django 1.10.8 on 2018-03-07 21:16
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0069_ropecon2018_kp_20180306_0934"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programme",
            name="ropecon2018_space_requirements",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Let us know of your requirements. Fully dark, separate rooms, water outlet, sound, light, etc. Not all requests can be accommodated so please give reasons how your request improves the game.",
                null=True,
                verbose_name="Space and technical requirements",
            ),
        ),
    ]
