# Generated by Django 1.10.8 on 2018-04-17 19:45
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0070_auto_20180307_2316"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="language",
            field=models.CharField(
                choices=[("fi", "Finnish"), ("sv", "Swedish"), ("en", "English")],
                default="fi",
                help_text="What is the primary language of your programme?",
                max_length=2,
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="programme",
            name="ropecon2018_prop_requirements",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Let us know what props and other equipment you need and if you can provide some of them yourself. Not all requests can be accommodated. Water and glasses are always provided.",
                max_length=200,
                null=True,
                verbose_name="Prop requirements",
            ),
        ),
        migrations.AlterField(
            model_name="programme",
            name="ropecon2018_sessions",
            field=models.PositiveIntegerField(
                default=2,
                help_text="Please let us know your preference. Due to the limited space we are not able to accommodate all requests. One four hour session gives you one weekend ticket. A second session gives you an additional day ticket.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)],
                verbose_name="number of times you want to run the game",
            ),
        ),
        migrations.AlterField(
            model_name="programme",
            name="ropecon2018_signuplist",
            field=models.CharField(
                choices=[("itse", "I will make my own signup sheet"), ("tiski", "Desk will make the signup sheet")],
                default="itse",
                help_text="A self-made signup sheet allows you to ask more detailed player preferences. Larp-desk-made signup sheet is a list of participant names.",
                max_length=15,
                null=True,
                verbose_name="Will you make your own signup sheet",
            ),
        ),
        migrations.AlterField(
            model_name="programme",
            name="ropecon2018_space_requirements",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Let us know of your requirements. Fully dark, separate rooms, water outlet, sound, light, etc. Not all requests can be accommodated so please explain how your request improves the game.",
                null=True,
                verbose_name="Space and technical requirements",
            ),
        ),
    ]
