# Generated by Django 1.10.8 on 2018-06-20 13:23
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0073_remove_programme_language_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programmefeedback",
            name="author",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.Person"
            ),
        ),
    ]
