# Generated by Django 2.1.5 on 2019-02-07 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paikkala", "0010_nonblank_room"),
        ("programme", "0075_auto_20181019_1918"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="is_using_paikkala",
            field=models.BooleanField(
                default=False,
                help_text="If selected, reserved seats for this programme will be offered.",
                verbose_name="Reservable seats",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="paikkala_program",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kompassi_programme",
                to="paikkala.Program",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="paikkala_room",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="paikkala.Room"),
        ),
    ]
