# Generated by Django 2.2.9 on 2020-02-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0097_auto_20200202_2051"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="ropecon2020_materials_language",
            field=models.CharField(
                blank=True, default="", max_length=1023, verbose_name="What language is used in the game materials?"
            ),
        ),
        migrations.AlterField(
            model_name="programme",
            name="ropecon2018_audience_size",
            field=models.CharField(
                choices=[
                    ("unknown", "No estimate"),
                    ("lt50", "Less than 50"),
                    ("50-100", "50 – 100"),
                    ("100-150", "100 – 150"),
                    ("150-200", "150 – 200"),
                    ("200-250", "200 – 250"),
                    ("gt250", "Over 250"),
                ],
                default="unknown",
                help_text="Estimate of audience size for talk/presentation, if you have previous experience.",
                max_length=7,
                null=True,
                verbose_name="Audience estimate",
            ),
        ),
        migrations.AlterField(
            model_name="programme",
            name="ropecon2019_gaming_desk_subtype",
            field=models.CharField(
                blank=True,
                choices=[("tmnt", "Tournament"), ("demo", "Demonstration"), ("open", "Open game"), ("othr", "Other")],
                help_text="What type of game programme are you offering? Tournament – organising your own game tournament or contest. Demonstration – showcasing, demonstrating and running demo games at the Experience Point. Open game – running games with or without specific scenarios by request. Other – Something other than mentioned above",
                max_length=4,
                verbose_name="Game program type",
            ),
        ),
    ]
