# Generated by Django 2.2.24 on 2021-09-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0105_programme_ropecon2021_gamedesk_materials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programme",
            name="ropecon2021_accessibility_inaccessibility",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The program involves some other form of inaccessibility. Please clarify.",
                null=True,
                verbose_name="Other inaccessibility",
            ),
        ),
        migrations.AlterField(
            model_name="programme",
            name="ropecon2021_gamedesk_materials",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Specify here whether your players are expected to bring their own game tools or other equipment and what that equipment is (e.g. card decks, figure armies).",
                null=True,
                verbose_name="Does your programme require materials from the players?",
            ),
        ),
    ]
