# Generated by Django 4.1.7 on 2023-03-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ropecon2023", "0002_language_remove_signupextra_can_english_and_more"),
        ("programme", "0110_alter_specialreservation_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="ropecon2023_accessibility_cant_use_mic",
            field=models.BooleanField(default=False, verbose_name="I can't use a microphone"),
        ),
        migrations.AddField(
            model_name="programme",
            name="ropecon2023_accessibility_limited_opportunities_to_move_around",
            field=models.BooleanField(
                default=False, verbose_name="There are limited opportunities to move around during the programme."
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="ropecon2023_accessibility_long_texts",
            field=models.BooleanField(
                default=False, verbose_name="Participation involves reading long texts independently"
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="ropecon2023_accessibility_participation_requires_dexterity",
            field=models.BooleanField(
                default=False, verbose_name="Participation requires some dexterity, e.g. that of hands and fingers."
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="ropecon2023_accessibility_participation_requires_react_quickly",
            field=models.BooleanField(
                default=False, verbose_name="Participation requires the ability to react quickly."
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="ropecon2023_accessibility_programme_duration_over_2_hours",
            field=models.BooleanField(
                default=False, verbose_name="The duration of the programme is over two hours without breaks."
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="ropecon2023_accessibility_texts_not_available_as_recordings",
            field=models.BooleanField(
                default=False,
                verbose_name="The programme includes texts that are essential to participation, and the texts are not available as recordings or read out loud.",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="ropecon2023_aimed_at_adult_attendees",
            field=models.BooleanField(
                default=False,
                help_text="If your programme is designed for adult attendees, please tick this box.",
                verbose_name="Aimed at adult attendees",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="ropecon2023_aimed_at_children_between_13_17",
            field=models.BooleanField(
                default=False,
                help_text="If your programme is designed for attendees between 13-17 years of age, please tick this box.",
                verbose_name="Aimed at children between 13-17",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="ropecon2023_aimed_at_children_under_13",
            field=models.BooleanField(
                default=False,
                help_text="If your programme is designed for attendees under the age of 13 years, please tick this box.",
                verbose_name="Aimed at children under 13",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="ropecon2023_beginner_friendly",
            field=models.BooleanField(
                default=False,
                help_text="If your programme is suitable for attendees with very limited knowledge or without any previous experience about the game or subject matter in question, please tick this box.",
                verbose_name="Beginner-friendly",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="ropecon2023_blocked_time_slots",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select the times when you are <b>NOT able</b> to run your larp. In other words, leave the times that you would be able to run your larp unselected!<br/>If you have a more specific request in mind regarding your schedule (for example, you would like to run your larp late at night), please let us know in the Comments section below.<br/>In this section, we would like to know more about how work or volunteer shifts, public transport schedules and other factors might be impacting your schedule. For example, if you need to leave the venue by 11pm to be able to catch the last bus to your accommodation.",
                related_name="+",
                to="ropecon2023.timeslot",
                verbose_name="When are you NOT able to host your programme?",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="ropecon2023_celebratory_year",
            field=models.BooleanField(
                default=False,
                help_text="Check this box, if your programme is related to Ropecon's 30th celebratory year.",
                verbose_name="Celebratory Year",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="ropecon2023_for_18_plus_only",
            field=models.BooleanField(
                default=False,
                help_text="If your programme contains themes that require attendees to be 18 years or older, please tick this box. There will be an ID check for all attendees.",
                verbose_name="For 18+ only",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="ropecon2023_language",
            field=models.CharField(
                choices=[
                    ("finnish", "Finnish"),
                    ("english", "English"),
                    ("language_free", "Language-free"),
                    ("finnish_or_english", "Finnish or English"),
                ],
                default="finnish",
                help_text="Finnish - choose this, if only Finnish is spoken in your programme.<br/>English - choose this, if only English is spoken in your programme.<br/>Language-free - choose this, if no Finnish or English is necessary to participate in the programme (e.g. a workshop with picture instructions or a dance where one can follow what others are doing).<br/>Finnish or English - choose this, if you are okay with having your game programme language based on what language the attendees speak. Please write your title and game programme description in both languages.",
                max_length=18,
                null=True,
                verbose_name="Choose the language used in your programme",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="ropecon2023_suitable_for_all_ages",
            field=models.BooleanField(
                default=False,
                help_text="If your programme is suitable for all ages, please tick this box.",
                verbose_name="Suitable for all ages",
            ),
        ),
        migrations.AlterField(
            model_name="programme",
            name="ropecon2021_accessibility_inaccessibility",
            field=models.TextField(
                blank=True,
                default="",
                help_text="In the open field, define if necessary what features of your programme may possibly limit or enable participation (e.g. if the programme is available in sign language).",
                null=True,
                verbose_name="Other inaccessibility",
            ),
        ),
        migrations.AlterField(
            model_name="programme",
            name="ropecon2022_content_warnings",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Examples: spiders, violence, phobias or other possibly triggering themes",
                max_length=1023,
                verbose_name="Tell us here if your programme contains heavy subjects that may cause discomfort or distress in some participants",
            ),
        ),
    ]
