# Generated by Django 4.1.7 on 2023-03-12 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0112_programme_ropecon2023_other_accessibility_information_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="ropecon2023_chairs",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="How many chairs are needed for your game programme.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)],
                verbose_name="Number of chairs",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="ropecon2023_signuplist",
            field=models.CharField(
                choices=[
                    ("none", "No sign-up"),
                    ("konsti", "Sign-up via the Konsti app"),
                    ("othersign", "Other sign-up process"),
                ],
                default="none",
                help_text="How will players sign up for your game programme?<br/>No sign-up - no sign-up is required to participate in the game programme.<br/>Sign-up via the Konsti app - the sign-up process for the game programme is done via the Konsti app during the event.<br/>Other sign-up process - if your game programme requires attendees to sign up beforehand and you prefer to handle it through some other means (e.g. at the Gaming Desk), please choose this option and describe the sign-up process in the Comments section below.",
                max_length=15,
                null=True,
                verbose_name="Sign-up process",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="ropecon2023_tables",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="How much table space is needed for your game programme: how many tables in total?<br/>Table size is 70 cm x 200 cm.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)],
                verbose_name="Number of tables",
            ),
        ),
        migrations.AlterField(
            model_name="programme",
            name="ropecon2023_beginner_friendly",
            field=models.BooleanField(
                default=False,
                help_text="If your programme is suitable for attendees with very limited knowledge or without any previous experience about the programme or subject matter in question, please tick this box.",
                verbose_name="Beginner-friendly",
            ),
        ),
    ]
