# Generated by Django 4.1.7 on 2023-03-14 20:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0115_alter_category_options_category_order"),
        ("programme", "0115_programme_ropecon2023_workshop_fee"),
    ]

    operations = []
