# Generated by Django 4.2.6 on 2023-11-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("solmukohta2024", "0001_initial"),
        ("programme", "0118_alter_programme_photography_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="hosts_from_host",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Please provide the names as they should be presented in the programme guide; please also indicate their role in the programme, if there are multiple roles (moderator, panelist, etc.)",
                max_length=1023,
                verbose_name="Programme host names",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="solmukohta2024_areas_of_expertise",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Please fill this in only if you checked the Panel participation box above",
                verbose_name="Areas of expertise",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="solmukohta2024_computer_usage",
            field=models.CharField(
                choices=[
                    ("own_pc", "I will bring my own laptop (PC)"),
                    ("own_mac", "I will bring my own laptop (Mac)"),
                    ("borrow", "I will need to borrow someone else's laptop"),
                    ("nope", "I do not need a computer for my programme item"),
                ],
                default="",
                max_length=7,
                verbose_name="Computer use",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="solmukohta2024_content_warnings",
            field=models.ManyToManyField(
                blank=True,
                help_text='Please check all that apply; if there are other potential content warnings, add them under "other".',
                to="solmukohta2024.contentwarning",
                verbose_name="The programme item contains...",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="solmukohta2024_documentation",
            field=models.ManyToManyField(
                blank=True,
                help_text="Check all that apply; you can learn more about these options in the Hosting Guide.",
                to="solmukohta2024.documentation",
                verbose_name="Documentation",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="solmukohta2024_have_you_hosted_before",
            field=models.CharField(
                choices=[
                    ("many", "Yes, many times"),
                    ("couple", "Yes, a couple of times"),
                    ("few", "Yes, once or twice"),
                    ("nope", "No, this is my first time"),
                ],
                default="",
                max_length=6,
                verbose_name="Have you hosted program for SK/KP before?",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="solmukohta2024_mentoring",
            field=models.ManyToManyField(
                blank=True,
                help_text="Less experienced presenters who would like some guidance may request a mentor. More experienced presenters can volunteer here to help. (This usually involves a few emails or Skype calls 1-2 months leading up to the event.)",
                to="solmukohta2024.mentoring",
                verbose_name="Mentoring",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="solmukohta2024_other_needs",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Please enter any other needs here, such as paper and markers for a workshop, spatial needs for a larp, etc. Also mention here if you want to have your programme item outside, in the pool, or in an otherwise unusual environment.",
                verbose_name="Other needs",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="solmukohta2024_panel_participation",
            field=models.ManyToManyField(
                blank=True, to="solmukohta2024.panelparticipation", verbose_name="Panel participation"
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="solmukohta2024_scheduling",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Please tell us if there are any restrictions to scheduling your programme item (if you will be arriving late or leaving early or the like).",
                verbose_name="Scheduling restrictions",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="solmukohta2024_ticket",
            field=models.BooleanField(
                default=False,
                help_text="I understand that if my programme item is accepted, I will still need to purchase a Solmukohta 2024 ticket in order to attend.",
                verbose_name="Solmukohta 2024 ticket",
            ),
        ),
    ]
