# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desuprofile_integration', '0004_auto_20151108_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcode',
            name='state',
            field=models.CharField(choices=[(b'valid', 'Valid'), (b'used', 'Used'), (b'revoked', 'Revoked')], default=b'valid', max_length=8),
        ),
    ]
