# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-15 22:08


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kawacon2017', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupextra',
            name='want_certificate',
            field=models.BooleanField(default=False, verbose_name='Haluan ty\xf6todistuksen ty\xf6skentelyst\xe4ni Kawaconissa'),
        ),
    ]
