# Generated by Django 1.9.12 on 2017-03-15 22:30


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kawacon2017", "0002_signupextra_want_certificate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=63)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="signupextra",
            name="shifts",
            field=models.ManyToManyField(
                help_text="Milloin olet k\xe4ytett\xe4viss\xe4? Tilav\xe4nk\xe4reille (ja muille halukkaille) on tarjolla ty\xf6vuoroja my\xf6s ennen conin aukeamista sek\xe4 conin p\xe4\xe4ttymisen j\xe4lkeen.",
                to="kawacon2017.Shift",
                verbose_name="Voin ty\xf6skennell\xe4",
            ),
        ),
    ]
