# Generated by Django 1.9.1 on 2016-01-24 21:28


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("desuprofile_integration", "0004_auto_20151108_1905"),
    ]

    operations = [
        migrations.AlterField(
            model_name="confirmationcode",
            name="state",
            field=models.CharField(
                choices=[("valid", "Valid"), ("used", "Used"), ("revoked", "Revoked")], default="valid", max_length=8
            ),
        ),
    ]
