# Generated by Django 5.0.1 on 2024-01-17 13:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("desuprofile_integration", "0006_auto_20190909_2157"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="confirmationcode",
            new_name="desuprofile_person__372366_idx",
            old_fields=("person", "state"),
        ),
    ]
