# Generated by Django 5.0.1 on 2024-02-03 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_rename_emailverificationtoken_person_state_core_emailv_person__722147_idx_and_more"),
        ("payments", "0010_alter_checkoutpayment_customer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentsorganizationmeta",
            name="stripe_api_secret",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentsorganizationmeta",
            name="stripe_webhook_secret",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="StripePayment",
            fields=[
                ("transaction_id", models.TextField(default="", editable=False, primary_key=True, serialize=False)),
                ("reference", models.TextField(editable=False)),
                ("price_cents", models.IntegerField(editable=False)),
                ("items", models.JSONField(editable=False)),
                ("customer", models.JSONField(editable=False)),
                ("provider", models.TextField(blank=True, editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("complete", "Complete"), ("expired", "Expired"), ("paid", "Paid")],
                        default="new",
                        editable=False,
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.event"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.organization"),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
