# Generated by Django 1.9.1 on 2016-01-29 15:09


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0006_badgeseventmeta_real_name_must_be_visible"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="badgeseventmeta",
            name="badge_factory_code",
        ),
    ]
