# Generated by Django 1.9.1 on 2016-01-29 20:45


import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("badges", "0014_auto_20160129_2230"),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="badges_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="badge",
            name="revoked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="badges_revoked",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Revoked by",
            ),
        ),
        migrations.AlterField(
            model_name="badge",
            name="is_first_name_visible",
            field=models.BooleanField(default=True, verbose_name="Is first name visible"),
        ),
        migrations.AlterField(
            model_name="badge",
            name="nick",
            field=models.CharField(
                blank=True,
                help_text="If you only have a single piece of information to print on the badge, use this field.",
                max_length=1023,
                verbose_name="Nick name",
            ),
        ),
    ]
