# Generated by Django 5.1.5 on 2025-04-27 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0028_remove_badgeseventmeta_onboarding_instructions_markdown_and_more"),
        ("forms", "0038_survey_created_at_survey_created_by_and_more"),
        ("labour", "0042_signup_override_formatted_perks"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyToBadgeMapping",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("required_dimensions", models.JSONField(default=dict)),
                ("job_title", models.CharField(blank=True, default="", max_length=255)),
                (
                    "personnel_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badge_mappings",
                        to="labour.personnelclass",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="badge_mappings", to="forms.survey"
                    ),
                ),
            ],
        ),
    ]
