# Generated by Django 5.1.5 on 2025-05-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0029_surveytobadgemapping"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="surveytobadgemapping",
            options={"ordering": ("survey", "priority")},
        ),
        migrations.AddField(
            model_name="surveytobadgemapping",
            name="annotations",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="surveytobadgemapping",
            name="priority",
            field=models.IntegerField(default=0, help_text="smallest number is the highest priority"),
        ),
    ]
