# Generated by Django 2.2.10 on 2020-07-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intra", "0006_auto_20171113_2158"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="is_public",
            field=models.BooleanField(default=True, verbose_name="Public"),
        ),
    ]
