# Generated by Django 4.1.7 on 2023-02-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ropecon2023", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=63)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="signupextra",
            name="can_english",
        ),
        migrations.RemoveField(
            model_name="signupextra",
            name="can_finnish",
        ),
        migrations.AddField(
            model_name="signupextra",
            name="languages",
            field=models.ManyToManyField(blank=True, to="ropecon2023.language", verbose_name="Kielet"),
        ),
    ]
