# Generated by Django 5.0.7 on 2024-07-30 13:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FeedbackMessage",
        ),
    ]
