# Generated by Django 1.10.8 on 2018-09-13 05:13
from django.db import migrations, models

import kompassi.core.csv_export


class Migration(migrations.Migration):
    dependencies = [
        ("tracon2018", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Poison",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=63)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SignupExtraAfterpartyProxy",
            fields=[],
            options={
                "proxy": True,
            },
            bases=("tracon2018.signupextra", kompassi.core.csv_export.CsvExportMixin),
        ),
        migrations.AddField(
            model_name="signupextra",
            name="afterparty_coaches_changed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="signupextra",
            name="afterparty_participation",
            field=models.BooleanField(
                default=False,
                help_text="Ruksaa tämä ruutu, mikäli haluat osallistua kaatajaisiin. Mikäli mielesi muuttuu tai sinulle tulee este, peru ilmoittautumisesi poistamalla rasti tästä ruudusta.",
                verbose_name="Osallistun kaatajaisiin",
            ),
        ),
        migrations.AddField(
            model_name="signupextra",
            name="outward_coach_departure_time",
            field=models.CharField(
                blank=True,
                choices=[
                    ("16:00", "16:00"),
                    ("17:00", "17:00"),
                    ("18:00", "18:00"),
                    ("nobus", "En tarvitse menokyytiä (tulen omalla kyydillä)"),
                ],
                default="",
                max_length=5,
                verbose_name="Menobussin lähtöaika",
            ),
        ),
        migrations.AddField(
            model_name="signupextra",
            name="return_coach_departure_time",
            field=models.CharField(
                blank=True,
                choices=[
                    ("23:00", "23:00"),
                    ("00:00", "00:00"),
                    ("01:00", "01:00"),
                    ("nobus", "En tarvitse paluukyytiä (poistun omalla kyydillä)"),
                ],
                default="",
                help_text="Tracon tarjoaa maksuttoman bussikyydin kaatajaisiin ja takaisin Tampereen keskustorilta. Saavuthan hyvissä ajoin ennen valitsemaasi lähtöaikaa lähtöpysäkille (Vanha kirkko), ja huolehdithan itse siitä, että nouset oikeaan aikaan paluubussiin kaatajaispaikalla. Mikäli myöhästyt valitsemastasi bussista, Tracon ei välttämättä pysty tarjoamaan sinulle kyytiä kaatajaisiin tai sieltä pois. Bussit täytetään ilmoittautumisjärjestyksessä, ja mikäli jokin busseista osoittautuu erityisen suosituksi, saatamme joutua siirtämään osallistujia bussista toiseen, mistä ilmoitamme sähköpostitse. Meno- tai paluubussin vaihto kaatajaisilmoittautumisen sulkeuduttua ainoastaan kaatajaisvastaavan myötävaikutuksella os. kaatajaiset@tracon.fi, ei omin päin.",
                max_length=5,
                verbose_name="Paluubussin lähtöaika",
            ),
        ),
        migrations.AddField(
            model_name="signupextra",
            name="willing_to_bartend",
            field=models.BooleanField(
                default=False, verbose_name="Olen halukas tekemään 1h juomienkaatonakin kaatajaisissa"
            ),
        ),
        migrations.AlterField(
            model_name="signupextra",
            name="total_work",
            field=models.CharField(
                choices=[("10h", "Minimi - 10 tuntia"), ("yli10h", "Työn Sankari! Yli 10 tuntia!")],
                help_text="Kuinka paljon haluat tehdä töitä yhteensä tapahtuman aikana? Minimi on pääsääntöisesti kymmenen tuntia.",
                max_length=15,
                verbose_name="Toivottu kokonaistyömäärä",
            ),
        ),
        migrations.AddField(
            model_name="signupextra",
            name="pick_your_poison",
            field=models.ManyToManyField(
                blank=True,
                help_text="Pyrimme siihen, että kaikki löytäisivät kaadon tarjoiluista jotain itselleen sopivaa. Ruksaa kaikki ne juomat, mitä saattaisit kuvitella nauttivasi kaadon aikana, niin yritämme arvioida määriä jotenkin sinne päin. Huomaathan kuitenkin, että haluamme pitää kaadon kaikille mukavana ja turvallisena, eikä kaadossa ole tarkoitus juoda itseään örveltäväksi idiootiksi.",
                to="tracon2018.Poison",
                verbose_name="Mitä tykkäät juoda?",
            ),
        ),
    ]
