# Generated by Django 2.1.12 on 2019-09-09 18:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("tracon2018", "0002_auto_20180913_0813"),
    ]

    operations = [  # noqa: RUF012
        migrations.DeleteModel(
            name="SignupExtraAfterpartyProxy",
        ),
    ]
