# Generated by Django 5.1.5 on 2025-04-23 15:10

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets_v2", "0005_ticketsv2eventmeta_contact_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketsv2eventmeta",
            name="contact_email",
            field=models.CharField(
                blank=True,
                help_text="Foo Bar &lt;foo.bar@example.com&gt;",
                max_length=255,
                validators=[django.core.validators.RegexValidator(re.compile("(?P<name>.+) <(?P<email>.+@.+\\..+)>"))],
            ),
        ),
    ]
