# Generated by Django 6.0.3 on 2026-04-24 14:16

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets_v2", "0007_no_receipt_on_cancel"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="vat_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="VAT percentage applied to this product. Prices are inclusive of VAT.",
                max_digits=4,
            ),
        ),
    ]
