# Generated by Django 6.0.6 on 2026-06-12 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0044_organization_business_id"),
        ("tickets_v2", "0008_product_vat_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketsv2eventmeta",
            name="cancellation_period_days",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Number of days from order creation during which the customer can cancel a paid order themselves. The period is further capped at event start. 0 = customer self-service cancellation disabled.",
            ),
        ),
        migrations.CreateModel(
            name="OrderCancellationToken",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_id", models.UUIDField()),
                ("code", models.CharField(max_length=63, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[("valid", "Valid"), ("used", "Used"), ("revoked", "Revoked")],
                        default="valid",
                        max_length=8,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("fi", "Finnish"), ("sv", "Swedish")], default="en", max_length=2
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="core.event"),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["event", "order_id", "state"], name="tickets_v2__event_i_7b245d_idx")],
            },
        ),
    ]
