# Generated by Django 6.0.7 on 2026-08-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("tickets_v2", "0014_unpaid_order_cancellation_delay_minutes"),
    ]

    operations = [  # noqa: RUF012
        migrations.AlterField(
            model_name="paymentstamp",
            name="data",
            field=models.JSONField(
                help_text=(
                    "What we sent to or received from the payment provider. "
                    "Sensitive details such as API credentials, PII etc. may be redacted. "
                    "Also fields lifted to relational fields need not be repeated here."
                )
            ),
        ),
    ]
