# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-06 09:43


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tylycon2017', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupextra',
            name='total_work',
            field=models.CharField(choices=[('4h', 'Minimi - 4 tuntia'), ('6h', '6 tuntia'), ('8h', '8 tuntia'), ('12h', '10\xe2\x80\x9312 tuntia')], help_text='Kuinka paljon haluat tehd\xe4 t\xf6it\xe4 yhteens\xe4 tapahtuman aikana?', max_length=15, verbose_name='Toivottu kokonaisty\xf6m\xe4\xe4r\xe4'),
        ),
    ]
