# Generated by Django 1.9.9 on 2016-10-12 18:09


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tylycon2017", "0002_auto_20161006_1243"),
    ]

    operations = [
        migrations.AddField(
            model_name="signupextra",
            name="motivation",
            field=models.TextField(
                blank=True,
                help_text="Kerro, miksi haluat t\xf6ihin juuri t\xe4h\xe4n coniin.",
                verbose_name="Miksi haet Tylyconiin?",
            ),
        ),
    ]
