# Generated by Django 1.9.9 on 2016-10-20 15:50


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tylycon2017", "0003_signupextra_motivation"),
    ]

    operations = [
        migrations.AddField(
            model_name="signupextra",
            name="shift_cleanup",
            field=models.BooleanField(
                default=False,
                help_text="Viimeiset ty\xf6teht\xe4v\xe4t jatkuvat klo 20 asti. \xc4l\xe4 valitse t\xe4t\xe4 ruutua, jos et esimerkiksi kulkuyhteyksien vuoksi pysty j\xe4\xe4m\xe4\xe4n Malmitalolle klo 20:en asti.",
                verbose_name="Voin ty\xf6skennell\xe4 illalla klo 20 asti",
            ),
        ),
        migrations.AddField(
            model_name="signupextra",
            name="shift_setup",
            field=models.BooleanField(
                default=False,
                help_text="Ensimm\xe4iset ty\xf6teht\xe4v\xe4t alkavat klo 8. \xc4l\xe4 valitse t\xe4t\xe4 ruutua, jos et esimerkiksi kulkuyhteyksien vuoksi pysty saapumaan Malmitalolle klo 8:an menness\xe4.",
                verbose_name="Voin ty\xf6skennell\xe4 aamulla klo 8 alkaen",
            ),
        ),
    ]
