# Generated by Django 1.10.8 on 2018-02-03 21:26
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matsucon2018", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="signupextra",
            name="more_info",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Jos valitsit työn, joka tarvitsee selvennystä osaamisestasi (ensiapukortti, linkki portfolioon jne.), kirjoita siitä tähän.",
                verbose_name="Lisätietoja osaamisestasi",
            ),
        ),
        migrations.AddField(
            model_name="signupextra",
            name="need_lodging",
            field=models.BooleanField(default=False, verbose_name="Tarvitsen majoituksen (lattiamajoitus)"),
        ),
        migrations.AddField(
            model_name="signupextra",
            name="night_work",
            field=models.BooleanField(
                default=False, verbose_name="Olen valmis tekemään yötyötä (jos valitsit työn, joka sellaista sisältää)"
            ),
        ),
        migrations.AlterField(
            model_name="signupextra",
            name="free_text",
            field=models.TextField(
                blank=True, help_text="Muuta kerrottavaa? Kysyttävää? Kirjoita se tähän.", verbose_name="Vapaa sana"
            ),
        ),
        migrations.AlterField(
            model_name="signupextra",
            name="prior_experience",
            field=models.TextField(
                blank=True,
                help_text="Oletko tehnyt vastaavaa työtä aikaisemmin? Muuta hyödyllistä työkokemusta? Kerro itsestäsi!",
                verbose_name="Työkokemus",
            ),
        ),
    ]
