# Generated by Django 5.1.5 on 2025-04-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracon2025", "0003_remove_signupextra_certificate_delivery_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signupextra",
            name="shirt_size",
            field=models.CharField(
                choices=[
                    ("NO_SHIRT", "Ei paitaa"),
                    ("XS", "XS Unisex"),
                    ("S", "S Unisex"),
                    ("M", "M Unisex"),
                    ("L", "L Unisex"),
                    ("XL", "XL Unisex"),
                    ("XXL", "2XL Unisex"),
                    ("3XL", "3XL Unisex"),
                    ("4XL", "4XL Unisex"),
                    ("5XL", "5XL Unisex"),
                    ("LF_XS", "XS Ladyfit"),
                    ("LF_S", "S Ladyfit"),
                    ("LF_M", "M Ladyfit"),
                    ("LF_L", "L Ladyfit"),
                    ("LF_XL", "XL Ladyfit"),
                    ("LF_XXL", "2XL Ladyfit"),
                    ("LF_3XL", "3XL Ladyfit"),
                    ("BAG", "Kangaskassi"),
                ],
                default="NO_SHIRT",
                help_text='Ajoissa ilmoittautuneet vänkärit saavat maksuttoman työvoimapaidan tai kangaskassin. Valitse tässä haluatko paidan vai kangaskassin, sekä paidan koko. <a href="/static/tracon2022/tracon2022_shirt_sizes.png" target="_blank" rel="noopener noreferrer">Kokotaulukko</a>',
                max_length=8,
                verbose_name="Swag-valinta",
            ),
        ),
    ]
