# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-01 14:39
from __future__ import unicode_literals

import core.models.group_management_mixin
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0023_auto_20160704_2155'),
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentEventMeta',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='enrollmenteventmeta', serialize=False, to='core.Event')),
                ('enrollment_opens', models.DateTimeField(blank=True, null=True, verbose_name='Enrollment opens')),
                ('enrollment_closes', models.DateTimeField(blank=True, null=True, verbose_name='Enrollment closes')),
                ('admin_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, core.models.group_management_mixin.GroupManagementMixin),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Event'),
        ),
    ]
