# Generated by Django 1.9.9 on 2016-10-11 17:48


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrollment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollmenteventmeta",
            name="override_enrollment_form_message",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Use this field to override the message that is shown in top of the enrollment form. If this field is not filled in, a default message is shown.",
                verbose_name="Enrollment form message",
            ),
        ),
    ]
