# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-07 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_enrollment_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialDiet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='special_diet_other',
            field=models.TextField(blank=True, help_text="If you're on a diet that's not included in the list, please detail your diet here. Event organizer will try to take dietary needs into consideration, but all diets may not be catered for.", verbose_name='Other diets'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='special_diet',
            field=models.ManyToManyField(blank=True, to='enrollment.SpecialDiet', verbose_name='_("Diet")'),
        ),
    ]
