# Generated by Django 1.10.7 on 2017-04-17 19:59
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrollment", "0002_enrollmenteventmeta_override_enrollment_form_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="special_diet",
            field=models.ManyToManyField(
                blank=True, related_name="enrollments", to="enrollment.SpecialDiet", verbose_name="Diet"
            ),
        ),
    ]
