# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-07 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_auto_20161007_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmenteventmeta',
            name='form_code',
            field=models.CharField(default=1, help_text='Reference to form class. Example: yukicon2016.forms:EnrollmentForm', max_length=63),
            preserve_default=False,
        ),
    ]
