# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-07 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0004_auto_20161007_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmenteventmeta',
            name='form_code',
        ),
        migrations.AddField(
            model_name='enrollmenteventmeta',
            name='form_code_path',
            field=models.CharField(default=1, help_text='Reference to form class. Example: events.yukicon2016.forms:EnrollmentForm', max_length=63),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Person'),
            preserve_default=False,
        ),
    ]
