# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-08 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0005_auto_20161007_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='special_diet',
            field=models.ManyToManyField(blank=True, to='enrollment.SpecialDiet', verbose_name='Diet'),
        ),
    ]
