#!/bin/bash

set -ue

# Allow setting either DATABASE_URL (takes precedence) or POSTGRES_*
POSTGRES_USERNAME="${POSTGRES_USERNAME:-kompassi}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-secret}"
POSTGRES_HOSTNAME="${POSTGRES_HOSTNAME:-postgres}"
POSTGRES_DATABASE="${POSTGRES_DATABASE:-kompassi}"
POSTGRES_EXTRAS="${POSTGRES_EXTRAS-}"
export DATABASE_URL="${DATABASE_URL:-psql://$POSTGRES_USERNAME:$POSTGRES_PASSWORD@$POSTGRES_HOSTNAME/$POSTGRES_DATABASE}${POSTGRES_EXTRAS}"

# Allow setting either BROKER_URL/CACHE_URL (takes precedence) or REDIS_HOSTNAME
REDIS_HOSTNAME="${REDIS_HOSTNAME:-redis}"
REDIS_BROKER_DATABASE="${REDIS_BROKER_DATABASE:-1}"
REDIS_CACHE_DATABASE="${REDIS_CACHE_DATABASE:-2}"
export BROKER_URL="${BROKER_URL:-redis://$REDIS_HOSTNAME/$REDIS_BROKER_DATABASE}"
export CACHE_URL="${CACHE_URL:-rediscache://$REDIS_HOSTNAME/$REDIS_CACHE_DATABASE}"

exec "$@"
