# Generated by Django 4.2.7 on 2023-11-26 09:18

from django.db import migrations, models

import kompassi.core.csv_export


class Migration(migrations.Migration):
    dependencies = [
        ("tracon2023", "0002_accessibilitywarning_timeslot"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignupExtraAfterpartyProxy",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("tracon2023.signupextra", kompassi.core.csv_export.CsvExportMixin),
        ),
        migrations.AlterField(
            model_name="signupextra",
            name="afterparty_help",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Kaatajaiset järjestyvät oman työryhmän voimin, mutta joskus lisäkädet ovat tarpeen. Oletko valmis auttamaan kaadon järjestelyissä, esim. logistiikassa tai juomien kaatamisessa? Jos olet, kirjoita tähän, mitää hommia, mihin aikaan ja kuinka paljon (karkea tuntimäärä illan aikana). Vastanneisiin otetaan yhteyttä Slackitse jos apuanne tarvitaan.",
                verbose_name="Työskentely kaatajaisissa",
            ),
        ),
    ]
