# Generated by Django 5.0.4 on 2024-06-09 12:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("tracon2023", "0003_signupextraafterpartyproxy_and_more"),
    ]

    operations = [  # noqa: RUF012
        migrations.DeleteModel(
            name="SignupExtraAfterpartyProxy",
        ),
    ]
