# Generated by Django 5.0.9 on 2024-11-28 14:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0042_alter_event_slug_alter_organization_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scope",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                (
                    "slug",
                    models.CharField(
                        help_text="The slug is a URL-friendly identifier. It may only contain lowercase letters, numbers, and hyphens. It may not be changed after creation.",
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Tekninen nimi saa sisältää vain pieniä kirjaimia, numeroita sekä väliviivoja.",
                                regex="^[a-z0-9-]+$",
                            )
                        ],
                        verbose_name="Slug",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.event"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.organization"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Universe",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "slug",
                    models.CharField(
                        help_text="The slug is a URL-friendly identifier. It may only contain lowercase letters, numbers, and hyphens. It may not be changed after creation.",
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Tekninen nimi saa sisältää vain pieniä kirjaimia, numeroita sekä väliviivoja.",
                                regex="^[a-z0-9-]+$",
                            )
                        ],
                        verbose_name="Slug",
                    ),
                ),
                (
                    "app",
                    models.CharField(choices=[("forms", "Surveys V2"), ("program_v2", "Program V2")], max_length=10),
                ),
                ("scope", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="dimensions.scope")),
            ],
        ),
        migrations.CreateModel(
            name="Dimension",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.SmallIntegerField(default=0)),
                (
                    "is_key_dimension",
                    models.BooleanField(default=False, help_text="Key dimensions are shown lists of atoms."),
                ),
                (
                    "is_multi_value",
                    models.BooleanField(
                        default=False,
                        help_text="Multi-value dimensions allow multiple values to be selected. NOTE: In the database, all dimensions are multi-value, so this is just a UI hint.",
                    ),
                ),
                (
                    "is_shown_to_subject",
                    models.BooleanField(
                        default=False,
                        help_text="If set, the subject will see the value of the dimension when atoms are listed in their profile.",
                    ),
                ),
                (
                    "is_list_filter",
                    models.BooleanField(
                        default=True, help_text="Suggests to UI that this dimension should be shown as a list filter."
                    ),
                ),
                (
                    "is_shown_in_detail",
                    models.BooleanField(
                        default=True, help_text="Suggests to UI that this dimension should be shown in detail view."
                    ),
                ),
                (
                    "is_negative_selection",
                    models.BooleanField(
                        default=False,
                        help_text="Suggests to UI that when this dimension is not being filtered on, all values should be selected. Intended for use cases when the user is expected to rather exclude certain values than only include some. One such use case is accessibility and content warnings. NOTE: Does not make sense without `is_multi_value`.",
                    ),
                ),
                (
                    "value_ordering",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("slug", "Alphabetical (slug)"),
                            ("title", "Alphabetical (localized title)"),
                        ],
                        default="title",
                        help_text="In which order are the values of this dimension returned in the GraphQL API. NOTE: When using Alphabetical (localized title), the language needs to be provided to `values` and `values.title` fields separately.",
                        max_length=6,
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        help_text="The slug is a URL-friendly identifier. It may only contain lowercase letters, numbers, and hyphens. It may not be changed after creation.",
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Tekninen nimi saa sisältää vain pieniä kirjaimia, numeroita sekä alaviivoja.",
                                regex="^[a-z0-9_]+$",
                            )
                        ],
                        verbose_name="Slug",
                    ),
                ),
                ("title_en", models.TextField(blank=True, default="")),
                ("title_fi", models.TextField(blank=True, default="")),
                ("title_sv", models.TextField(blank=True, default="")),
                (
                    "universe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="dimensions", to="dimensions.universe"
                    ),
                ),
            ],
            options={
                "ordering": ("universe", "order", "slug"),
            },
        ),
        migrations.CreateModel(
            name="DimensionValue",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_initial",
                    models.BooleanField(default=False, help_text="Initial values are set on new atoms automatically."),
                ),
                (
                    "order",
                    models.SmallIntegerField(
                        default=0, help_text="Only applies if `dimension.value_ordering` is `manual`."
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        help_text="The slug is a URL-friendly identifier. It may only contain lowercase letters, numbers, and hyphens. It may not be changed after creation.",
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Tekninen nimi saa sisältää vain pieniä kirjaimia, numeroita sekä alaviivoja.",
                                regex="^[a-z0-9_]+$",
                            )
                        ],
                        verbose_name="Slug",
                    ),
                ),
                ("color", models.CharField(blank=True, default="", max_length=63)),
                ("title_en", models.TextField(blank=True, default="")),
                ("title_fi", models.TextField(blank=True, default="")),
                ("title_sv", models.TextField(blank=True, default="")),
                (
                    "dimension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="values", to="dimensions.dimension"
                    ),
                ),
            ],
            options={
                "ordering": ("dimension", "order", "slug"),
                "unique_together": {("dimension", "slug")},
            },
        ),
        migrations.AddConstraint(
            model_name="scope",
            constraint=models.UniqueConstraint(
                fields=("organization", "event"), name="scope_unique_organization_event", nulls_distinct=False
            ),
        ),
        migrations.AddConstraint(
            model_name="scope",
            constraint=models.CheckConstraint(
                check=models.Q(("event__isnull", False), ("organization", None), _negated=True),
                name="scope_disallow_event_without_organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="dimension",
            constraint=models.UniqueConstraint(fields=("universe", "slug"), name="dimension_unique_universe_slug"),
        ),
    ]
