# Generated by Django 5.1.5 on 2025-02-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dimensions", "0002_populate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dimension",
            name="is_shown_to_subject",
        ),
        migrations.AddField(
            model_name="dimension",
            name="is_public",
            field=models.BooleanField(default=True, help_text="Public dimensions are returned to non-admin users."),
        ),
    ]
