# Generated by Django 5.1.5 on 2025-04-18 15:48

import django.core.validators
from django.db import migrations, models

import dimensions.models.dimension


class Migration(migrations.Migration):
    dependencies = [
        ("dimensions", "0005_alter_dimension_value_ordering"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dimension",
            name="slug",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Tekninen nimi saa sisältää vain pieniä kirjaimia, numeroita sekä alaviivoja.",
                        regex="^[a-z0-9_]+$",
                    ),
                    dimensions.models.dimension.invalid_slugs_validator,
                ],
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="dimensionvalue",
            name="slug",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Tekninen nimi saa sisältää vain pieniä kirjaimia, numeroita sekä alaviivoja.",
                        regex="^[a-z0-9_]+$",
                    )
                ],
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="scope",
            name="slug",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Tekninen nimi saa sisältää vain pieniä kirjaimia, numeroita sekä väliviivoja.",
                        regex="^[a-z0-9-]+$",
                    )
                ],
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="universe",
            name="slug",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Tekninen nimi saa sisältää vain pieniä kirjaimia, numeroita sekä väliviivoja.",
                        regex="^[a-z0-9-]+$",
                    )
                ],
                verbose_name="Slug",
            ),
        ),
    ]
