# Generated by Django 5.1.5 on 2025-04-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dimensions", "0006_alter_dimension_slug_alter_dimensionvalue_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dimension",
            name="is_technical",
            field=models.BooleanField(
                default=False,
                help_text="Technical dimensions are not editable in the UI. They are used for internal purposes have some assumptions about them (eg. their existence and that of certain values).",
            ),
        ),
        migrations.AddField(
            model_name="dimensionvalue",
            name="is_technical",
            field=models.BooleanField(
                default=False,
                help_text="Technical values cannot be edited in the UI. They are used for internal purposes and have some assumptions about them.",
            ),
        ),
    ]
