# Generated by Django 5.1.5 on 2025-04-27 22:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dimensions", "0008_alter_dimension_slug_alter_dimensionvalue_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dimensionvalue",
            name="is_initial",
        ),
    ]
