# Generated by Django 4.2.5 on 2023-09-26 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_v2", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="programdimensionvalue",
            old_name="dimension_value",
            new_name="value",
        ),
        migrations.AlterField(
            model_name="dimensionvalue",
            name="dimension",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="values", to="program_v2.dimension"
            ),
        ),
        migrations.AlterField(
            model_name="programdimensionvalue",
            name="dimension",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="+", to="program_v2.dimension"
            ),
        ),
        migrations.AlterField(
            model_name="programdimensionvalue",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dimensions",
                to="program_v2.program",
            ),
        ),
        migrations.AlterField(
            model_name="programdimensionvalue",
            name="value",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="+", to="program_v2.dimensionvalue"
            ),
        ),
    ]  # type: ignore
