# Generated by Django 4.2.6 on 2023-11-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_v2", "0006_offerform_active_from_offerform_active_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="programv2eventmeta",
            name="skip_offer_form_selection",
            field=models.BooleanField(
                default=False,
                help_text="If checked, the user will not be able to choose an offer form. Instead they will be redirected to the default offer form.",
                verbose_name="Skip offer form selection",
            ),
        ),
    ]
