# Generated by Django 5.0.1 on 2024-01-17 19:31

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("program_v2", "0008_alter_dimension_title_alter_dimensionvalue_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dimension",
            name="title",
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="dimensionvalue",
            name="title",
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="offerform",
            name="short_description",
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict),
        ),
        migrations.RunSQL(
            """
            alter table program_v2_dimension drop constraint if exists program_v2_dimension_title_required_en;
            alter table program_v2_dimensionvalue drop constraint if exists program_v2_dimensionvalue_title_required_en;
            """
        ),
    ]
