# Generated by Django 5.0.8 on 2024-08-18 08:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def populate_cached_event(apps, schema_editor):
    ScheduleItem = apps.get_model("program_v2", "ScheduleItem")
    for schedule_item in ScheduleItem.objects.all():
        schedule_item.cached_event = schedule_item.program.event
        schedule_item.save(update_fields=["cached_event"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_rename_emailverificationtoken_person_state_core_emailv_person__722147_idx_and_more"),
        ("program_v2", "0019_scheduleitem_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scheduleitem",
            options={"ordering": ["cached_event", "start_time"]},
        ),
        migrations.AddField(
            model_name="scheduleitem",
            name="cached_event",
            field=models.ForeignKey(
                default=1,  # type: ignore
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_items",
                to="core.event",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="scheduleitem",
            name="slug",
            field=models.CharField(
                help_text="NOTE: Slug must be unique within Event. It does not suffice to be unique within Program.",
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Tekninen nimi saa sisältää vain pieniä kirjaimia, numeroita sekä väliviivoja.",
                        regex="[a-z0-9-]+",
                    )
                ],
                verbose_name="Slug",
            ),
        ),
        migrations.RunPython(populate_cached_event),
        migrations.AlterUniqueTogether(
            name="scheduleitem",
            unique_together={("cached_event", "slug")},
        ),
    ]
