# Generated by Django 5.0.9 on 2024-09-29 06:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("program_v2", "0021_programv2eventmeta_is_accepting_feedback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="programv2eventmeta",
            name="primary_dimension",
        ),
    ]
