# Generated by Django 5.0.9 on 2024-10-26 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("program_v2", "0023_scheduleitem_favorited_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="favorited_by",
        ),
    ]
