# Generated by Django 5.0.9 on 2024-11-30 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dimensions", "0002_populate"),
        ("program_v2", "0026_programdimensionvalue_new_value_alter_dimension_slug_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="programdimensionvalue",
            options={"ordering": ("dimension__order", "new_value__order")},
        ),
        migrations.AlterUniqueTogether(
            name="programdimensionvalue",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="programdimensionvalue",
            name="new_value",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, related_name="+", to="dimensions.dimensionvalue"
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="programdimensionvalue",
            unique_together={("program", "new_value")},
        ),
    ]
