# Generated by Django 5.1.5 on 2025-04-21 19:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("program_v2", "0035_remove_programv2eventmeta_importer_name"),
    ]

    operations = [  # noqa: RUF012
        migrations.RemoveField(
            model_name="programv2eventmeta",
            name="location_dimension",
        ),
    ]
