# Generated by Django 5.1.5 on 2025-04-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_v2", "0036_remove_programv2eventmeta_location_dimension"),
    ]

    operations = [
        migrations.AddField(
            model_name="programv2eventmeta",
            name="guide_v2_embedded_url",
            field=models.CharField(
                blank=True, help_text="URL to the embedded guide. This is used to form program links.", max_length=255
            ),
        ),
    ]
