# Generated by Django 5.1.5 on 2025-04-23 15:10

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_v2", "0037_programv2eventmeta_guide_v2_embedded_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programv2eventmeta",
            name="contact_email",
            field=models.CharField(
                blank=True,
                help_text="Foo Bar &lt;foo.bar@example.com&gt;",
                max_length=255,
                validators=[django.core.validators.RegexValidator(re.compile("(?P<name>.+) <(?P<email>.+@.+\\..+)>"))],
            ),
        ),
    ]
