# Generated by Django 5.2.3 on 2025-07-18 14:46

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_v2", "0041_auto_20250625_2128"),
    ]

    operations = [
        migrations.CreateModel(
            name="Annotation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(unique=True)),
                ("title", models.JSONField(default=dict)),
                ("description", models.JSONField(default=dict)),
                (
                    "type_slug",
                    models.CharField(
                        choices=[("string", "string"), ("number", "number"), ("boolean", "boolean")],
                        default="string",
                        max_length=50,
                    ),
                ),
                ("is_applicable_to_program_items", models.BooleanField(default=True)),
                ("is_applicable_to_schedule_items", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=True)),
                ("is_shown_in_detail", models.BooleanField(default=True)),
                ("is_computed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="EventAnnotation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="If false, this annotation will not be used in this event."
                    ),
                ),
                (
                    "program_form_fields",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        help_text="List of program form field slugs this annotation will be attempted to be extracted from, in order.",
                        size=None,
                    ),
                ),
                (
                    "annotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_annotations",
                        to="program_v2.annotation",
                    ),
                ),
                (
                    "meta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_annotations",
                        to="program_v2.programv2eventmeta",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="programv2eventmeta",
            name="annotations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Annotations that are used for program in this event.",
                related_name="event_metas_using",
                through="program_v2.EventAnnotation",
                to="program_v2.annotation",
            ),
        ),
    ]
