# Generated by Django 5.2.4 on 2025-07-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_v2", "0044_nuke_eventannotation"),
    ]

    operations = [
        migrations.AddField(
            model_name="programv2eventmeta",
            name="konsti_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="URL to the Konsti signup application page for this event. This is used to form signup links.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="programv2eventmeta",
            name="guide_v2_embedded_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="URL to the embedded guide. This is used to form program links.",
                max_length=255,
            ),
        ),
    ]
