# Generated by Django 5.2.4 on 2025-08-06 20:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("program_v2", "0045_programv2eventmeta_konsti_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventannotation",
            name="annotation",
        ),
        migrations.RemoveField(
            model_name="eventannotation",
            name="meta",
        ),
        migrations.DeleteModel(
            name="Annotation",
        ),
        migrations.DeleteModel(
            name="EventAnnotation",
        ),
    ]
