# Generated by Django 5.2.4 on 2025-08-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_v2", "0046_remove_eventannotation_annotation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleitem",
            name="cached_combined_annotations",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
