# Generated by Django 5.2.4 on 2025-08-27 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paikkala", "0016_zone_ordering"),
        ("program_v2", "0047_scheduleitem_cached_combined_annotations"),
    ]

    operations = [
        migrations.AddField(
            model_name="programv2eventmeta",
            name="paikkala_default_max_tickets_per_batch",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="programv2eventmeta",
            name="paikkala_default_max_tickets_per_user",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="scheduleitem",
            name="paikkala_program",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kompassi_v2_program",
                to="paikkala.program",
            ),
        ),
    ]
