# Generated by Django 5.2.4 on 2025-09-03 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dimensions", "0017_remove_annotation_dimensions_annotation_type_annotationdatatype_and_more"),
        ("paikkala", "0016_zone_ordering"),
        ("program_v2", "0048_programv2eventmeta_paikkala_default_max_tickets_per_batch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleitem",
            name="paikkala_special_reservation_code",
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="scheduleitem",
            name="paikkala_program",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kompassi_v2_schedule_item",
                to="paikkala.program",
            ),
        ),
        migrations.CreateModel(
            name="PaikkalaRoomMapping",
            fields=[
                (
                    "room_dimension_value",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="paikkala_room_mapping",
                        serialize=False,
                        to="dimensions.dimensionvalue",
                    ),
                ),
                (
                    "paikkala_room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kompassi_v2_room_mapping",
                        to="paikkala.room",
                    ),
                ),
            ],
        ),
    ]
