# Generated by Django 5.2.4 on 2025-09-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_v2", "0049_scheduleitem_paikkala_special_reservation_code_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paikkalaroommapping",
            old_name="room_dimension_value",
            new_name="paikkala_dimension_value",
        ),
        migrations.AddField(
            model_name="scheduleitem",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
