# Generated by Django 5.2.4 on 2025-09-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_v2", "0050_rename_room_dimension_value_paikkalaroommapping_paikkala_dimension_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleitem",
            name="paikkala_icon",
            field=models.FileField(
                blank=True,
                help_text="The programme icon is used to make it harder to mix up reservations of different programmes during inspection.",
                upload_to="paikkala_icons_v2",
                verbose_name="Paikkala icon",
            ),
        ),
    ]
