# Generated by Django 6.0.3 on 2026-05-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_v2", "0052_programv2eventmeta_public_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programv2eventmeta",
            name="public_from",
            field=models.DateTimeField(
                blank=True,
                help_text="The program schedule becomes publicly visible at this point in time. Leave unset to keep the schedule private.",
                null=True,
            ),
        ),
    ]
