# Generated by Django 6.1 on 2026-09-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("program_v2", "0053_alter_programv2eventmeta_public_from"),
    ]

    operations = [  # noqa: RUF012
        migrations.AddField(
            model_name="programv2eventmeta",
            name="protect_responses",
            field=models.BooleanField(
                default=True,
                help_text="If enabled, program offers and program form responses cannot be deleted from the UI without disabling this first.",
            ),
        ),
    ]
