# Generated by Django 6.1 on 2026-09-03 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("involvement", "0014_alter_involvementeventmeta_default_registry"),
        ("program_v2", "0054_programv2eventmeta_protect_responses"),
    ]

    operations = [  # noqa: RUF012
        migrations.AlterField(
            model_name="programv2eventmeta",
            name="default_registry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="program_v2_event_metas",
                to="involvement.registry",
            ),
        ),
    ]
