# Generated by Django 1.9.1 on 2016-01-24 12:57


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0011_auto_20160124_1448"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="programmeedittoken",
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name="programmeedittoken",
            name="person",
        ),
        migrations.RemoveField(
            model_name="programmeedittoken",
            name="programme",
        ),
        migrations.DeleteModel(
            name="ProgrammeEditToken",
        ),
    ]
