# Generated by Django 1.9.1 on 2016-02-02 20:31


import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0022_auto_20160202_1950"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={
                "ordering": ("personnel_class__event", "personnel_class__priority", "priority"),
                "verbose_name": "role",
                "verbose_name_plural": "roles",
            },
        ),
        migrations.AddField(
            model_name="programme",
            name="slug",
            field=models.CharField(
                blank=True,
                help_text='Tekninen nimi eli "slug" n\xe4kyy URL-osoitteissa. Sallittuja merkkej\xe4 ovat pienet kirjaimet, numerot ja v\xe4liviiva. Teknist\xe4 nime\xe4 ei voi muuttaa luomisen j\xe4lkeen.',
                max_length=63,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Tekninen nimi saa sis\xe4lt\xe4\xe4 vain pieni\xe4 kirjaimia, numeroita sek\xe4 v\xe4liviivoja.",
                        regex="[a-z0-9-]+",
                    )
                ],
                verbose_name="Tekninen nimi",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="priority",
            field=models.IntegerField(
                default=0,
                help_text="Some events have speaker roles that convey different privileges within the same personnel class. This priority field will put the speakers in their place.",
                verbose_name="Priority",
            ),
        ),
    ]
