# Generated by Django 1.9.1 on 2016-02-02 20:31


import re

from django.db import migrations

SLUGIFY_CHAR_MAP = {
    "ä": "a",
    "å": "a",
    "ö": "o",
    "ü": "u",
    " ": "-",
    "_": "-",
    ".": "-",
}
SLUGIFY_FORBANNAD_RE = re.compile(r"[^a-z0-9-]", re.UNICODE)
SLUGIFY_MULTIDASH_RE = re.compile(r"-+", re.UNICODE)


def slugify(ustr):
    ustr = ustr.lower()
    ustr = "".join(SLUGIFY_CHAR_MAP.get(c, c) for c in ustr)
    ustr = SLUGIFY_FORBANNAD_RE.sub("", ustr)
    ustr = SLUGIFY_MULTIDASH_RE.sub("-", ustr)
    return ustr  # noqa: RET504


def populate_slug(apps, schema_editor):
    Programme = apps.get_model("programme", "programme")

    for programme in Programme.objects.all():
        if not programme.slug:
            programme.slug = slugify(programme.title)
            programme.save()


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0024_auto_20160202_2236"),
    ]

    operations = [migrations.RunPython(populate_slug, elidable=True)]
