# Generated by Django 1.9.5 on 2016-06-27 17:51


from django.db import migrations

ACTIVE_EVENTS = ["tracon11", "animecon2016", "kawacon2016"]


def populate_frozen(apps, schema_editor):
    Programme = apps.get_model("programme", "programme")
    Programme.objects.filter(state="frozen").update(frozen=True, state="accepted")
    Programme.objects.filter(state="published", category__event__slug__in=ACTIVE_EVENTS).update(frozen=False)
    Programme.objects.filter(state="published").exclude(category__event__slug__in=ACTIVE_EVENTS).update(frozen=True)


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0036_programme_frozen"),
    ]

    operations = [
        migrations.RunPython(populate_frozen, elidable=True),
    ]
