# Generated by Django 1.9.5 on 2016-07-12 11:06


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0043_auto_20160706_2211"),
    ]

    operations = [
        migrations.AddField(
            model_name="programmeeventmeta",
            name="accepting_cold_offers_from",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Accepting cold offers from"),
        ),
        migrations.AddField(
            model_name="programmeeventmeta",
            name="accepting_cold_offers_until",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Accepting cold offers until"),
        ),
        migrations.AlterField(
            model_name="programme",
            name="rerun",
            field=models.CharField(
                choices=[
                    ("already", "Yes. The programme has previously been presented in another convention."),
                    ("will", "Yes. The programme will be presented in a convention that takes place before this one."),
                    (
                        "might",
                        "Maybe. The programme might be presented in a convention that takes place before this one.",
                    ),
                    (
                        "original",
                        "No. The programme is original to this convention and I promise not to present it elsewhere before.",
                    ),
                ],
                default="original",
                help_text="Have you presented this same programme at another event before the event you are offering it to now, or do you intend to present it in another event before this one? If you are unsure about the re-run policy of this event, please consult the programme managers.",
                max_length=8,
                verbose_name="Is this a re-run?",
            ),
        ),
    ]
