# Generated by Django 1.9.9 on 2017-02-12 20:03


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("programme", "0050_auto_20161129_2147"),
    ]

    operations = [  # noqa: RUF012
        migrations.AlterUniqueTogether(
            name="room",
            unique_together={("venue", "slug")},
        ),
    ]
