# Generated by Django 1.10.8 on 2017-11-09 17:11
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("programme", "0058_populate_room_event"),
    ]

    operations = [  # noqa: RUF012
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["event", "order"], "verbose_name": "tila", "verbose_name_plural": "tilat"},
        ),
        migrations.RemoveField(
            model_name="room",
            name="venue",
        ),
    ]
