# Generated by Django 1.10.8 on 2017-12-26 22:37
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0064_auto_20171125_1326"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="active",
        ),
        migrations.AlterField(
            model_name="view",
            name="end_time",
            field=models.DateTimeField(
                blank=True,
                help_text="If the start and end times are set, this view will be constrained to those times. Use this for eg. day-specific views. If these are not set, the whole event will be displayed in a single view.",
                null=True,
                verbose_name="End time",
            ),
        ),
        migrations.AlterField(
            model_name="view",
            name="event",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="views", to="core.Event"),
        ),
        migrations.AlterField(
            model_name="view",
            name="name",
            field=models.CharField(max_length=32, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="view",
            name="order",
            field=models.IntegerField(help_text="This will be automatically filled in if not provided."),
        ),
        migrations.AlterField(
            model_name="view",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Start time"),
        ),
        migrations.AlterField(
            model_name="viewroom",
            name="order",
            field=models.IntegerField(help_text="This will be automatically filled in if not provided."),
        ),
    ]
