# Generated by Django 2.1.5 on 2019-02-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0076_auto_20190207_1753"),
    ]

    operations = [
        migrations.AddField(
            model_name="programmeeventmeta",
            name="paikkala_default_max_tickets_per_batch",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="programmeeventmeta",
            name="paikkala_default_max_tickets_per_user",
            field=models.IntegerField(default=5),
        ),
    ]
