# Generated by Django 2.1.5 on 2019-03-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ropecon2019", "0002_auto_20190226_2146"),
        ("programme", "0086_auto_20190301_0927"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="ropecon2019_preferred_time_slots",
            field=models.ManyToManyField(
                blank=True,
                help_text="When would you like to host your game program? Check the times when you would like to host your game program. If you have more specific needs regarding the timing, please let us know in the Comments field below. We do not restrict your desired times, but we reserve the right to make changes. For example, we would rather have tournaments one after another than at the same time.",
                related_name="_programme_ropecon2019_preferred_time_slots_+",
                to="ropecon2019.TimeSlot",
                verbose_name="time preferences",
            ),
        ),
        migrations.AlterField(
            model_name="programme",
            name="ropecon2019_blocked_time_slots",
            field=models.ManyToManyField(
                blank=True,
                help_text="When are you <strong>unable to run</strong> your game?<br><br>Tell us when you <strong>can not run</strong> your game. You can write more specific requests in the <em>other information</em> field below (e.g. <em>I'd like to run my game late in the evening</em>), but here we want information about limitations set by for example work or bus schedules (for example if you need to leave the venue by 11 PM to get to your accommodation in time).",
                related_name="_programme_ropecon2019_blocked_time_slots_+",
                to="ropecon2019.TimeSlot",
                verbose_name="time preferences",
            ),
        ),
    ]
