# Generated by Django 2.1.11 on 2019-08-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0092_programmefeedback_author_external_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="paikkala_icon",
            field=models.FileField(
                blank=True,
                help_text="The programme icon is used to make it harder to mix up reservations of different programmes during inspection.",
                upload_to="paikkala_icons",
                verbose_name="Programme icon",
            ),
        ),
    ]
