# Generated by Django 2.1.12 on 2019-09-19 18:36

from django.db import migrations, models

import kompassi.core.csv_export


class Migration(migrations.Migration):
    dependencies = [
        ("paikkala", "0016_zone_ordering"),
        ("programme", "0094_programme_is_paikkala_public"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaikkalaTicketCsvExportProxy",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
            },
            bases=(kompassi.core.csv_export.CsvExportMixin, "paikkala.ticket"),
        ),
        migrations.AddField(
            model_name="programme",
            name="is_paikkala_time_visible",
            field=models.BooleanField(
                default=True,
                help_text="If selected, the time of this progrmme will be shown in reservation context. This is used to hide the time in contexts in which the time is not relevant or would be misleading, particularly Tracon afterparty coaches.",
                verbose_name="Programme time is visible in Paikkala context",
            ),
        ),
    ]
