# Generated by Django 2.2.17 on 2021-02-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0101_programme_ropecon2021_gamedesk_physical_or_virtual"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="ropecon2021_accessibility_colourblind",
            field=models.BooleanField(
                default=False, verbose_name="Material used in the programme can cause problems for the colourblind"
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="ropecon2021_accessibility_flashing_lights",
            field=models.BooleanField(default=False, verbose_name="Flashing or bright lights"),
        ),
        migrations.AddField(
            model_name="programme",
            name="ropecon2021_accessibility_inaccessibility",
            field=models.TextField(
                blank=True,
                default="",
                null=True,
                verbose_name="The program involves some other form of inaccessibility. Please clarify.",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="ropecon2021_accessibility_irritate_skin",
            field=models.BooleanField(default=False, verbose_name="Materials or substances that irritate the skin"),
        ),
        migrations.AddField(
            model_name="programme",
            name="ropecon2021_accessibility_loud_sounds",
            field=models.BooleanField(default=False, verbose_name="Loud sounds"),
        ),
        migrations.AddField(
            model_name="programme",
            name="ropecon2021_accessibility_low_lightning",
            field=models.BooleanField(default=False, verbose_name="Darkness/low lighting"),
        ),
        migrations.AddField(
            model_name="programme",
            name="ropecon2021_accessibility_moving_around",
            field=models.BooleanField(
                default=False,
                verbose_name="Participation involves a lot of moving around without a chance for sitting down",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="ropecon2021_accessibility_physical_contact",
            field=models.BooleanField(
                default=False, verbose_name="Physical contact and/or low chances of personal space"
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="ropecon2021_accessibility_recording",
            field=models.BooleanField(
                default=False,
                verbose_name="Participation requires listening to a recording that does not have a text version for the hearing impaired",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="ropecon2021_accessibility_strong_smells",
            field=models.BooleanField(default=False, verbose_name="Strong smells"),
        ),
        migrations.AddField(
            model_name="programme",
            name="ropecon2021_accessibility_text",
            field=models.BooleanField(
                default=False,
                verbose_name="Participation involves reading long texts independently, and the texts are not available as recordings for those with visual impairment",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="ropecon2021_accessibility_video",
            field=models.BooleanField(
                default=False,
                verbose_name="The programme involves watching a video without subtitles for the hearing impaired",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="ropecon2021_programme_for_children",
            field=models.BooleanField(
                default=False,
                help_text="If your programme is aimed at children and their guardians, please tick this box.",
                verbose_name="Programme for children",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="ropecon2021_rpg_clarifications",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Specify here is you have any clarifications or if you have anything to expand upon regarding the above questions.",
                null=True,
                verbose_name="Any clarifications?",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="ropecon2021_rpg_physical_or_virtual",
            field=models.BooleanField(
                default=False, verbose_name="If Ropecon is held virtually, I can run my game virtually"
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="ropecon_theme",
            field=models.BooleanField(
                default=False,
                help_text="If your programme is related to the theme of Ropecon 2021, please tick this box.",
                verbose_name="Theme: Elements",
            ),
        ),
    ]
