# Generated by Django 4.1.3 on 2022-11-13 10:47

from django.db import migrations, models

import kompassi.zombies.programme.models.special_reservation


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_alter_organization_panel_css_class"),
        ("programme", "0109_alter_programme_ropecon2019_blocked_time_slots_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialreservation",
            name="code",
            field=models.CharField(
                default=kompassi.zombies.programme.models.special_reservation.get_code,
                max_length=63,
                unique=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="programmerole",
            unique_together={("person", "programme")},
        ),
    ]
