# Generated by Django 4.1.7 on 2023-03-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0113_programme_ropecon2023_chairs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="ropecon2023_furniture_needs",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Inform us here, if you need a specific kind of space (and/or furniture) for your workshop. For example if tables and chairs need to be moved for empty space in your workshop, because it is not possible to do so in every room.",
                verbose_name="Other space and furniture needs",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="ropecon2023_material_needs",
            field=models.TextField(
                blank=True,
                default="",
                help_text="If you need assistance from Ropecon in acquiring or loaning the materials, inform about your needs here. It can be for example pens and paper, flip chart, miniature parts, miniature paint, iron wire etc.",
                verbose_name="Material needs",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="ropecon2023_tables_and_chairs",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Inform us how many tables and chairs are needed in your workshop.",
                max_length=1023,
                verbose_name="Number of tables and chairs",
            ),
        ),
    ]
