# Generated by Django 4.1.7 on 2023-03-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("programme", "0114_programme_ropecon2023_furniture_needs_and_more"),
    ]

    operations = [  # noqa: RUF012
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["event", "order", "title"],
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
