# Generated by Django 5.0.1 on 2024-01-17 13:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0122_alter_programme_hosts_from_host"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="programme",
            new_name="programme_p_categor_69bbc0_idx",
            old_fields=("category", "state"),
        ),
    ]
