# Generated by Django 5.0.6 on 2024-06-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0128_category_v2_dimensions_room_v2_dimensions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alternativeprogrammeform",
            name="v2_dimensions",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="dimension slug -> list of dimension value slugs. When program is imported to v2, dimension values indicated here are added to programs of this category.",
            ),
        ),
    ]
