# Generated by Django 5.2.3 on 2025-07-11 08:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0134_alter_programme_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invitation",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="invitation",
            name="programme",
        ),
        migrations.RemoveField(
            model_name="invitation",
            name="role",
        ),
        migrations.RemoveField(
            model_name="invitation",
            name="sire",
        ),
        migrations.RemoveField(
            model_name="programmerole",
            name="invitation",
        ),
        migrations.DeleteModel(
            name="InvitationAdminProxy",
        ),
        migrations.DeleteModel(
            name="Invitation",
        ),
    ]
