# Generated by Django 1.9.9 on 2016-10-20 18:59


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labour", "0032_survey_override_does_not_apply_message"),
        ("mailings", "0006_auto_20160505_2233"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipientgroup",
            name="personnel_class",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="labour.PersonnelClass"
            ),
        ),
    ]
