# Generated by Django 4.1.7 on 2023-04-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailings", "0010_recipientgroup_programme_form"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipientgroup",
            name="verbose_name",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Nimi"),
        ),
    ]
