# Generated by Django 2.1.8 on 2019-04-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nekocon2019", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="signupextra",
            name="afterparty_participation",
            field=models.BooleanField(
                default=False, verbose_name="Haluan osallistua kaatajaisiin sunnuntaina conin jälkeen"
            ),
        ),
        migrations.AddField(
            model_name="signupextra",
            name="shift_wishes",
            field=models.TextField(
                blank=True,
                help_text="Jos tiedät nyt jo, ettet pääse paikalle johonkin tiettyyn aikaan tai haluat osallistua johonkin tiettyyn ohjelmanumeroon, mainitse siitä tässä.",
                verbose_name="Alustavat työvuorotoiveet",
            ),
        ),
        migrations.AddField(
            model_name="signupextra",
            name="shirt_size",
            field=models.CharField(
                choices=[
                    ("NO_SHIRT", "Ei paitaa"),
                    ("XS", "XS Unisex"),
                    ("S", "S Unisex"),
                    ("M", "M Unisex"),
                    ("L", "L Unisex"),
                    ("XL", "XL Unisex"),
                    ("XXL", "XXL Unisex"),
                    ("3XL", "XXL Unisex"),
                    ("LF_XS", "XS Ladyfit"),
                    ("LF_S", "S Ladyfit"),
                    ("LF_M", "M Ladyfit"),
                    ("LF_L", "L Ladyfit"),
                    ("LF_XL", "XL Ladyfit"),
                    ("LF_XXL", "XXL Ladyfit"),
                ],
                default="NO_SHIRT",
                help_text="Ajoissa ilmoittautuneet vänkärit saavat maksuttoman työvoimapaidan.",
                max_length=8,
                verbose_name="Paidan koko",
            ),
        ),
        migrations.AlterField(
            model_name="signupextra",
            name="lodging_needs",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tarvitsetko majoitusta? Merkitse ne yöt, joille tarvitset majoituksen. Kerro vapaassa alueessa, mikäli toivot majoittuvasi luokassa, jossa on vain tyttöjä tai vain poikia.",
                to="nekocon2019.Night",
                verbose_name="Majoitustarve",
            ),
        ),
        migrations.AlterField(
            model_name="signupextra",
            name="total_work",
            field=models.CharField(
                choices=[("8h", "8 tuntia"), ("10h", "10–12 tuntia"), ("yli12h", "Työn sankari! Yli 12 tuntia")],
                help_text="Kuinka paljon haluat tehdä töitä yhteensä tapahtuman aikana?",
                max_length=15,
                verbose_name="Toivottu kokonaistyömäärä",
            ),
        ),
    ]
