# Generated by Django 1.10.6 on 2017-03-21 19:03


import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventsurvey",
            name="model",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                help_text='Use the <a href="http://surveyjs.org/builder/" target="_blank">Survey.JS Builder</a> to create the survey.'
            ),
        ),
        migrations.AlterField(
            model_name="globalsurvey",
            name="model",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                help_text='Use the <a href="http://surveyjs.org/builder/" target="_blank">Survey.JS Builder</a> to create the survey.'
            ),
        ),
    ]
