# Generated by Django 1.10.7 on 2017-09-15 15:08
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("event_log", "0003_subscription_event_survey_filter"),
    ]

    operations = [  # noqa: RUF012
        migrations.AddField(
            model_name="entry",
            name="context",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The URL of the view in which the event occurred.",
                max_length=1024,
                verbose_name="Context",
            ),
        ),
    ]
