# Generated by Django 4.2.5 on 2023-09-26 08:29

import core.models.group_management_mixin
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import localized_fields.fields.char_field
import localized_fields.mixins
import psqlextra.manager.manager


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0038_alter_person_discord_handle"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dimension",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "slug",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Tekninen nimi saa sisältää vain pieniä kirjaimia, numeroita sekä väliviivoja.",
                                regex="[a-z0-9-]+",
                            )
                        ],
                    ),
                ),
                ("title", localized_fields.fields.char_field.LocalizedCharField(max_length=1023, required=["fi"])),
                ("color", models.CharField(blank=True, default="", max_length=63)),
                ("icon", models.FileField(blank=True, upload_to="program_v2/dimension_icons")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="dimensions", to="core.event"
                    ),
                ),
            ],
            options={
                "unique_together": {("event", "slug")},
            },
            bases=(localized_fields.mixins.AtomicSlugRetryMixin, models.Model),
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name="DimensionValue",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "slug",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Tekninen nimi saa sisältää vain pieniä kirjaimia, numeroita sekä väliviivoja.",
                                regex="[a-z0-9-]+",
                            )
                        ],
                    ),
                ),
                ("title", localized_fields.fields.char_field.LocalizedCharField(max_length=1023, required=["fi"])),
                ("override_color", models.CharField(blank=True, default="", max_length=63)),
                ("override_icon", models.FileField(blank=True, upload_to="program_v2/dimension_icons")),
                (
                    "dimension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dimension_values",
                        to="program_v2.dimension",
                    ),
                ),
            ],
            options={
                "unique_together": {("dimension", "slug")},
            },
            bases=(localized_fields.mixins.AtomicSlugRetryMixin, models.Model),
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=1023)),
                (
                    "slug",
                    models.CharField(
                        max_length=1023,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Tekninen nimi saa sisältää vain pieniä kirjaimia, numeroita sekä väliviivoja.",
                                regex="[a-z0-9-]+",
                            )
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("other_fields", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cached_dimensions", models.JSONField(default=dict)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="programs", to="core.event"
                    ),
                ),
            ],
            options={
                "unique_together": {("event", "slug")},
            },
        ),
        migrations.CreateModel(
            name="ScheduleItem",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subtitle", models.CharField(blank=True, max_length=255)),
                ("start_time", models.DateTimeField()),
                ("length", models.DurationField()),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_items",
                        to="program_v2.program",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProgramV2EventMeta",
            fields=[
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="%(class)s",
                        serialize=False,
                        to="core.event",
                    ),
                ),
                ("admin_group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="auth.group")),
                (
                    "primary_dimension",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_dimension_for_event_meta",
                        to="program_v2.dimension",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, core.models.group_management_mixin.GroupManagementMixin),
        ),
        migrations.CreateModel(
            name="ProgramDimensionValue",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "dimension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_dimension_values",
                        to="program_v2.dimension",
                    ),
                ),
                (
                    "dimension_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_dimension_values",
                        to="program_v2.dimensionvalue",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_dimension_values",
                        to="program_v2.program",
                    ),
                ),
            ],
            options={
                "unique_together": {("program", "dimension_value")},
            },
        ),
    ]
