# Generated by Django 4.2.6 on 2023-11-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0008_eventform_language_globalform_language"),
        ("program_v2", "0003_offerform_offerformlanguage"),
    ]

    operations = [
        migrations.AddField(
            model_name="offerform",
            name="languages",
            field=models.ManyToManyField(
                help_text="The form will be available in these languages. Each language can have its own set of fields. There must be exactly one form per supported language.",
                to="forms.eventform",
                verbose_name="language versions",
            ),
        ),
        migrations.DeleteModel(
            name="OfferFormLanguage",
        ),
    ]
