# Generated by Django 4.2.6 on 2023-11-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_v2", "0005_program_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="offerform",
            name="active_from",
            field=models.DateTimeField(
                blank=True,
                help_text="The form will be available from this date onwards. If not set, the form will not be available.",
                null=True,
                verbose_name="active from",
            ),
        ),
        migrations.AddField(
            model_name="offerform",
            name="active_until",
            field=models.DateTimeField(
                blank=True,
                help_text="The form will be available until this date. If not set, the form will be available indefinitely provided that active_from is set and has passed.",
                null=True,
                verbose_name="active until",
            ),
        ),
    ]
