# Generated by Django 2.1.12 on 2019-11-29 08:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0004_auto_20191126_1758"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formresponse",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="formresponse",
            name="form",
        ),
        migrations.DeleteModel(
            name="FormResponse",
        ),
    ]
