# Generated by Django 4.2.7 on 2023-11-26 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0011_rename_values_eventformresponse_form_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventform",
            name="language",
            field=models.CharField(choices=[("fi", "Finnish"), ("en", "English")], default="en", max_length=2),
        ),
        migrations.AlterField(
            model_name="eventformresponse",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="responses", to="forms.eventform"
            ),
        ),
        migrations.AlterField(
            model_name="globalform",
            name="language",
            field=models.CharField(choices=[("fi", "Finnish"), ("en", "English")], default="en", max_length=2),
        ),
        migrations.AlterField(
            model_name="globalformresponse",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="responses", to="forms.globalform"
            ),
        ),
    ]
