# Generated by Django 4.2.9 on 2024-01-07 06:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_alter_person_birth_date_alter_person_email_and_more"),
        ("forms", "0013_remove_eventsurvey_active_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EventSurvey",
            new_name="Survey",
        ),
        migrations.DeleteModel(
            name="GlobalSurvey",
        ),
    ]
