# Generated by Django 4.2.9 on 2024-01-14 10:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0016_rename_eventform_form_delete_globalform"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="key_fields",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                help_text="Key fields will be shown in the response list.",
                size=None,
                verbose_name="key fields",
            ),
        ),
    ]
