# Generated by Django 5.0.1 on 2024-01-18 20:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0018_survey_anonymity_survey_max_responses_per_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="cached_dimensions",
            field=models.JSONField(default=dict, help_text="dimension slug -> list of value slugs"),
        ),
        migrations.CreateModel(
            name="Dimension",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "slug",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Tekninen nimi saa sisältää vain pieniä kirjaimia, numeroita sekä väliviivoja.",
                                regex="[a-z0-9-]+",
                            )
                        ],
                    ),
                ),
                ("title", models.JSONField(blank=True, default=dict)),
                ("order", models.IntegerField(default=0)),
                (
                    "is_key_dimension",
                    models.BooleanField(
                        default=False, help_text="Key dimensions are shown in the survey responses list."
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="dimensions", to="forms.survey"
                    ),
                ),
            ],
            options={
                "ordering": ("survey", "order", "slug"),
                "unique_together": {("survey", "slug")},
            },
        ),
        migrations.CreateModel(
            name="DimensionValue",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "slug",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Tekninen nimi saa sisältää vain pieniä kirjaimia, numeroita sekä väliviivoja.",
                                regex="[a-z0-9-]+",
                            )
                        ],
                    ),
                ),
                ("title", models.JSONField(blank=True, default=dict)),
                ("color", models.CharField(blank=True, default="", max_length=63)),
                (
                    "is_initial",
                    models.BooleanField(
                        default=False, help_text="Initial values are set on new responses automatically."
                    ),
                ),
                (
                    "dimension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="values", to="forms.dimension"
                    ),
                ),
            ],
            options={
                "unique_together": {("dimension", "slug")},
            },
        ),
        migrations.CreateModel(
            name="ResponseDimensionValue",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "dimension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="forms.dimension"
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="dimensions", to="forms.response"
                    ),
                ),
                (
                    "value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="forms.dimensionvalue"
                    ),
                ),
            ],
            options={
                "unique_together": {("response", "value")},
            },
        ),
    ]
