# Generated by Django 5.0.1 on 2024-01-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0019_response_cached_dimensions_dimension_dimensionvalue_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="cached_enriched_fields",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="form",
            name="fields",
            field=models.JSONField(default=list),
        ),
    ]
