# Generated by Django 5.0.2 on 2024-04-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0024_alter_form_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("fi", "Finnish"), ("sv", "Swedish")], default="en", max_length=2
            ),
        ),
    ]
