# Generated by Django 5.0.4 on 2024-04-22 18:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0025_alter_form_language"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="subscribers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who will receive notifications when new responses are submitted.",
                related_name="subscribed_surveys",
                to=settings.AUTH_USER_MODEL,
                verbose_name="subscribers",
            ),
        ),
    ]
