# Generated by Django 5.0.9 on 2024-09-30 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import event_log_v2.utils.monthly_partitions
import event_log_v2.utils.uuid7


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0026_survey_subscribers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KeyPair",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=event_log_v2.utils.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("public_key", models.JSONField()),
                ("encrypted_private_key", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keypairs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=(event_log_v2.utils.monthly_partitions.UUID7Mixin, models.Model),
        ),
    ]
