# Generated by Django 5.0.10 on 2025-01-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0032_rename_new_value_responsedimensionvalue_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="protect_responses",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, responses cannot be deleted from the UI without disabling this first.",
            ),
        ),
    ]
