# Generated by Django 5.1.5 on 2025-02-18 18:08

import django.db.models.deletion
from django.db import migrations, models


def populate_form_survey(apps, schema_editor):
    Survey = apps.get_model("forms", "Survey")
    for survey in Survey.objects.all():
        survey.languages.update(survey=survey)


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0034_survey_app"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="survey",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="forms.survey"),
        ),
        migrations.AlterField(
            model_name="survey",
            name="app",
            field=models.CharField(
                choices=[("forms", "forms"), ("program_v2", "program_v2")],
                default="forms",
                help_text="Which app manages this survey?",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="languages",
            field=models.ManyToManyField(
                help_text="The form will be available in these languages. Each language can have its own set of fields. There must be exactly one form per supported language.",
                related_name="+",
                to="forms.form",
                verbose_name="language versions",
            ),
        ),
        migrations.RunPython(populate_form_survey, reverse_code=migrations.RunPython.noop, elidable=True),
    ]
