# Generated by Django 5.1.5 on 2025-02-18 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_emailverificationtoken_language_and_more"),
        ("forms", "0035_form_survey_alter_survey_app_alter_survey_languages"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="form",
            unique_together={("event", "survey", "language")},
        ),
        migrations.RemoveField(
            model_name="survey",
            name="languages",
        ),
        migrations.AlterField(
            model_name="form",
            name="survey",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, related_name="languages", to="forms.survey"
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="form",
            name="layout",
        ),
        migrations.RemoveField(
            model_name="form",
            name="slug",
        ),
    ]
