# Generated by Django 5.1.5 on 2025-05-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0040_survey_registry"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="cached_key_fields",
            field=models.JSONField(default=dict, help_text="key field slug -> value as in values"),
        ),
    ]
