# Generated by Django 5.1.5 on 2025-05-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0041_response_cached_key_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="purpose_slug",
            field=models.CharField(
                choices=[("DEFAULT", "DEFAULT"), ("INVITE", "INVITE")],
                default="DEFAULT",
                help_text="Generic surveys and program offers are DEFAULT, program host invitations are ACCEPT_INVITATION.",
                max_length=7,
            ),
        ),
    ]
