# Generated by Django 5.1.5 on 2025-05-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0041_response_cached_key_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="purpose_slug",
            field=models.CharField(
                choices=[("DEFAULT", "DEFAULT"), ("INVITE", "INVITE")],
                default="DEFAULT",
                help_text="Generic surveys and program offers are DEFAULT, program host invitations are ACCEPT_INVITATION.",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="anonymity",
            field=models.CharField(
                choices=[
                    ("HARD", "Hard anonymous"),
                    ("SOFT", "Soft anonymous (linked to user account but not shown to survey owner)"),
                    ("NAME_AND_EMAIL", "Name and email shown to survey owner if responded logged-in"),
                    ("FULL_PROFILE", "Full profile shown to survey owner if responded logged-in"),
                ],
                default="SOFT",
                help_text="Hard anonymous: responses are not linked to user accounts and IP addresses are not recorded. Soft anonymous: responses are linked to user accounts but not shown to survey owners. Name and email: responses are linked to user accounts and shown to survey owners.",
                max_length=14,
                verbose_name="anonymity",
            ),
        ),
    ]
