# Generated by Django 5.2.1 on 2025-05-27 17:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dimensions", "0010_alter_universe_app"),
        ("forms", "0042_survey_purpose_slug_alter_survey_anonymity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projection",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="if False, the projection API will require CBAC authorization"
                    ),
                ),
                ("default_language_code", models.CharField(default="en", max_length=2)),
                (
                    "slug",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Tekninen nimi saa sisältää vain pieniä kirjaimia, numeroita sekä väliviivoja.",
                                regex="^[a-z0-9-]+$",
                            )
                        ],
                        verbose_name="Slug",
                    ),
                ),
                ("splats", models.JSONField(blank=True, default=list)),
                (
                    "required_dimensions",
                    models.JSONField(
                        blank=True, default=dict, help_text="dimension slug -> list of dimension value slugs"
                    ),
                ),
                (
                    "projected_dimensions",
                    models.JSONField(blank=True, default=dict, help_text="target field name -> dimension slug"),
                ),
                (
                    "filterable_dimensions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of dimension slugs that can be used to filter the projection results.",
                    ),
                ),
                (
                    "order_by",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of resulting (projected) field names to order the projection results by.",
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="projections", to="dimensions.scope"
                    ),
                ),
                (
                    "surveys",
                    models.ManyToManyField(
                        blank=True,
                        help_text="These surveys must share a Universe.",
                        related_name="projections",
                        to="forms.survey",
                    ),
                ),
            ],
            options={
                "unique_together": {("scope", "slug")},
            },
        ),
    ]
