# Generated by Django 5.2.1 on 2025-05-31 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0043_projection"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="superseded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="forms.response",
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="responses_editable_until",
            field=models.DateTimeField(
                blank=True,
                help_text="If set, responses to this survey can be edited by whomever sent them until this date, provided that the response is not locked by a dimension value that is set to lock subjects. If unset, responses cannnot be edited at all. ",
                null=True,
                verbose_name="responses editable until",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="all_responses", to="forms.form"
            ),
        ),
    ]
