# Generated by Django 5.2.1 on 2025-06-13 13:33

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dimensions", "0011_dimensionvalue_is_subject_locked"),
        ("forms", "0045_rename_created_at_response_revision_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="responsedimensionvalue",
            old_name="response",
            new_name="subject",
        ),
        migrations.RenameField(
            model_name="survey",
            old_name="app",
            new_name="app_name",
        ),
        migrations.RenameField(
            model_name="surveydefaultdimensionvalue",
            old_name="survey",
            new_name="subject",
        ),
        migrations.AlterUniqueTogether(
            name="responsedimensionvalue",
            unique_together={("subject", "value")},
        ),
        migrations.AlterUniqueTogether(
            name="surveydefaultdimensionvalue",
            unique_together={("subject", "value")},
        ),
        migrations.AddIndex(
            model_name="response",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["cached_dimensions"],
                name="forms_response_gin",
                opclasses=["jsonb_path_ops"],
            ),
        ),
    ]
