# Generated by Django 5.2.3 on 2025-07-02 17:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dimensions", "0012_universe_app_name"),
        ("forms", "0050_alter_survey_app_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SurveyDefaultDimensionValue",
            new_name="SurveyDefaultResponseDimensionValue",
        ),
    ]
