# Generated by Django 5.2.3 on 2025-07-02 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0051_rename_surveydefaultdimensionvalue_surveydefaultresponsedimensionvalue"),
    ]

    operations = [
        migrations.RenameField(
            model_name="survey",
            old_name="cached_default_dimensions",
            new_name="cached_default_response_dimensions",
        ),
        migrations.AlterField(
            model_name="surveydefaultresponsedimensionvalue",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="default_response_dimensions",
                to="forms.survey",
            ),
        ),
    ]
