# Generated by Django 5.2.3 on 2025-07-04 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dimensions", "0012_universe_app_name"),
        ("forms", "0052_rename_cached_default_dimensions_survey_cached_default_response_dimensions_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyDefaultInvolvementDimensionValue",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="default_involvement_dimensions",
                        to="forms.survey",
                    ),
                ),
                (
                    "value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="dimensions.dimensionvalue"
                    ),
                ),
            ],
            options={
                "unique_together": {("subject", "value")},
            },
        ),
    ]
