# Generated by Django 2.2.10 on 2020-08-16 15:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hitpoint2020", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="signupextra",
            name="overseer",
        ),
    ]
