# Generated by Django 1.10.8 on 2018-06-11 16:43
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finncon2018", "0002_auto_20180429_2012"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signupextra",
            name="shirt_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NO_SHIRT", "Ei paitaa"),
                    ("XS", "XS Unisex"),
                    ("S", "S Unisex"),
                    ("M", "M Unisex"),
                    ("L", "L Unisex"),
                    ("XL", "XL Unisex"),
                    ("XXL", "XXL Unisex"),
                    ("3XL", "3XL Unisex"),
                    ("4XL", "4XL Unisex"),
                    ("5XL", "5XL Unisex"),
                    ("LF_XS", "XS Ladyfit"),
                    ("LF_S", "S Ladyfit"),
                    ("LF_M", "M Ladyfit"),
                    ("LF_L", "L Ladyfit"),
                    ("LF_XL", "XL Ladyfit"),
                    ("LF_2XL", "2XL Ladyfit"),
                    ("LF_3XL", "3XL Ladyfit"),
                ],
                help_text="Ajoissa ilmoittautuneet vänkärit saavat maksuttoman työvoimapaidan, mikäli ilmoittavat työskentelevänsä vähintään 8 tuntia.",
                max_length=8,
                null=True,
                verbose_name="Paidan koko",
            ),
        ),
        migrations.AlterField(
            model_name="signupextra",
            name="total_work",
            field=models.CharField(
                choices=[("4h", "4–8 tuntia"), ("8h", "8 tuntia"), ("yli8h", "Yli 8 tuntia")],
                help_text="Kuinka paljon haluat tehdä töitä yhteensä tapahtuman aikana?",
                max_length=15,
                verbose_name="Toivottu kokonaistyömäärä",
            ),
        ),
    ]
