# Generated by Django 1.9.5 on 2016-06-07 19:24


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0011_auto_20160202_2235"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accessorganizationmeta",
            options={"verbose_name": "access management settings"},
        ),
        migrations.AlterModelOptions(
            name="emailalias",
            options={"verbose_name": "e-mail alias", "verbose_name_plural": "e-mail aliases"},
        ),
        migrations.AlterModelOptions(
            name="emailaliasdomain",
            options={"verbose_name": "e-mail alias domain", "verbose_name_plural": "e-mail alias domains"},
        ),
        migrations.AlterModelOptions(
            name="emailaliastype",
            options={"verbose_name": "e-mail alias type", "verbose_name_plural": "e-mail alias types"},
        ),
        migrations.AlterModelOptions(
            name="grantedprivilege",
            options={"verbose_name": "granted privilege", "verbose_name_plural": "granted privileges"},
        ),
        migrations.AlterModelOptions(
            name="groupemailaliasgrant",
            options={"verbose_name": "group e-mail alias grant", "verbose_name_plural": "group e-mail alias grants"},
        ),
        migrations.AlterModelOptions(
            name="groupprivilege",
            options={"verbose_name": "group privilege", "verbose_name_plural": "group privileges"},
        ),
        migrations.AlterModelOptions(
            name="privilege",
            options={"verbose_name": "privilege", "verbose_name_plural": "privileges"},
        ),
        migrations.AlterModelOptions(
            name="slackaccess",
            options={"verbose_name": "Slack invite automation", "verbose_name_plural": "Slack invite automations"},
        ),
        migrations.AlterModelOptions(
            name="smtppassword",
            options={"verbose_name": "SMTP password", "verbose_name_plural": "SMTP passwords"},
        ),
        migrations.AlterModelOptions(
            name="smtpserver",
            options={"verbose_name": "SMTP server", "verbose_name_plural": "SMTP servers"},
        ),
        migrations.AlterField(
            model_name="accessorganizationmeta",
            name="admin_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="auth.Group", verbose_name="administrator group"
            ),
        ),
        migrations.AlterField(
            model_name="accessorganizationmeta",
            name="organization",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="core.Organization",
                verbose_name="organization",
            ),
        ),
        migrations.AlterField(
            model_name="emailalias",
            name="account_name",
            field=models.CharField(
                blank=True,
                help_text="Ennen @-merkki\xe4 tuleva osa s\xe4hk\xf6postiosoitetta. Muodostetaan automaattisesti jos tyhj\xe4.",
                max_length=255,
                verbose_name="account name",
            ),
        ),
        migrations.AlterField(
            model_name="emailalias",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="emailalias",
            name="domain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="access.EmailAliasDomain", verbose_name="domain"
            ),
        ),
        migrations.AlterField(
            model_name="emailalias",
            name="email_address",
            field=models.CharField(
                help_text="Muodostetaan automaattisesti", max_length=511, verbose_name="e-mail address"
            ),
        ),
        migrations.AlterField(
            model_name="emailalias",
            name="group_grant",
            field=models.ForeignKey(
                blank=True,
                help_text="My\xf6nt\xe4miskanava antaa kaikille tietyn ryhm\xe4n j\xe4senille tietyntyyppisen s\xe4hk\xf6postialiaksen. Jos aliakselle on asetettu my\xf6nt\xe4miskanava, alias on my\xf6nnetty t\xe4m\xe4n my\xf6nt\xe4miskanavan perusteella, ja kun my\xf6nt\xe4miskanava vanhenee, kaikki sen perusteella my\xf6nnetyt aliakset voidaan poistaa kerralla.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="access.GroupEmailAliasGrant",
            ),
        ),
        migrations.AlterField(
            model_name="emailalias",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="emailalias",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_aliases",
                to="core.Person",
                verbose_name="person",
            ),
        ),
        migrations.AlterField(
            model_name="emailalias",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_aliases",
                to="access.EmailAliasType",
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="emailaliasdomain",
            name="domain_name",
            field=models.CharField(help_text="eg. example.com", max_length=255, unique=True, verbose_name="domain"),
        ),
        migrations.AlterField(
            model_name="emailaliasdomain",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.Organization", verbose_name="organization"
            ),
        ),
        migrations.AlterField(
            model_name="emailaliastype",
            name="domain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="access.EmailAliasDomain", verbose_name="domain"
            ),
        ),
        migrations.AlterField(
            model_name="emailaliastype",
            name="metavar",
            field=models.CharField(
                default="firstname.lastname", help_text="eg. firstname.lastname", max_length=255, verbose_name="metavar"
            ),
        ),
        migrations.AlterField(
            model_name="slackaccess",
            name="team_name",
            field=models.CharField(max_length=255, verbose_name="Slack-yhteis\xc3\xb6n nimi"),
        ),
        migrations.AlterField(
            model_name="smtppassword",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="smtppassword",
            name="password_hash",
            field=models.CharField(max_length=255, verbose_name="password hash"),
        ),
        migrations.AlterField(
            model_name="smtppassword",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="smtp_passwords",
                to="core.Person",
                verbose_name="person",
            ),
        ),
        migrations.AlterField(
            model_name="smtppassword",
            name="smtp_server",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="smtp_passwords",
                to="access.SMTPServer",
                verbose_name="SMTP server",
            ),
        ),
        migrations.AlterField(
            model_name="smtpserver",
            name="crypto",
            field=models.CharField(
                choices=[("plain", "Ei salausta"), ("ssl", "SSL"), ("tls", "TLS")],
                default="tls",
                max_length=5,
                verbose_name="encryption",
            ),
        ),
        migrations.AlterField(
            model_name="smtpserver",
            name="domains",
            field=models.ManyToManyField(
                related_name="smtp_servers", to="access.EmailAliasDomain", verbose_name="domains"
            ),
        ),
        migrations.AlterField(
            model_name="smtpserver",
            name="hostname",
            field=models.CharField(max_length=255, verbose_name="SMTP server"),
        ),
        migrations.AlterField(
            model_name="smtpserver",
            name="port",
            field=models.IntegerField(default=587, verbose_name="port number"),
        ),
    ]
