# Generated by Django 1.10.6 on 2017-04-16 17:44
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0014_emailaliastype_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slackaccess",
            name="team_name",
            field=models.CharField(max_length=255, verbose_name="Slack-yhteisön nimi"),
        ),
    ]
