# Generated by Django 6.1.1 on 2026-09-28 19:43

from django.db import migrations, models

import kompassi.tickets_v2.optimized_server.utils.uuid7


class Migration(migrations.Migration):
    initial = True

    dependencies = []  # noqa: RUF012

    operations = [  # noqa: RUF012
        migrations.CreateModel(
            name="QueuedTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=kompassi.tickets_v2.optimized_server.utils.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("func_path", models.TextField()),
                ("args", models.JSONField(blank=True, default=list)),
                ("kwargs", models.JSONField(blank=True, default=dict)),
                ("queue_name", models.TextField(default="default")),
                ("priority", models.SmallIntegerField(default=0)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("READY", "Ready"),
                            ("RUNNING", "Running"),
                            ("FAILED", "Failed"),
                            ("SUCCESSFUL", "Successful"),
                        ],
                        default="READY",
                    ),
                ),
                ("max_attempts", models.IntegerField(default=1)),
                ("attempts", models.IntegerField(default=0)),
                ("run_after", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("last_attempted_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("errors", models.JSONField(blank=True, default=list)),
            ],
            options={
                "indexes": [
                    models.Index(
                        condition=models.Q(("status", "READY")), fields=["-priority", "id"], name="task_queue_ready_idx"
                    ),
                    models.Index(
                        condition=models.Q(("status", "RUNNING")),
                        fields=["lease_expires_at"],
                        name="task_queue_running_idx",
                    ),
                ],
            },
        ),
    ]
