# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_auto_20160216_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShirtOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Order')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ShirtSize')),
            ],
        ),
    ]
