# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-24 05:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('tickets', '0023_auto_20180212_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketseventmeta',
            name='pos_access_group',
            field=models.ForeignKey(blank=True, help_text='Members of this group are granted access to the ticket exchange view without being ticket admins.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_pos_access_group_for', to='auth.Group', verbose_name='POS access group'),
        ),
    ]
