# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-22 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import labour.models.signup_extras


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0022_auto_20160202_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('special_diet_other', models.TextField(blank=True, help_text=b'Jos noudatat erikoisruokavaliota, jota ei ole yll\xc3\xa4 olevassa listassa, ilmoita se t\xc3\xa4ss\xc3\xa4. Tapahtuman j\xc3\xa4rjest\xc3\xa4j\xc3\xa4 pyrkii ottamaan erikoisruokavaliot huomioon, mutta kaikkia erikoisruokavalioita ei v\xc3\xa4ltt\xc3\xa4m\xc3\xa4tt\xc3\xa4 pystyt\xc3\xa4 j\xc3\xa4rjest\xc3\xa4m\xc3\xa4\xc3\xa4n.', verbose_name=b'Muu erikoisruokavalio')),
                ('total_work', models.CharField(choices=[(b'8h', b'8 tuntia'), (b'12h', b'12 tuntia')], help_text=b'Kuinka paljon haluat enint\xc3\xa4\xc3\xa4n tehd\xc3\xa4 t\xc3\xb6it\xc3\xa4 yhteens\xc3\xa4 tapahtuman aikana?', max_length=15, verbose_name=b'Maksimity\xc3\xb6m\xc3\xa4\xc3\xa4r\xc3\xa4')),
                ('shift_type', models.CharField(choices=[(b'yksipitka', b'Yksi pitk\xc3\xa4 vuoro'), (b'montalyhytta', b'Monta lyhytt\xc3\xa4 vuoroa'), (b'eivalia', b'Ei v\xc3\xa4li\xc3\xa4')], help_text='Haluatko tehd\xe4 yhden pitk\xe4n ty\xf6vuoron vaiko monta lyhyemp\xe4\xe4 vuoroa?', max_length=15, verbose_name='Toivottu ty\xf6vuoron pituus')),
                ('working_days', models.CharField(choices=[(b'pe', b'Perjantaina'), (b'la', b'Lauantaina'), (b'pela', b'Molempina p\xc3\xa4ivin\xc3\xa4')], help_text=b'V\xc3\xa4nk\xc3\xa4rin\xc3\xa4 voit ottaa ty\xc3\xb6vuoroja perjantaina, lauantaina tai molempina p\xc3\xa4ivin\xc3\xa4.', max_length=4, verbose_name=b'Ty\xc3\xb6skenteleminen tapahtumassa')),
                ('prior_experience', models.TextField(blank=True, help_text=b'Kerro t\xc3\xa4ss\xc3\xa4 kent\xc3\xa4ss\xc3\xa4, jos sinulla on aiempaa kokemusta vastaavista teht\xc3\xa4vist\xc3\xa4 tai muuta sellaista ty\xc3\xb6kokemusta, josta arvioit olevan hy\xc3\xb6ty\xc3\xa4 hakemassasi teht\xc3\xa4v\xc3\xa4ss\xc3\xa4.', verbose_name=b'Ty\xc3\xb6kokemus')),
                ('shift_wishes', models.TextField(blank=True, help_text=b'Jos tied\xc3\xa4t nyt jo, ettet p\xc3\xa4\xc3\xa4se paikalle johonkin tiettyyn aikaan tai haluat osallistua johonkin tiettyyn ohjelmanumeroon, mainitse siit\xc3\xa4 t\xc3\xa4ss\xc3\xa4.', verbose_name=b'Alustavat ty\xc3\xb6vuorotoiveet')),
                ('free_text', models.TextField(blank=True, help_text=b'Jos haluat sanoa hakemuksesi k\xc3\xa4sittelij\xc3\xb6ille jotain sellaista, jolle ei ole omaa kentt\xc3\xa4\xc3\xa4 yll\xc3\xa4, k\xc3\xa4yt\xc3\xa4 t\xc3\xa4t\xc3\xa4 kentt\xc3\xa4\xc3\xa4.', verbose_name=b'Vapaa alue')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shippocon2016_signup_extras', to='core.Event')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shippocon2016_signup_extra', to='core.Person')),
            ],
            options={
                'abstract': False,
            },
            bases=(labour.models.signup_extras.SignupExtraMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SpecialDiet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
        ),
        migrations.AddField(
            model_name='signupextra',
            name='special_diet',
            field=models.ManyToManyField(blank=True, to='shippocon2016.SpecialDiet', verbose_name=b'Erikoisruokavalio'),
        ),
    ]
