# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-13 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shippocon2016', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupextra',
            name='free_text',
            field=models.TextField(blank=True, help_text='Jos haluat sanoa hakemuksesi käsittelijöille jotain sellaista, jolle ei ole omaa kenttää yllä, käytä tätä kenttää.', verbose_name='Vapaa alue'),
        ),
        migrations.AlterField(
            model_name='signupextra',
            name='prior_experience',
            field=models.TextField(blank=True, help_text='Kerro tässä kentässä, jos sinulla on aiempaa kokemusta vastaavista tehtävistä tai muuta sellaista työkokemusta, josta arvioit olevan hyötyä hakemassasi tehtävässä.', verbose_name='Työkokemus'),
        ),
        migrations.AlterField(
            model_name='signupextra',
            name='shift_type',
            field=models.CharField(choices=[('yksipitka', 'Yksi pitkä vuoro'), ('montalyhytta', 'Monta lyhyttä vuoroa'), ('eivalia', 'Ei väliä')], help_text='Haluatko tehdä yhden pitkän työvuoron vaiko monta lyhyempää vuoroa?', max_length=15, verbose_name='Toivottu työvuoron pituus'),
        ),
        migrations.AlterField(
            model_name='signupextra',
            name='shift_wishes',
            field=models.TextField(blank=True, help_text='Jos tiedät nyt jo, ettet pääse paikalle johonkin tiettyyn aikaan tai haluat osallistua johonkin tiettyyn ohjelmanumeroon, mainitse siitä tässä.', verbose_name='Alustavat työvuorotoiveet'),
        ),
        migrations.AlterField(
            model_name='signupextra',
            name='special_diet_other',
            field=models.TextField(blank=True, help_text='Jos noudatat erikoisruokavaliota, jota ei ole yllä olevassa listassa, ilmoita se tässä. Tapahtuman järjestäjä pyrkii ottamaan erikoisruokavaliot huomioon, mutta kaikkia erikoisruokavalioita ei välttämättä pystytä järjestämään.', verbose_name='Muu erikoisruokavalio'),
        ),
        migrations.AlterField(
            model_name='signupextra',
            name='total_work',
            field=models.CharField(choices=[('8h', '8 tuntia'), ('12h', '12 tuntia')], help_text='Kuinka paljon haluat enintään tehdä töitä yhteensä tapahtuman aikana?', max_length=15, verbose_name='Maksimityömäärä'),
        ),
        migrations.AlterField(
            model_name='signupextra',
            name='working_days',
            field=models.CharField(choices=[('pe', 'Perjantaina'), ('la', 'Lauantaina'), ('pela', 'Molempina päivinä')], help_text='Vänkärinä voit ottaa työvuoroja perjantaina, lauantaina tai molempina päivinä.', max_length=4, verbose_name='Työskenteleminen tapahtumassa'),
        ),
    ]
