# Generated by Django 1.9.1 on 2016-02-02 17:50


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_auto_20160131_2044"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="nick",
            field=models.CharField(
                blank=True,
                help_text="If you go by a nick name or handle that you want printed in your badge and programme details, enter it here.",
                max_length=1023,
                verbose_name="Nick name",
            ),
        ),
    ]
