# Generated by Django 1.10.7 on 2017-07-22 17:23
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_auto_20170722_1958"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="panel_css_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("panel-default", "Harmaa"),
                    ("panel-primary", "Kompassi (turkoosi)"),
                    ("panel-success", "Desucon (vihreä)"),
                    ("panel-info", "Yukicon (vaaleansininen)"),
                    ("panel-warning", "Popcult (oranssi)"),
                    ("panel-danger", "Tracon (punainen)"),
                ],
                default="panel-default",
                max_length=255,
                verbose_name="Etusivun paneelin väri",
            ),
        ),
    ]
