# Generated by Django 1.10.7 on 2017-08-27 15:18
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_auto_20170802_1453"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="logo_file",
            field=models.FileField(
                blank=True,
                help_text="Näkyy tapahtumasivulla. Jos sekä tämä että logon URL -kenttä on täytetty, käytetään tätä.",
                upload_to="event_logos",
                verbose_name="Tapahtuman logo",
            ),
        ),
        migrations.AlterField(
            model_name="carouselslide",
            name="target",
            field=models.CharField(
                blank=True, choices=[("", "Same window"), ("_blank", "New window")], default="", max_length=6
            ),
        ),
    ]
