# Generated by Django 5.0.9 on 2024-10-26 10:47

from django.db import migrations, models

import core.models.event


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_rename_emailverificationtoken_person_state_core_emailv_person__722147_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="timezone_name",
            field=models.CharField(default="Europe/Helsinki", validators=[core.models.event.validate_timezone_name]),
        ),
    ]
