# Generated by Django 6.0.7 on 2026-07-28 11:15

import django.db.models.deletion
import django_enum.fields
from django.conf import settings
from django.db import migrations, models

import kompassi.tickets_v2.optimized_server.utils.uuid7


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0044_organization_business_id"),
        ("dimensions", "0017_remove_annotation_dimensions_annotation_type_annotationdatatype_and_more"),
        ("involvement", "0010_involvementeventmeta_admin_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageBody",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("digest", models.CharField(db_index=True, max_length=128)),
                ("text", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="MessageReplyTo",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "app",
                    django_enum.fields.EnumCharField(
                        choices=[("program_v2", "PROGRAM")], default="program_v2", max_length=10
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "universe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_reply_tos",
                        to="dimensions.universe",
                    ),
                ),
            ],
            options={
                "ordering": ("universe", "name"),
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=kompassi.tickets_v2.optimized_server.utils.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "app",
                    django_enum.fields.EnumCharField(
                        choices=[("program_v2", "PROGRAM")], default="program_v2", max_length=10
                    ),
                ),
                ("subject", models.CharField(blank=True, default="", max_length=255)),
                ("body", models.TextField(blank=True, default="")),
                (
                    "dispatch",
                    django_enum.fields.EnumCharField(
                        choices=[("per_person", "PER_PERSON"), ("per_involvement", "PER_INVOLVEMENT")],
                        default="per_person",
                        max_length=15,
                    ),
                ),
                ("recipient_filters", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "universe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="dimensions.universe"
                    ),
                ),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="messages_v2.messagereplyto",
                    ),
                ),
            ],
            options={
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="MessageRecipient",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("cached_dimensions", models.JSONField(blank=True, default=dict)),
                (
                    "body",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="messages_v2.messagebody"
                    ),
                ),
                (
                    "involvement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="involvement.involvement",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="recipients", to="messages_v2.message"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="received_messages", to="core.person"
                    ),
                ),
            ],
            options={
                "ordering": ("-sent_at",),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("involvement__isnull", True)),
                        fields=("message", "person"),
                        name="messages_v2_messagerecipient_unique_person",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("involvement__isnull", False)),
                        fields=("message", "involvement"),
                        name="messages_v2_messagerecipient_unique_involvement",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="messagereplyto",
            constraint=models.CheckConstraint(
                condition=models.Q(("app__in", ["program_v2"])), name="messages_v2_MessageReplyTo_app_MessageApp"
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(("app__in", ["program_v2"])), name="messages_v2_Message_app_MessageApp"
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(("dispatch__in", ["per_person", "per_involvement"])),
                name="messages_v2_Message_dispatch_MessageDispatch",
            ),
        ),
    ]
