# Generated by Django 6.1 on 2026-08-28 14:49

import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("dimensions", "0019_rename_universe_app_name_to_app"),
        ("messages_v2", "0002_rename_program_v2_app_value_to_program"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [  # noqa: RUF012
        migrations.AlterField(
            model_name="message",
            name="app",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("forms", "FORMS"),
                    ("program", "PROGRAM"),
                    ("involvement", "INVOLVEMENT"),
                    ("volunteers", "VOLUNTEERS"),
                ],
                default="program",
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="messagereplyto",
            name="app",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("forms", "FORMS"),
                    ("program", "PROGRAM"),
                    ("involvement", "INVOLVEMENT"),
                    ("volunteers", "VOLUNTEERS"),
                ],
                default="program",
                max_length=11,
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(("app__in", ["forms", "program", "involvement", "volunteers"])),
                name="messages_v2_Message_app_DimensionApp",
            ),
        ),
        migrations.AddConstraint(
            model_name="messagereplyto",
            constraint=models.CheckConstraint(
                condition=models.Q(("app__in", ["forms", "program", "involvement", "volunteers"])),
                name="messages_v2_MessageReplyTo_app_DimensionApp",
            ),
        ),
    ]
