# Generated by Django 4.0.6 on 2022-08-23 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_alter_organization_panel_css_class"),
        ("ropecon2019", "0004_auto_20190909_2157"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signupextra",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_signup_extras", to="core.event"
            ),
        ),
        migrations.AlterField(
            model_name="signupextra",
            name="person",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_signup_extra", to="core.person"
            ),
        ),
    ]
