# Generated by Django 1.10.8 on 2018-07-18 11:33
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0003_externalevent_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalevent",
            name="logo_file",
            field=models.FileField(blank=True, upload_to="external_event_logos"),
        ),
    ]
