# Generated by Django 2.2.10 on 2020-03-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("listings", "0004_externalevent_logo_file"),
    ]

    operations = [  # noqa: RUF012
        migrations.AddField(
            model_name="externalevent",
            name="cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
