# Generated by Django 5.0.9 on 2024-12-07 14:50

import django.db.models.deletion
from django.db import migrations, models

import labour.models.signup_extras


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0042_alter_event_slug_alter_organization_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventDay",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=63)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KnownLanguage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=63)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NativeLanguage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=63)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SpecialDiet",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=63)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SignupExtra",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "shift_type",
                    models.CharField(
                        choices=[
                            ("yksipitka", "Yksi pitkä vuoro"),
                            ("montalyhytta", "Monta lyhyempää vuoroa"),
                            ("kaikkikay", "Kumpi tahansa käy"),
                        ],
                        help_text="Haluatko tehdä yhden pitkän työvuoron vaiko monta lyhyempää vuoroa?",
                        max_length=15,
                        verbose_name="Toivottu työvuoron pituus",
                    ),
                ),
                (
                    "shift_leader",
                    models.BooleanField(
                        default=False,
                        verbose_name="Oletko kiinnostunut vuorovastaavan tehtävistä? Vuorovastaava koordinoi vuoron aikana tehtäviä ja tauotuksia.",
                    ),
                ),
                (
                    "total_work",
                    models.CharField(
                        choices=[
                            ("8h", "Minimi - 8 tuntia"),
                            ("10h", "8-10 tuntia"),
                            ("yli10h", "Työn Sankari! Yli 10 tuntia!"),
                        ],
                        help_text="Kuinka paljon haluat tehdä töitä yhteensä tapahtuman aikana?",
                        max_length=15,
                        verbose_name="Toivottu kokonaistyömäärä",
                    ),
                ),
                (
                    "build_participation",
                    models.CharField(
                        choices=[
                            ("ei", "En pysty osallistumaan kumpaankaan"),
                            ("kasaus", "Pystyn osallistumaan vain kasaukseen"),
                            ("purku", "Pystyn osallistumaan vain purkuun"),
                            ("molemmat", "Pystyn osallistumaan molempiin"),
                        ],
                        help_text="Valitse pystytkö osallistumaan kasaukseen ja/tai purkuun",
                        max_length=15,
                        verbose_name="Kasaus ja purku",
                    ),
                ),
                (
                    "shirt_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NO_SHIRT", "Ei paitaa"),
                            ("XS", "XS Unisex"),
                            ("S", "S Unisex"),
                            ("M", "M Unisex"),
                            ("L", "L Unisex"),
                            ("XL", "XL Unisex"),
                            ("XXL", "XXL Unisex"),
                            ("3XL", "3XL Unisex"),
                            ("4XL", "4XL Unisex"),
                            ("5XL", "5XL Unisex"),
                        ],
                        default="NO_SHIRT",
                        help_text="Ajoissa ilmoittautuneet vänkärit saattavat saada maksuttoman työvoimapaidan.",
                        max_length=8,
                        verbose_name="Paidan koko",
                    ),
                ),
                (
                    "parking_needed",
                    models.BooleanField(default=False, verbose_name="Tarvitsetko autollesi pysäköintilupaa?"),
                ),
                (
                    "car_regnr",
                    models.TextField(blank=True, verbose_name="Auton rekisterinumero (pysäköintilupaa varten)"),
                ),
                ("native_language_other", models.TextField(blank=True, verbose_name="Muu äidinkieli")),
                ("known_language_other", models.TextField(blank=True, verbose_name="Muu osaamasi kieli")),
                (
                    "special_diet_other",
                    models.TextField(
                        blank=True,
                        help_text="Jos noudatat erikoisruokavaliota, jota ei ole yllä olevassa listassa, ilmoita se tässä. Tapahtuman järjestäjä pyrkii ottamaan erikoisruokavaliot huomioon, mutta kaikkia erikoisruokavalioita ei välttämättä pystytä järjestämään.",
                        verbose_name="Muu erikoisruokavalio",
                    ),
                ),
                (
                    "shift_wishes",
                    models.TextField(
                        blank=True,
                        help_text="Jos tiedät nyt jo, ettet pääse paikalle johonkin tiettyyn aikaan tai haluat osallistua johonkin tiettyyn ohjelmanumeroon, mainitse siitä tässä.",
                        verbose_name="Alustavat työvuorotoiveet",
                    ),
                ),
                (
                    "why_work",
                    models.TextField(
                        blank=True,
                        help_text="Kerro mikä Shumiconissa viehättää ja miksi haluaisit tulla juuri tähän tapahtumaan",
                        verbose_name="Miksi haluaisit työskennellä Shumiconissa?",
                    ),
                ),
                (
                    "why_you",
                    models.TextField(
                        blank=True,
                        help_text="Kerro miksi hait juuri kyseisiin tehtäviin ja miksi juuri sinut tulisi valita",
                        verbose_name="Miksi olisit hyvä valinta hakemaasi työtehtävään?",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_signup_extras",
                        to="core.event",
                    ),
                ),
                (
                    "known_language",
                    models.ManyToManyField(
                        blank=True, to="shumicon2025.knownlanguage", verbose_name="Muut osaamasi kielet"
                    ),
                ),
                (
                    "native_language",
                    models.ManyToManyField(to="shumicon2025.nativelanguage", verbose_name="Äidinkielesi"),
                ),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_signup_extra",
                        to="core.person",
                    ),
                ),
                (
                    "work_days",
                    models.ManyToManyField(
                        help_text="Minä päivinä olet halukas työskentelemään?",
                        to="shumicon2025.eventday",
                        verbose_name="Tapahtumapäivät",
                    ),
                ),
                (
                    "special_diet",
                    models.ManyToManyField(blank=True, to="shumicon2025.specialdiet", verbose_name="Erikoisruokavalio"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(labour.models.signup_extras.SignupExtraMixin, models.Model),
        ),
    ]
