name: frontend

on:
  push:
    paths:
      - kompassi-v2-frontend/**
      - .github/workflows/frontend.yaml
    branches:
      - main
  pull_request:
    paths:
      - kompassi-v2-frontend/**
      - .github/workflows/frontend.yaml
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v4
      - id: build
        uses: docker/build-push-action@v6
        with:
          context: kompassi-v2-frontend
          tags: ghcr.io/con2/kompassi2:${{ github.sha }}
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          provenance: false
          cache-from: type=registry,ref=ghcr.io/con2/kompassi2:buildcache
          cache-to: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') && 'type=registry,ref=ghcr.io/con2/kompassi2:buildcache,mode=max' || '' }}
      - run: |
          cat > build.json <<EOF
          {"builds":[{"imageName":"kompassi2","tag":"ghcr.io/con2/kompassi2:${{ github.sha }}@${{ steps.build.outputs.digest }}"}]}
          EOF
      - name: Store build.json artifact
        uses: actions/upload-artifact@v7
        with:
          name: build-json
          path: build.json

  # TODO Placeholder for actual tests, so that we can require step "test" to succeed for automerge (backend actually has one)
  test:
    runs-on: ubuntu-latest
    steps:
      - run: "true"

  deploy_staging:
    runs-on: qb-arc-runners
    needs: build
    environment: Staging
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/download-artifact@v8
        with:
          name: build-json
          path: kompassi-v2-frontend/
      - uses: actions/setup-node@v7
        with:
          node-version: 24

      - id: cache-bin
        uses: actions/cache@v6
        with:
          path: bin
          key: ${{ runner.os }}-bin-3
      - if: steps.cache-bin.outputs.cache-hit != 'true'
        run: |
          mkdir bin
          curl -Lo bin/skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          curl -Lo bin/kubectl https://dl.k8s.io/release/v1.36.2/bin/linux/amd64/kubectl
          chmod +x bin/skaffold bin/kubectl
      - run: echo "$PWD/bin" >> $GITHUB_PATH
      - run: node --experimental-strip-types manifest.ts
        working-directory: kompassi-v2-frontend/kubernetes
        env:
          ENV: staging
      - run: skaffold deploy -n kompassi2-staging -a build.json
        working-directory: kompassi-v2-frontend

  deploy_production:
    runs-on: qb-arc-runners
    needs: build
    environment: Production
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/download-artifact@v8
        with:
          name: build-json
          path: kompassi-v2-frontend/
      - uses: actions/setup-node@v7
        with:
          node-version: 24

      - id: cache-bin
        uses: actions/cache@v6
        with:
          path: bin
          key: ${{ runner.os }}-bin-3
      - if: steps.cache-bin.outputs.cache-hit != 'true'
        run: |
          mkdir bin
          curl -Lo bin/skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          curl -Lo bin/kubectl https://dl.k8s.io/release/v1.36.2/bin/linux/amd64/kubectl
          chmod +x bin/skaffold bin/kubectl
      - run: echo "$PWD/bin" >> $GITHUB_PATH
      - run: node --experimental-strip-types manifest.ts
        working-directory: kompassi-v2-frontend/kubernetes
        env:
          ENV: production
      - run: skaffold deploy -n kompassi2-production -a build.json
        working-directory: kompassi-v2-frontend
