name: lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: true
      - uses: actions/setup-python@v7
        with:
          python-version-file: ".python-version"
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: kompassi-v2-frontend/package-lock.json

      - run: uv sync --locked
      - run: npm ci
        working-directory: kompassi-v2-frontend

      - uses: j178/prek-action@v3.0.0
