apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      stack: kompassi
      component: postgres
  template:
    metadata:
      labels:
        stack: kompassi
        component: postgres
    spec:
      enableServiceLinks: false
      containers:
        - name: master
          image: !Var postgres_image
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: !Var postgres_database
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: postgres-data
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - kompassi
            initialDelaySeconds: 15
            periodSeconds: 30
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - kompassi
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
