# Generated by Django 1.9.9 on 2017-02-20 17:36


import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackMessage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("context", models.CharField(blank=True, max_length=1024)),
                (
                    "author_ip_address",
                    models.CharField(blank=True, default="", max_length=48, verbose_name="IP address"),
                ),
                ("feedback", models.TextField(verbose_name="feedback")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "feedback message",
                "verbose_name_plural": "feedback messages",
            },
        ),
    ]
