# Generated by Django 1.10.7 on 2017-07-22 16:58
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("core", "0025_auto_20170722_1954"),
    ]

    operations = [  # noqa: RUF012
        migrations.AlterModelOptions(
            name="carouselslide",
            options={
                "ordering": ("order", "-active_from"),
                "verbose_name": "carousel slide",
                "verbose_name_plural": "carousel slides",
            },
        ),
    ]
