# Generated by Django 1.10.8 on 2018-09-26 09:52
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_auto_20170827_1818"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="muncipality",
            field=models.CharField(
                blank=True,
                help_text="Virallinen kotikuntasi eli kunta jossa olet kirjoilla. Kotikunta ja väestörekisteriin merkityt etunimesi (kaikki) ovat pakollisia tietoja, mikäli kuulut tai haluat liittyä johonkin yhdistykseen joka käyttää tätä sivustoa jäsenrekisterin hallintaan.",
                max_length=127,
                verbose_name="Kotikunta",
            ),
        ),
    ]
