# Generated by Django 4.2.7 on 2023-11-26 09:18

from django.db import migrations, models

import kompassi.core.models.person
import kompassi.core.utils.model_utils


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_alter_person_discord_handle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="birth_date",
            field=models.DateField(
                blank=True,
                help_text="Birth date in the following format: DD.MM.YYYY",
                null=True,
                validators=[kompassi.core.models.person.birth_date_validator],
                verbose_name="Syntymäaika",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Email is the primary means of contact for event-related matters.",
                max_length=255,
                verbose_name="email address",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="may_send_info",
            field=models.BooleanField(
                default=False, verbose_name="I may be sent information about future events by email <i>(optional)</i>"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Your phone number is used only for urgent contact regarding your participation in the event.",
                max_length=255,
                validators=[kompassi.core.utils.model_utils.phone_number_validator],
                verbose_name="phone number",
            ),
        ),
    ]
