# Generated by Django 5.0.1 on 2024-01-17 13:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_alter_person_birth_date_alter_person_email_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="emailverificationtoken",
            new_name="core_emailv_person__722147_idx",
            old_fields=("person", "state"),
        ),
        migrations.RenameIndex(
            model_name="passwordresettoken",
            new_name="core_passwo_person__f14579_idx",
            old_fields=("person", "state"),
        ),
    ]
