# Generated by Django 6.1 on 2026-09-02 21:31

from django.db import migrations

import kompassi.core.models.enums
import kompassi.field_types


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("core", "0044_organization_business_id"),
    ]

    operations = [  # noqa: RUF012
        # The AddField below emits ADD COLUMN ... core_programroleretentionpolicy,
        # so the enum type must exist first.
        migrations.RunSQL(
            "create type core_programroleretentionpolicy as enum ('REMOVE', 'RETAIN')",
            reverse_sql="drop type core_programroleretentionpolicy",
        ),
        migrations.AddField(
            model_name="person",
            name="program_role_retention_policy",
            field=kompassi.field_types.PostgresEnumField(
                blank=True,
                choices=[
                    ("REMOVE", "Remove me from the hosts of my past program items when the retention period expires"),
                    ("RETAIN", "Retain me as the host of my past program items until I choose otherwise"),
                ],
                db_type_name="core_programroleretentionpolicy",
                enum=kompassi.core.models.enums.ProgramRoleRetentionPolicy,
                help_text="Personal data related to your participation in events is deleted after the retention period of the event organizer has passed. Many are, however, proud of their program history and wish to remain listed as the host of their past program items. You can choose here whether your program host roles are retained beyond the retention period.",
                null=True,
                verbose_name="Retention of program host roles",
            ),
        ),
    ]
