# Generated by Django 1.9.1 on 2016-01-29 21:39


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0015_auto_20160129_2245"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="job_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Please stay civil with the job title field.",
                max_length=63,
                verbose_name="Job title",
            ),
        ),
    ]
