# Generated by Django 1.9.5 on 2016-07-06 19:07


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0019_auto_20160627_2018"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="batch",
            options={"verbose_name": "Batch", "verbose_name_plural": "Batches"},
        ),
    ]
