# Generated by Django 4.1.4 on 2022-12-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0024_badgeseventmeta_onboarding_access_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="badgeseventmeta",
            name="onboarding_instructions_markdown",
            field=models.TextField(
                blank=True,
                default="",
                help_text="These instructions will be shown at the top of the onboarding view. Markdown formatting available.",
                verbose_name="onboarding instructions",
            ),
        ),
    ]
